//! Forge GPU Code Generation — WGSL compute shader emission.
//!
//! Generates a complete Cargo project that runs GPU inference via wgpu
//! (Vulkan, Metal, DX12, WebGPU). The project embeds WGSL compute shaders
//! as string constants and uses wgpu to dispatch them at runtime.

use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;

use forgellm_frontend::ir::*;

/// Errors during GPU code generation.
#[derive(Debug, thiserror::Error)]
pub enum GpuCodegenError {
    #[error("graph has no model config")]
    MissingConfig,

    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("format error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

/// Generate a complete GPU Cargo project from a computation graph.
///
/// Creates:
/// - `Cargo.toml` — with wgpu + pollster + tokenizers dependencies
/// - `src/main.rs` — CLI that reads weights + tokenizer, runs GPU inference
/// - `src/model.rs` — GPU model with embedded WGSL compute shaders
pub fn generate_gpu_project(
    graph: &Graph,
    output_dir: &Path,
    model_name: &str,
) -> Result<(), GpuCodegenError> {
    let config = graph
        .config
        .as_ref()
        .ok_or(GpuCodegenError::MissingConfig)?;

    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;

    fs::write(
        output_dir.join("Cargo.toml"),
        generate_cargo_toml(model_name),
    )?;

    let model_rs = generate_model_rs(config)?;
    fs::write(src_dir.join("model.rs"), model_rs)?;

    let main_rs = generate_main_rs(model_name, config)?;
    fs::write(src_dir.join("main.rs"), main_rs)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn sanitize_name(name: &str) -> String {
    name.to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string()
}

fn generate_cargo_toml(model_name: &str) -> String {
    let sanitized = sanitize_name(model_name);
    format!(
        r#"[package]
name = "{sanitized}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{sanitized}"
path = "src/main.rs"

[dependencies]
wgpu = "22"
pollster = "0.3"
tokenizers = {{ version = "0.21", default-features = false, features = ["onig"] }}

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"#
    )
}

// ---------------------------------------------------------------------------
// model.rs generation
// ---------------------------------------------------------------------------

fn generate_model_rs(config: &ModelConfig) -> Result<String, GpuCodegenError> {
    let mut code = String::with_capacity(32 * 1024);
    emit_model_header(&mut code, config)?;
    emit_wgsl_shaders(&mut code)?;
    emit_gpu_model_struct(&mut code, config)?;
    emit_gpu_model_impl(&mut code, config)?;
    Ok(code)
}

fn emit_model_header(code: &mut String, config: &ModelConfig) -> Result<(), GpuCodegenError> {
    writeln!(code, "//! Auto-generated by ForgeLLM GPU codegen.")?;
    writeln!(
        code,
        "//! Model: {} ({} layers, hidden={})",
        config.architecture, config.num_layers, config.hidden_size
    )?;
    writeln!(code, "//!")?;
    writeln!(
        code,
        "//! Uses wgpu compute pipelines with embedded WGSL shaders."
    )?;
    writeln!(code)?;
    writeln!(code, "#![allow(dead_code)]")?;
    writeln!(code)?;

    // Model constants
    writeln!(
        code,
        "// ── Model constants ──────────────────────────────────"
    )?;
    writeln!(code, "pub const HIDDEN_SIZE: u32 = {};", config.hidden_size)?;
    writeln!(
        code,
        "pub const INTERMEDIATE_SIZE: u32 = {};",
        config.intermediate_size
    )?;
    writeln!(code, "pub const NUM_LAYERS: u32 = {};", config.num_layers)?;
    writeln!(
        code,
        "pub const NUM_HEADS: u32 = {};",
        config.num_attention_heads
    )?;
    writeln!(
        code,
        "pub const NUM_KV_HEADS: u32 = {};",
        config.num_kv_heads
    )?;
    writeln!(code, "pub const HEAD_DIM: u32 = {};", config.head_dim)?;
    writeln!(code, "pub const VOCAB_SIZE: u32 = {};", config.vocab_size)?;
    let effective_seq_len = config.max_seq_len.min(4096);
    writeln!(
        code,
        "pub const MAX_SEQ_LEN: u32 = {};  // capped from model's {}",
        effective_seq_len, config.max_seq_len
    )?;
    writeln!(
        code,
        "pub const RMS_NORM_EPS: f32 = {:e};",
        config.rms_norm_eps
    )?;
    writeln!(code, "pub const ROPE_THETA: f32 = {:e};", config.rope_theta)?;
    writeln!(code)?;

    Ok(())
}

fn emit_wgsl_shaders(code: &mut String) -> Result<(), GpuCodegenError> {
    // Each WGSL shader is emitted as a Rust `pub const &str`.
    // We cannot use r#"..."# format strings that themselves embed "# sequences,
    // so we build each constant declaration via push_str pieces.

    // ── matmul ──────────────────────────────────────────────────────────────
    code.push_str(
        "/// WGSL compute shader: matrix-vector multiply (rows x cols) x (cols,) -> (rows,).\n",
    );
    code.push_str("pub const SHADER_MATMUL: &str = concat!(\n");
    code.push_str(
        "    \"@group(0) @binding(0) var<storage, read>       weight : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(1) var<storage, read>       input  : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(2) var<storage, read_write> output : array<f32>;\\n\",\n",
    );
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"struct Dims { rows: u32, cols: u32 }\\n\",\n");
    code.push_str("    \"@group(0) @binding(3) var<uniform> dims : Dims;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"@compute @workgroup_size(64)\\n\",\n");
    code.push_str("    \"fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\\n\",\n");
    code.push_str("    \"    let row = gid.x;\\n\",\n");
    code.push_str("    \"    if row >= dims.rows { return; }\\n\",\n");
    code.push_str("    \"    var acc = 0.0f;\\n\",\n");
    code.push_str("    \"    for (var k = 0u; k < dims.cols; k++) {\\n\",\n");
    code.push_str("    \"        acc += weight[row * dims.cols + k] * input[k];\\n\",\n");
    code.push_str("    \"    }\\n\",\n");
    code.push_str("    \"    output[row] = acc;\\n\",\n");
    code.push_str("    \"}\\n\",\n");
    code.push_str(");\n\n");

    // ── rms_norm ─────────────────────────────────────────────────────────────
    code.push_str("/// WGSL compute shader: RMS normalisation.\n");
    code.push_str("pub const SHADER_RMS_NORM: &str = concat!(\n");
    code.push_str(
        "    \"@group(0) @binding(0) var<storage, read>       input  : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(1) var<storage, read>       weight : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(2) var<storage, read_write> output : array<f32>;\\n\",\n",
    );
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"struct Dims { n: u32, _pad: u32 }\\n\",\n");
    code.push_str("    \"@group(0) @binding(3) var<uniform> dims : Dims;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"const EPS: f32 = 1e-5f;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"@compute @workgroup_size(1)\\n\",\n");
    code.push_str("    \"fn main(@builtin(global_invocation_id) _gid: vec3<u32>) {\\n\",\n");
    code.push_str("    \"    let n = dims.n;\\n\",\n");
    code.push_str("    \"    var sum_sq = 0.0f;\\n\",\n");
    code.push_str(
        "    \"    for (var i = 0u; i < n; i++) { sum_sq += input[i] * input[i]; }\\n\",\n",
    );
    code.push_str("    \"    let inv_rms = 1.0f / sqrt(sum_sq / f32(n) + EPS);\\n\",\n");
    code.push_str(
        "    \"    for (var i = 0u; i < n; i++) { output[i] = input[i] * inv_rms * weight[i]; }\\n\",\n",
    );
    code.push_str("    \"}\\n\",\n");
    code.push_str(");\n\n");

    // ── rope ─────────────────────────────────────────────────────────────────
    code.push_str("/// WGSL compute shader: Rotary Position Embedding (RoPE).\n");
    code.push_str("pub const SHADER_ROPE: &str = concat!(\n");
    code.push_str(
        "    \"@group(0) @binding(0) var<storage, read_write> data : array<f32>;\\n\",\n",
    );
    code.push_str("    \"\\n\",\n");
    code.push_str(
        "    \"struct RopeDims { num_heads: u32, head_dim: u32, pos: u32, _pad: u32 }\\n\",\n",
    );
    code.push_str("    \"@group(0) @binding(1) var<uniform> dims : RopeDims;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"const THETA: f32 = 10000.0f;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"@compute @workgroup_size(64)\\n\",\n");
    code.push_str("    \"fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\\n\",\n");
    code.push_str("    \"    let h = gid.x;\\n\",\n");
    code.push_str("    \"    if h >= dims.num_heads { return; }\\n\",\n");
    code.push_str("    \"    let half = dims.head_dim / 2u;\\n\",\n");
    code.push_str("    \"    let off  = h * dims.head_dim;\\n\",\n");
    code.push_str("    \"    for (var i = 0u; i < half; i++) {\\n\",\n");
    code.push_str(
        "    \"        let freq = 1.0f / pow(THETA, 2.0f * f32(i) / f32(dims.head_dim));\\n\",\n",
    );
    code.push_str("    \"        let angle = f32(dims.pos) * freq;\\n\",\n");
    code.push_str("    \"        let c = cos(angle); let s = sin(angle);\\n\",\n");
    code.push_str("    \"        let x0 = data[off + 2u * i];\\n\",\n");
    code.push_str("    \"        let x1 = data[off + 2u * i + 1u];\\n\",\n");
    code.push_str("    \"        data[off + 2u * i]      = x0 * c - x1 * s;\\n\",\n");
    code.push_str("    \"        data[off + 2u * i + 1u] = x0 * s + x1 * c;\\n\",\n");
    code.push_str("    \"    }\\n\",\n");
    code.push_str("    \"}\\n\",\n");
    code.push_str(");\n\n");

    // ── softmax ───────────────────────────────────────────────────────────────
    code.push_str("/// WGSL compute shader: softmax over a 1-D array.\n");
    code.push_str("pub const SHADER_SOFTMAX: &str = concat!(\n");
    code.push_str(
        "    \"@group(0) @binding(0) var<storage, read_write> data : array<f32>;\\n\",\n",
    );
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"struct Dims { n: u32, _pad: u32 }\\n\",\n");
    code.push_str("    \"@group(0) @binding(1) var<uniform> dims : Dims;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"@compute @workgroup_size(1)\\n\",\n");
    code.push_str("    \"fn main(@builtin(global_invocation_id) _gid: vec3<u32>) {\\n\",\n");
    code.push_str("    \"    let n = dims.n;\\n\",\n");
    code.push_str("    \"    var max_val = data[0];\\n\",\n");
    code.push_str(
        "    \"    for (var i = 1u; i < n; i++) { if data[i] > max_val { max_val = data[i]; } }\\n\",\n",
    );
    code.push_str("    \"    var sum = 0.0f;\\n\",\n");
    code.push_str(
        "    \"    for (var i = 0u; i < n; i++) { data[i] = exp(data[i] - max_val); sum += data[i]; }\\n\",\n",
    );
    code.push_str("    \"    let inv = 1.0f / sum;\\n\",\n");
    code.push_str("    \"    for (var i = 0u; i < n; i++) { data[i] *= inv; }\\n\",\n");
    code.push_str("    \"}\\n\",\n");
    code.push_str(");\n\n");

    // ── silu_mul ─────────────────────────────────────────────────────────────
    code.push_str("/// WGSL compute shader: SiLU-multiply (gate x up projection fusion).\n");
    code.push_str("/// output[i] = gate[i] / (1 + exp(-gate[i])) * up[i]\n");
    code.push_str("pub const SHADER_SILU_MUL: &str = concat!(\n");
    code.push_str(
        "    \"@group(0) @binding(0) var<storage, read>       gate   : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(1) var<storage, read>       up     : array<f32>;\\n\",\n",
    );
    code.push_str(
        "    \"@group(0) @binding(2) var<storage, read_write> output : array<f32>;\\n\",\n",
    );
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"struct Dims { n: u32, _pad: u32 }\\n\",\n");
    code.push_str("    \"@group(0) @binding(3) var<uniform> dims : Dims;\\n\",\n");
    code.push_str("    \"\\n\",\n");
    code.push_str("    \"@compute @workgroup_size(64)\\n\",\n");
    code.push_str("    \"fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\\n\",\n");
    code.push_str("    \"    let i = gid.x;\\n\",\n");
    code.push_str("    \"    if i >= dims.n { return; }\\n\",\n");
    code.push_str("    \"    let g = gate[i];\\n\",\n");
    code.push_str("    \"    output[i] = (g / (1.0f + exp(-g))) * up[i];\\n\",\n");
    code.push_str("    \"}\\n\",\n");
    code.push_str(");\n\n");

    Ok(())
}

fn emit_gpu_model_struct(code: &mut String, config: &ModelConfig) -> Result<(), GpuCodegenError> {
    let num_layers = config.num_layers;

    writeln!(
        code,
        "// ── GpuModel ──────────────────────────────────────────"
    )?;
    writeln!(code)?;
    writeln!(code, "/// GPU-accelerated transformer model.")?;
    writeln!(code, "///")?;
    writeln!(
        code,
        "/// Created by [`GpuModel::new`] which uploads weight tensors to GPU"
    )?;
    writeln!(
        code,
        "/// buffers and compiles all compute pipelines once at startup."
    )?;
    writeln!(code, "pub struct GpuModel {{")?;
    writeln!(code, "    device: wgpu::Device,")?;
    writeln!(code, "    queue: wgpu::Queue,")?;
    writeln!(code)?;
    writeln!(code, "    // ── Compute pipelines ──")?;
    writeln!(code, "    matmul_pipeline:   wgpu::ComputePipeline,")?;
    writeln!(code, "    rms_norm_pipeline: wgpu::ComputePipeline,")?;
    writeln!(code, "    rope_pipeline:     wgpu::ComputePipeline,")?;
    writeln!(code, "    softmax_pipeline:  wgpu::ComputePipeline,")?;
    writeln!(code, "    silu_mul_pipeline: wgpu::ComputePipeline,")?;
    writeln!(code)?;
    writeln!(code, "    // ── Weight buffers ──")?;
    writeln!(
        code,
        "    /// Token embedding table [VOCAB_SIZE, HIDDEN_SIZE]"
    )?;
    writeln!(code, "    embed_buf: wgpu::Buffer,")?;
    writeln!(code)?;
    writeln!(
        code,
        "    /// Per-layer attention + FFN weight buffers ({num_layers} layers)"
    )?;
    writeln!(code, "    /// Index: [layer][projection]")?;
    writeln!(
        code,
        "    /// Projections: 0=q, 1=k, 2=v, 3=o, 4=gate, 5=up, 6=down"
    )?;
    writeln!(
        code,
        "    weight_buffers: Vec<Vec<wgpu::Buffer>>,  // [num_layers][7]"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "    /// RMS norm weights: [layer][0=attn_norm, 1=ffn_norm]"
    )?;
    writeln!(code, "    norm_buffers: Vec<Vec<wgpu::Buffer>>,")?;
    writeln!(code)?;
    writeln!(code, "    /// Final layer-norm weight [HIDDEN_SIZE]")?;
    writeln!(code, "    final_norm_buf: wgpu::Buffer,")?;
    writeln!(code)?;
    writeln!(
        code,
        "    // ── Working buffers (re-used every forward pass) ──"
    )?;
    writeln!(code, "    hidden_buf:   wgpu::Buffer,")?;
    writeln!(code, "    residual_buf: wgpu::Buffer,")?;
    writeln!(code, "    logits_buf:   wgpu::Buffer,")?;
    writeln!(code)?;
    writeln!(code, "    // ── Model dimensions ──")?;
    writeln!(code, "    hidden_size:       u32,")?;
    writeln!(code, "    intermediate_size: u32,")?;
    writeln!(code, "    num_layers:        u32,")?;
    writeln!(code, "    num_heads:         u32,")?;
    writeln!(code, "    num_kv_heads:      u32,")?;
    writeln!(code, "    head_dim:          u32,")?;
    writeln!(code, "    vocab_size:        u32,")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    Ok(())
}

fn emit_gpu_model_impl(code: &mut String, config: &ModelConfig) -> Result<(), GpuCodegenError> {
    let hidden = config.hidden_size;
    let intermediate = config.intermediate_size;
    let _num_layers = config.num_layers;
    let vocab = config.vocab_size;

    writeln!(code, "impl GpuModel {{")?;

    // ── new() ──
    writeln!(
        code,
        "    /// Initialise the model: request a GPU adapter, upload weights,"
    )?;
    writeln!(code, "    /// and compile all compute pipelines.")?;
    writeln!(code, "    ///")?;
    writeln!(code, "    /// `weights` is the raw weight blob produced by")?;
    writeln!(code, "    /// `forge export-weights`.")?;
    writeln!(code, "    pub fn new(weights: &[u8]) -> Self {{")?;
    writeln!(
        code,
        "        let instance = wgpu::Instance::new(&wgpu::InstanceDescriptor {{"
    )?;
    writeln!(code, "            backends: wgpu::Backends::all(),")?;
    writeln!(code, "            ..Default::default()")?;
    writeln!(code, "        }});")?;
    writeln!(code)?;
    writeln!(
        code,
        "        let adapter = pollster::block_on(instance.request_adapter("
    )?;
    writeln!(code, "            &wgpu::RequestAdapterOptions {{")?;
    writeln!(
        code,
        "                power_preference: wgpu::PowerPreference::HighPerformance,"
    )?;
    writeln!(code, "                ..Default::default()")?;
    writeln!(code, "            }},")?;
    writeln!(code, "        ))")?;
    writeln!(code, "        .expect(\"no GPU adapter found\");")?;
    writeln!(code)?;
    writeln!(
        code,
        "        let (device, queue) = pollster::block_on(adapter.request_device("
    )?;
    writeln!(code, "            &wgpu::DeviceDescriptor {{")?;
    writeln!(code, "                label: Some(\"forge-gpu\"),")?;
    writeln!(code, "                ..Default::default()")?;
    writeln!(code, "            }},")?;
    writeln!(code, "            None,")?;
    writeln!(code, "        ))")?;
    writeln!(code, "        .expect(\"failed to create wgpu device\");")?;
    writeln!(code)?;

    // compile pipelines
    writeln!(code, "        // Compile compute pipelines")?;
    for (name, shader) in [
        ("matmul", "SHADER_MATMUL"),
        ("rms_norm", "SHADER_RMS_NORM"),
        ("rope", "SHADER_ROPE"),
        ("softmax", "SHADER_SOFTMAX"),
        ("silu_mul", "SHADER_SILU_MUL"),
    ] {
        let var = format!("{name}_pipeline");
        writeln!(
            code,
            "        let {var} = make_pipeline(&device, {shader}, \"{name}\");"
        )?;
    }
    writeln!(code)?;

    // weight upload helpers
    writeln!(code, "        // Decode and upload weights")?;
    writeln!(
        code,
        "        // Weight layout (byte offsets into the blob):"
    )?;
    writeln!(
        code,
        "        //   [embed]  VOCAB_SIZE * HIDDEN_SIZE * 4 bytes (f32)"
    )?;
    writeln!(
        code,
        "        //   [layers] NUM_LAYERS * 7 * {hidden} * ... f32"
    )?;
    writeln!(code, "        let f32_size = std::mem::size_of::<f32>();")?;
    writeln!(
        code,
        "        let embed_elems  = (VOCAB_SIZE * HIDDEN_SIZE) as usize;"
    )?;
    writeln!(code, "        let hidden_elems = HIDDEN_SIZE as usize;")?;
    writeln!(
        code,
        "        let inter_elems  = INTERMEDIATE_SIZE as usize;"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        let mut cursor = 0usize;  // byte cursor into `weights`"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        // Helper: read the next `n` f32s from the weight blob."
    )?;
    writeln!(
        code,
        "        // Returns a slice of bytes suitable for wgpu upload."
    )?;
    writeln!(
        code,
        "        let mut next_f32_bytes = |n: usize| -> &[u8] {{"
    )?;
    writeln!(code, "            let start = cursor;")?;
    writeln!(code, "            cursor += n * f32_size;")?;
    writeln!(
        code,
        "            if cursor <= weights.len() {{ &weights[start..cursor] }}"
    )?;
    writeln!(
        code,
        "            else {{ &weights[..0] }}  // out of range → empty"
    )?;
    writeln!(code, "        }};")?;
    writeln!(code)?;
    writeln!(
        code,
        "        let embed_buf = upload_buffer(&device, &queue, next_f32_bytes(embed_elems), \"embed\");"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        let mut weight_buffers: Vec<Vec<wgpu::Buffer>> = Vec::with_capacity(NUM_LAYERS as usize);"
    )?;
    writeln!(
        code,
        "        let mut norm_buffers:   Vec<Vec<wgpu::Buffer>> = Vec::with_capacity(NUM_LAYERS as usize);"
    )?;
    writeln!(code)?;
    writeln!(code, "        for layer in 0..NUM_LAYERS as usize {{")?;
    writeln!(code, "            // Attention projections: q, k, v, o")?;
    writeln!(
        code,
        "            let q  = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems * hidden_elems), &format!(\"layer{{layer}}.q\"));"
    )?;
    writeln!(
        code,
        "            let k  = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems * hidden_elems), &format!(\"layer{{layer}}.k\"));"
    )?;
    writeln!(
        code,
        "            let v  = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems * hidden_elems), &format!(\"layer{{layer}}.v\"));"
    )?;
    writeln!(
        code,
        "            let o  = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems * hidden_elems), &format!(\"layer{{layer}}.o\"));"
    )?;
    writeln!(code, "            // FFN projections: gate, up, down")?;
    writeln!(
        code,
        "            let gate = upload_buffer(&device, &queue, next_f32_bytes(inter_elems * hidden_elems), &format!(\"layer{{layer}}.gate\"));"
    )?;
    writeln!(
        code,
        "            let up   = upload_buffer(&device, &queue, next_f32_bytes(inter_elems * hidden_elems), &format!(\"layer{{layer}}.up\"));"
    )?;
    writeln!(
        code,
        "            let down = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems * inter_elems), &format!(\"layer{{layer}}.down\"));"
    )?;
    writeln!(
        code,
        "            weight_buffers.push(vec![q, k, v, o, gate, up, down]);"
    )?;
    writeln!(code)?;
    writeln!(code, "            // Norm weights")?;
    writeln!(
        code,
        "            let attn_norm = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems), &format!(\"layer{{layer}}.attn_norm\"));"
    )?;
    writeln!(
        code,
        "            let ffn_norm  = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems), &format!(\"layer{{layer}}.ffn_norm\"));"
    )?;
    writeln!(
        code,
        "            norm_buffers.push(vec![attn_norm, ffn_norm]);"
    )?;
    writeln!(code, "        }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "        let final_norm_buf = upload_buffer(&device, &queue, next_f32_bytes(hidden_elems), \"final_norm\");"
    )?;
    writeln!(code)?;

    // working buffers
    writeln!(code, "        // Allocate working buffers")?;
    writeln!(code, "        let buf_usage =")?;
    writeln!(
        code,
        "            wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST;"
    )?;
    let hidden_bytes = hidden * 4;
    let _inter_bytes = intermediate * 4;
    let vocab_bytes = vocab * 4;
    writeln!(
        code,
        "        let hidden_buf = device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"hidden\"),")?;
    writeln!(code, "            size:  {hidden_bytes},")?;
    writeln!(code, "            usage: buf_usage,")?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(
        code,
        "        let residual_buf = device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"residual\"),")?;
    writeln!(code, "            size:  {hidden_bytes},")?;
    writeln!(code, "            usage: buf_usage,")?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(
        code,
        "        let logits_buf = device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"logits\"),")?;
    writeln!(code, "            size:  {vocab_bytes},")?;
    writeln!(
        code,
        "            usage: buf_usage | wgpu::BufferUsages::MAP_READ,"
    )?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(code)?;

    writeln!(code, "        Self {{")?;
    writeln!(code, "            device,")?;
    writeln!(code, "            queue,")?;
    writeln!(code, "            matmul_pipeline,")?;
    writeln!(code, "            rms_norm_pipeline,")?;
    writeln!(code, "            rope_pipeline,")?;
    writeln!(code, "            softmax_pipeline,")?;
    writeln!(code, "            silu_mul_pipeline,")?;
    writeln!(code, "            embed_buf,")?;
    writeln!(code, "            weight_buffers,")?;
    writeln!(code, "            norm_buffers,")?;
    writeln!(code, "            final_norm_buf,")?;
    writeln!(code, "            hidden_buf,")?;
    writeln!(code, "            residual_buf,")?;
    writeln!(code, "            logits_buf,")?;
    writeln!(code, "            hidden_size: HIDDEN_SIZE,")?;
    writeln!(code, "            intermediate_size: INTERMEDIATE_SIZE,")?;
    writeln!(code, "            num_layers: NUM_LAYERS,")?;
    writeln!(code, "            num_heads: NUM_HEADS,")?;
    writeln!(code, "            num_kv_heads: NUM_KV_HEADS,")?;
    writeln!(code, "            head_dim: HEAD_DIM,")?;
    writeln!(code, "            vocab_size: VOCAB_SIZE,")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;

    // ── forward() ──
    writeln!(code, "    /// Run the forward pass for a single token.")?;
    writeln!(code, "    ///")?;
    writeln!(
        code,
        "    /// Returns logits over the vocabulary as a flat `Vec<f32>`."
    )?;
    writeln!(
        code,
        "    pub fn forward(&mut self, token_id: u32, pos: u32) -> Vec<f32> {{"
    )?;
    writeln!(
        code,
        "        // 1. Embedding lookup — copy row `token_id` from embed_buf → hidden_buf"
    )?;
    writeln!(code, "        {{")?;
    writeln!(
        code,
        "            let src_offset = (token_id * self.hidden_size) as u64 * 4;"
    )?;
    writeln!(
        code,
        "            let byte_len   = self.hidden_size as u64 * 4;"
    )?;
    writeln!(
        code,
        "            let mut enc = self.device.create_command_encoder("
    )?;
    writeln!(
        code,
        "                &wgpu::CommandEncoderDescriptor {{ label: Some(\"embed_copy\") }},"
    )?;
    writeln!(code, "            );")?;
    writeln!(code, "            enc.copy_buffer_to_buffer(")?;
    writeln!(code, "                &self.embed_buf, src_offset,")?;
    writeln!(code, "                &self.hidden_buf, 0,")?;
    writeln!(code, "                byte_len,")?;
    writeln!(code, "            );")?;
    writeln!(
        code,
        "            enc.copy_buffer_to_buffer(&self.hidden_buf, 0, &self.residual_buf, 0, byte_len);"
    )?;
    writeln!(code, "            self.queue.submit(Some(enc.finish()));")?;
    writeln!(code, "        }}")?;
    writeln!(code)?;
    writeln!(code, "        // 2. Transformer layers")?;
    writeln!(code, "        for layer in 0..self.num_layers as usize {{")?;
    writeln!(code, "            // RMS norm (attention)")?;
    writeln!(
        code,
        "            self.dispatch_rms_norm(&self.residual_buf.slice(..), &self.norm_buffers[layer][0], &self.hidden_buf);"
    )?;
    writeln!(code)?;
    writeln!(code, "            // Q, K, V projections (matmul)")?;
    writeln!(
        code,
        "            let q_buf = self.dispatch_matmul_alloc(&self.hidden_buf, &self.weight_buffers[layer][0], self.hidden_size, self.hidden_size);"
    )?;
    writeln!(
        code,
        "            let k_buf = self.dispatch_matmul_alloc(&self.hidden_buf, &self.weight_buffers[layer][1], self.hidden_size, self.hidden_size);"
    )?;
    writeln!(
        code,
        "            let v_buf = self.dispatch_matmul_alloc(&self.hidden_buf, &self.weight_buffers[layer][2], self.hidden_size, self.hidden_size);"
    )?;
    writeln!(code)?;
    writeln!(code, "            // RoPE on Q and K")?;
    writeln!(
        code,
        "            self.dispatch_rope(&q_buf, self.num_heads, self.head_dim, pos);"
    )?;
    writeln!(
        code,
        "            self.dispatch_rope(&k_buf, self.num_kv_heads, self.head_dim, pos);"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "            // Attention (simplified: Q·Kᵀ softmax V)"
    )?;
    writeln!(
        code,
        "            let attn_out = self.dispatch_attention(&q_buf, &k_buf, &v_buf);"
    )?;
    writeln!(code)?;
    writeln!(code, "            // Output projection + residual")?;
    writeln!(
        code,
        "            let o_proj = self.dispatch_matmul_alloc(&attn_out, &self.weight_buffers[layer][3], self.hidden_size, self.hidden_size);"
    )?;
    writeln!(
        code,
        "            self.accumulate_residual(&self.residual_buf, &o_proj);"
    )?;
    writeln!(code)?;
    writeln!(code, "            // RMS norm (FFN)")?;
    writeln!(
        code,
        "            self.dispatch_rms_norm(&self.residual_buf.slice(..), &self.norm_buffers[layer][1], &self.hidden_buf);"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "            // FFN: gate + up projections, SiLU-mul, down"
    )?;
    writeln!(
        code,
        "            let gate_buf = self.dispatch_matmul_alloc(&self.hidden_buf, &self.weight_buffers[layer][4], self.intermediate_size, self.hidden_size);"
    )?;
    writeln!(
        code,
        "            let up_buf   = self.dispatch_matmul_alloc(&self.hidden_buf, &self.weight_buffers[layer][5], self.intermediate_size, self.hidden_size);"
    )?;
    writeln!(
        code,
        "            let ffn_mid  = self.dispatch_silu_mul(&gate_buf, &up_buf, self.intermediate_size);"
    )?;
    writeln!(
        code,
        "            let down_out = self.dispatch_matmul_alloc(&ffn_mid, &self.weight_buffers[layer][6], self.hidden_size, self.intermediate_size);"
    )?;
    writeln!(
        code,
        "            self.accumulate_residual(&self.residual_buf, &down_out);"
    )?;
    writeln!(code, "        }}")?;
    writeln!(code)?;
    writeln!(code, "        // 3. Final RMS norm")?;
    writeln!(
        code,
        "        self.dispatch_rms_norm(&self.residual_buf.slice(..), &self.final_norm_buf, &self.hidden_buf);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // 4. Logits projection (hidden → vocab)")?;
    writeln!(code, "        {{")?;
    writeln!(
        code,
        "            let dims_data: [u32; 2] = [self.vocab_size, self.hidden_size];"
    )?;
    writeln!(
        code,
        "            let dims_bytes = bytemuck_cast_slice(&dims_data);"
    )?;
    writeln!(
        code,
        "            let dims_buf = upload_uniform(&self.device, &self.queue, dims_bytes, \"logits_dims\");"
    )?;
    writeln!(
        code,
        "            let bg = make_bind_group(&self.device, &self.matmul_pipeline, &["
    )?;
    writeln!(code, "                &self.embed_buf,  // tied weights")?;
    writeln!(code, "                &self.hidden_buf,")?;
    writeln!(code, "                &self.logits_buf,")?;
    writeln!(code, "                &dims_buf,")?;
    writeln!(code, "            ]);")?;
    writeln!(
        code,
        "            dispatch(&self.device, &self.queue, &self.matmul_pipeline, &bg, self.vocab_size.div_ceil(64));"
    )?;
    writeln!(code, "        }}")?;
    writeln!(code)?;
    writeln!(code, "        // 5. Read back logits")?;
    writeln!(code, "        read_buffer_f32(&self.device, &self.queue, &self.logits_buf, self.vocab_size as usize)")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;

    // helper dispatch methods
    writeln!(
        code,
        "    // ── Private dispatch helpers ───────────────────────"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn dispatch_rms_norm(&self, _input: &wgpu::BufferSlice, _weight: &wgpu::Buffer, _output: &wgpu::Buffer) {{"
    )?;
    writeln!(
        code,
        "        // Simplified: a real implementation would build a bind group and submit."
    )?;
    writeln!(
        code,
        "        let dims_data: [u32; 2] = [self.hidden_size, 0];"
    )?;
    writeln!(
        code,
        "        let _dims_buf = upload_uniform(&self.device, &self.queue, bytemuck_cast_slice(&dims_data), \"rms_dims\");"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn dispatch_matmul_alloc(&self, input: &wgpu::Buffer, weight: &wgpu::Buffer, rows: u32, cols: u32) -> wgpu::Buffer {{"
    )?;
    writeln!(
        code,
        "        let out_buf = self.device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"matmul_out\"),")?;
    writeln!(code, "            size: (rows as u64) * 4,")?;
    writeln!(
        code,
        "            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,"
    )?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(code, "        let dims_data: [u32; 2] = [rows, cols];")?;
    writeln!(
        code,
        "        let dims_buf = upload_uniform(&self.device, &self.queue, bytemuck_cast_slice(&dims_data), \"matmul_dims\");"
    )?;
    writeln!(
        code,
        "        let bg = make_bind_group(&self.device, &self.matmul_pipeline, &[weight, input, &out_buf, &dims_buf]);"
    )?;
    writeln!(
        code,
        "        dispatch(&self.device, &self.queue, &self.matmul_pipeline, &bg, rows.div_ceil(64));"
    )?;
    writeln!(code, "        out_buf")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn dispatch_rope(&self, buf: &wgpu::Buffer, num_heads: u32, head_dim: u32, pos: u32) {{"
    )?;
    writeln!(
        code,
        "        let dims_data: [u32; 4] = [num_heads, head_dim, pos, 0];"
    )?;
    writeln!(
        code,
        "        let dims_buf = upload_uniform(&self.device, &self.queue, bytemuck_cast_slice(&dims_data), \"rope_dims\");"
    )?;
    writeln!(
        code,
        "        let bg = make_bind_group(&self.device, &self.rope_pipeline, &[buf, &dims_buf]);"
    )?;
    writeln!(
        code,
        "        dispatch(&self.device, &self.queue, &self.rope_pipeline, &bg, num_heads.div_ceil(64));"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn dispatch_attention(&self, q: &wgpu::Buffer, _k: &wgpu::Buffer, _v: &wgpu::Buffer) -> wgpu::Buffer {{"
    )?;
    writeln!(
        code,
        "        // Simplified single-token attention: returns a copy of q."
    )?;
    writeln!(
        code,
        "        let out_buf = self.device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"attn_out\"),")?;
    writeln!(code, "            size: self.hidden_size as u64 * 4,")?;
    writeln!(
        code,
        "            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,"
    )?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(
        code,
        "        let mut enc = self.device.create_command_encoder("
    )?;
    writeln!(
        code,
        "            &wgpu::CommandEncoderDescriptor {{ label: Some(\"attn_copy\") }},"
    )?;
    writeln!(code, "        );")?;
    writeln!(
        code,
        "        enc.copy_buffer_to_buffer(q, 0, &out_buf, 0, self.hidden_size as u64 * 4);"
    )?;
    writeln!(code, "        self.queue.submit(Some(enc.finish()));")?;
    writeln!(code, "        out_buf")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn dispatch_silu_mul(&self, gate: &wgpu::Buffer, up: &wgpu::Buffer, n: u32) -> wgpu::Buffer {{"
    )?;
    writeln!(
        code,
        "        let out_buf = self.device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "            label: Some(\"silu_out\"),")?;
    writeln!(code, "            size: n as u64 * 4,")?;
    writeln!(
        code,
        "            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC | wgpu::BufferUsages::COPY_DST,"
    )?;
    writeln!(code, "            mapped_at_creation: false,")?;
    writeln!(code, "        }});")?;
    writeln!(code, "        let dims_data: [u32; 2] = [n, 0];")?;
    writeln!(
        code,
        "        let dims_buf = upload_uniform(&self.device, &self.queue, bytemuck_cast_slice(&dims_data), \"silu_dims\");"
    )?;
    writeln!(
        code,
        "        let bg = make_bind_group(&self.device, &self.silu_mul_pipeline, &[gate, up, &out_buf, &dims_buf]);"
    )?;
    writeln!(
        code,
        "        dispatch(&self.device, &self.queue, &self.silu_mul_pipeline, &bg, n.div_ceil(64));"
    )?;
    writeln!(code, "        out_buf")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    fn accumulate_residual(&self, residual: &wgpu::Buffer, delta: &wgpu::Buffer) {{"
    )?;
    writeln!(
        code,
        "        // In a full implementation this would use a GPU add kernel."
    )?;
    writeln!(
        code,
        "        // For now we just copy delta → residual as a placeholder."
    )?;
    writeln!(
        code,
        "        let mut enc = self.device.create_command_encoder("
    )?;
    writeln!(
        code,
        "            &wgpu::CommandEncoderDescriptor {{ label: Some(\"residual_add\") }},"
    )?;
    writeln!(code, "        );")?;
    writeln!(
        code,
        "        enc.copy_buffer_to_buffer(delta, 0, residual, 0, self.hidden_size as u64 * 4);"
    )?;
    writeln!(code, "        self.queue.submit(Some(enc.finish()));")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // ── Free functions ──
    emit_gpu_free_functions(code)?;

    Ok(())
}

fn emit_gpu_free_functions(code: &mut String) -> Result<(), GpuCodegenError> {
    writeln!(
        code,
        "// ── Utilities ─────────────────────────────────────────"
    )?;
    writeln!(code)?;

    // make_pipeline
    writeln!(
        code,
        "fn make_pipeline(device: &wgpu::Device, wgsl: &str, label: &str) -> wgpu::ComputePipeline {{"
    )?;
    writeln!(
        code,
        "    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {{"
    )?;
    writeln!(code, "        label: Some(label),")?;
    writeln!(
        code,
        "        source: wgpu::ShaderSource::Wgsl(wgsl.into()),"
    )?;
    writeln!(code, "    }});")?;
    writeln!(
        code,
        "    device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {{"
    )?;
    writeln!(code, "        label: Some(label),")?;
    writeln!(code, "        layout: None,")?;
    writeln!(code, "        module: &module,")?;
    writeln!(code, "        entry_point: Some(\"main\"),")?;
    writeln!(
        code,
        "        compilation_options: wgpu::PipelineCompilationOptions::default(),"
    )?;
    writeln!(code, "        cache: None,")?;
    writeln!(code, "    }})")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // upload_buffer
    writeln!(
        code,
        "fn upload_buffer(device: &wgpu::Device, queue: &wgpu::Queue, data: &[u8], label: &str) -> wgpu::Buffer {{"
    )?;
    writeln!(code, "    use wgpu::util::DeviceExt as _;")?;
    writeln!(
        code,
        "    device.create_buffer_init(&wgpu::util::BufferInitDescriptor {{"
    )?;
    writeln!(code, "        label: Some(label),")?;
    writeln!(code, "        contents: data,")?;
    writeln!(
        code,
        "        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,"
    )?;
    writeln!(code, "    }})")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // upload_uniform
    writeln!(
        code,
        "fn upload_uniform(device: &wgpu::Device, queue: &wgpu::Queue, data: &[u8], label: &str) -> wgpu::Buffer {{"
    )?;
    writeln!(code, "    use wgpu::util::DeviceExt as _;")?;
    writeln!(
        code,
        "    device.create_buffer_init(&wgpu::util::BufferInitDescriptor {{"
    )?;
    writeln!(code, "        label: Some(label),")?;
    writeln!(code, "        contents: data,")?;
    writeln!(
        code,
        "        usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,"
    )?;
    writeln!(code, "    }})")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // make_bind_group
    writeln!(
        code,
        "fn make_bind_group(device: &wgpu::Device, pipeline: &wgpu::ComputePipeline, buffers: &[&wgpu::Buffer]) -> wgpu::BindGroup {{"
    )?;
    writeln!(code, "    let layout = pipeline.get_bind_group_layout(0);")?;
    writeln!(
        code,
        "    let entries: Vec<wgpu::BindGroupEntry<'_>> = buffers"
    )?;
    writeln!(code, "        .iter()")?;
    writeln!(code, "        .enumerate()")?;
    writeln!(code, "        .map(|(i, buf)| wgpu::BindGroupEntry {{")?;
    writeln!(code, "            binding: i as u32,")?;
    writeln!(code, "            resource: buf.as_entire_binding(),")?;
    writeln!(code, "        }})")?;
    writeln!(code, "        .collect();")?;
    writeln!(
        code,
        "    device.create_bind_group(&wgpu::BindGroupDescriptor {{"
    )?;
    writeln!(code, "        label: None,")?;
    writeln!(code, "        layout: &layout,")?;
    writeln!(code, "        entries: &entries,")?;
    writeln!(code, "    }})")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // dispatch
    writeln!(
        code,
        "fn dispatch(device: &wgpu::Device, queue: &wgpu::Queue, pipeline: &wgpu::ComputePipeline, bg: &wgpu::BindGroup, workgroups: u32) {{"
    )?;
    writeln!(
        code,
        "    let mut enc = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {{ label: None }});"
    )?;
    writeln!(code, "    {{")?;
    writeln!(
        code,
        "        let mut pass = enc.begin_compute_pass(&wgpu::ComputePassDescriptor {{"
    )?;
    writeln!(code, "            label: None,")?;
    writeln!(code, "            timestamp_writes: None,")?;
    writeln!(code, "        }});")?;
    writeln!(code, "        pass.set_pipeline(pipeline);")?;
    writeln!(code, "        pass.set_bind_group(0, bg, &[]);")?;
    writeln!(code, "        pass.dispatch_workgroups(workgroups, 1, 1);")?;
    writeln!(code, "    }}")?;
    writeln!(code, "    queue.submit(Some(enc.finish()));")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // read_buffer_f32
    writeln!(
        code,
        "fn read_buffer_f32(device: &wgpu::Device, queue: &wgpu::Queue, buf: &wgpu::Buffer, n: usize) -> Vec<f32> {{"
    )?;
    writeln!(
        code,
        "    let staging = device.create_buffer(&wgpu::BufferDescriptor {{"
    )?;
    writeln!(code, "        label: Some(\"staging\"),")?;
    writeln!(code, "        size: (n as u64) * 4,")?;
    writeln!(
        code,
        "        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,"
    )?;
    writeln!(code, "        mapped_at_creation: false,")?;
    writeln!(code, "    }});")?;
    writeln!(code, "    let mut enc = device.create_command_encoder(")?;
    writeln!(
        code,
        "        &wgpu::CommandEncoderDescriptor {{ label: Some(\"readback\") }},"
    )?;
    writeln!(code, "    );")?;
    writeln!(
        code,
        "    enc.copy_buffer_to_buffer(buf, 0, &staging, 0, (n as u64) * 4);"
    )?;
    writeln!(code, "    queue.submit(Some(enc.finish()));")?;
    writeln!(code, "    let slice = staging.slice(..);")?;
    writeln!(code, "    slice.map_async(wgpu::MapMode::Read, |_| {{}});")?;
    writeln!(code, "    device.poll(wgpu::Maintain::Wait);")?;
    writeln!(code, "    let data = slice.get_mapped_range();")?;
    writeln!(code, "    let result: Vec<f32> = data")?;
    writeln!(code, "        .chunks_exact(4)")?;
    writeln!(
        code,
        "        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))"
    )?;
    writeln!(code, "        .collect();")?;
    writeln!(code, "    drop(data);")?;
    writeln!(code, "    staging.unmap();")?;
    writeln!(code, "    result")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // bytemuck_cast_slice — avoids a bytemuck dependency
    writeln!(
        code,
        "/// Reinterpret a `&[u32]` as `&[u8]` without the bytemuck crate."
    )?;
    writeln!(code, "fn bytemuck_cast_slice(data: &[u32]) -> &[u8] {{")?;
    writeln!(
        code,
        "    // SAFETY: u32 and u8 have compatible alignment; the slice length stays in bounds."
    )?;
    writeln!(
        code,
        "    unsafe {{ std::slice::from_raw_parts(data.as_ptr().cast::<u8>(), data.len() * 4) }}"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // suppress unused warning for queue in upload helpers
    writeln!(
        code,
        "// suppress unused-variable warning in upload helpers"
    )?;
    writeln!(code, "#[allow(unused_variables)]")?;
    writeln!(code, "fn _use_queue(_q: &wgpu::Queue) {{}}")?;
    writeln!(code)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// main.rs generation
// ---------------------------------------------------------------------------

fn generate_main_rs(model_name: &str, config: &ModelConfig) -> Result<String, GpuCodegenError> {
    let sanitized = sanitize_name(model_name);
    let vocab = config.vocab_size;
    let mut code = String::with_capacity(4 * 1024);
    writeln!(
        code,
        "//! Auto-generated GPU inference binary for `{model_name}`."
    )?;
    writeln!(code, "//!")?;
    writeln!(
        code,
        "//! Usage:  {sanitized} <weights.bin> <tokenizer.json> [prompt]"
    )?;
    writeln!(code)?;
    writeln!(code, "mod model;")?;
    writeln!(code, "use model::GpuModel;")?;
    writeln!(code)?;
    writeln!(code, "fn main() {{")?;
    writeln!(
        code,
        "    let args: Vec<String> = std::env::args().collect();"
    )?;
    writeln!(code, "    if args.len() < 3 {{")?;
    writeln!(
        code,
        "        eprintln!(\"Usage: {{}} <weights.bin> <tokenizer.json> [prompt]\", args[0]);"
    )?;
    writeln!(code, "        std::process::exit(1);")?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(
        code,
        "    let weights = std::fs::read(&args[1]).expect(\"failed to read weights\");"
    )?;
    writeln!(code, "    let tokenizer_path = &args[2];")?;
    writeln!(
        code,
        "    let prompt = if args.len() > 3 {{ args[3].clone() }} else {{ \"Hello, world!\".to_string() }};"
    )?;
    writeln!(code)?;
    writeln!(code, "    println!(\"Initialising GPU model...\");")?;
    writeln!(code, "    let mut model = GpuModel::new(&weights);")?;
    writeln!(code)?;
    writeln!(code, "    // Load tokenizer and encode prompt")?;
    writeln!(
        code,
        "    let tokenizer = tokenizers::Tokenizer::from_file(tokenizer_path)"
    )?;
    writeln!(code, "        .expect(\"failed to load tokenizer\");")?;
    writeln!(
        code,
        "    let encoding = tokenizer.encode(prompt.as_str(), false).expect(\"tokenizer encode failed\");"
    )?;
    writeln!(
        code,
        "    let token_ids: Vec<u32> = encoding.get_ids().to_vec();"
    )?;
    writeln!(code)?;
    writeln!(code, "    println!(\"Prompt: {{prompt}}\");")?;
    writeln!(code, "    println!(\"Tokens: {{:?}}\", token_ids);")?;
    writeln!(code)?;
    writeln!(code, "    // Run forward pass for each token")?;
    writeln!(code, "    let mut last_logits = vec![0.0f32; {vocab}];")?;
    writeln!(
        code,
        "    for (pos, &token_id) in token_ids.iter().enumerate() {{"
    )?;
    writeln!(
        code,
        "        last_logits = model.forward(token_id, pos as u32);"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;
    writeln!(code, "    // Greedy decode: pick argmax of logits")?;
    writeln!(code, "    let next_token = last_logits")?;
    writeln!(code, "        .iter()")?;
    writeln!(code, "        .enumerate()")?;
    writeln!(
        code,
        "        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())"
    )?;
    writeln!(code, "        .map(|(i, _)| i as u32)")?;
    writeln!(code, "        .unwrap_or(0);")?;
    writeln!(code)?;
    writeln!(code, "    let decoded = tokenizer")?;
    writeln!(code, "        .decode(&[next_token], true)")?;
    writeln!(
        code,
        "        .unwrap_or_else(|_| \"[decode error]\".to_string());"
    )?;
    writeln!(
        code,
        "    println!(\"Next token: {{next_token}} → \\\"{{decoded}}\\\"\");"
    )?;
    writeln!(code, "}}")?;

    Ok(code)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::ir::{Architecture, DType, ModelConfig};

    fn minimal_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 4,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 512,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F32,
            sliding_window_size: None,
            qkv_bias: false,
            hidden_activation: HiddenActivation::SiLU,
        }
    }

    fn minimal_graph() -> Graph {
        Graph::new("test-gpu").with_config(minimal_config())
    }

    #[test]
    fn generate_gpu_project_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let graph = minimal_graph();
        generate_gpu_project(&graph, dir.path(), "test-model").unwrap();

        assert!(
            dir.path().join("Cargo.toml").exists(),
            "Cargo.toml should be created"
        );
        assert!(
            dir.path().join("src/model.rs").exists(),
            "src/model.rs should be created"
        );
        assert!(
            dir.path().join("src/main.rs").exists(),
            "src/main.rs should be created"
        );
    }

    #[test]
    fn generated_cargo_toml_has_wgpu_dep() {
        let toml = generate_cargo_toml("my-model");
        assert!(toml.contains("wgpu"), "Cargo.toml should depend on wgpu");
        assert!(
            toml.contains("pollster"),
            "Cargo.toml should depend on pollster"
        );
        assert!(
            toml.contains("tokenizers"),
            "Cargo.toml should depend on tokenizers"
        );
    }

    #[test]
    fn generated_model_rs_contains_wgsl() {
        let config = minimal_config();
        let model_rs = generate_model_rs(&config).unwrap();

        assert!(
            model_rs.contains("SHADER_MATMUL"),
            "model.rs should define SHADER_MATMUL"
        );
        assert!(
            model_rs.contains("SHADER_RMS_NORM"),
            "model.rs should define SHADER_RMS_NORM"
        );
        assert!(
            model_rs.contains("SHADER_ROPE"),
            "model.rs should define SHADER_ROPE"
        );
        assert!(
            model_rs.contains("SHADER_SOFTMAX"),
            "model.rs should define SHADER_SOFTMAX"
        );
        assert!(
            model_rs.contains("SHADER_SILU_MUL"),
            "model.rs should define SHADER_SILU_MUL"
        );
        assert!(
            model_rs.contains("@compute @workgroup_size"),
            "model.rs should contain WGSL compute annotation"
        );
        assert!(
            model_rs.contains("var<storage"),
            "model.rs should contain WGSL storage binding"
        );
    }

    #[test]
    fn generated_model_rs_has_gpu_model_struct() {
        let config = minimal_config();
        let model_rs = generate_model_rs(&config).unwrap();

        assert!(
            model_rs.contains("pub struct GpuModel"),
            "model.rs should define GpuModel struct"
        );
        assert!(
            model_rs.contains("matmul_pipeline"),
            "GpuModel should have matmul_pipeline field"
        );
        assert!(
            model_rs.contains("weight_buffers"),
            "GpuModel should have weight_buffers field"
        );
        assert!(
            model_rs.contains("fn new(weights: &[u8])"),
            "GpuModel should implement new()"
        );
        assert!(
            model_rs.contains("fn forward(&mut self, token_id: u32, pos: u32)"),
            "GpuModel should implement forward()"
        );
    }

    #[test]
    fn generated_main_rs_has_tokenizer_usage() {
        let config = minimal_config();
        let main_rs = generate_main_rs("test-model", &config).unwrap();

        assert!(
            main_rs.contains("tokenizers::Tokenizer"),
            "main.rs should use tokenizers crate"
        );
        assert!(
            main_rs.contains("GpuModel::new"),
            "main.rs should call GpuModel::new"
        );
        assert!(
            main_rs.contains("model.forward"),
            "main.rs should call model.forward"
        );
    }

    #[test]
    fn missing_config_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let graph = Graph::new("no-config");
        let result = generate_gpu_project(&graph, dir.path(), "fail");
        assert!(
            matches!(result, Err(GpuCodegenError::MissingConfig)),
            "should fail with MissingConfig when graph has no config"
        );
    }

    #[test]
    fn model_constants_match_config() {
        let config = minimal_config();
        let model_rs = generate_model_rs(&config).unwrap();

        assert!(model_rs.contains("pub const HIDDEN_SIZE: u32 = 64;"));
        assert!(model_rs.contains("pub const NUM_LAYERS: u32 = 2;"));
        assert!(model_rs.contains("pub const VOCAB_SIZE: u32 = 256;"));
    }

    #[test]
    fn sanitize_name_replaces_special_chars() {
        assert_eq!(sanitize_name("my_model.v2"), "my-model-v2");
        assert_eq!(sanitize_name("Llama-3B"), "llama-3b");
        assert_eq!(sanitize_name("test model"), "test-model");
    }
}
