//! Rust source code emission from IR graphs.
//!
//! Generates a complete Rust module containing:
//! - Typed buffer declarations for all intermediate tensors
//! - Specialized kernel functions for each operation
//! - A `forward()` function that chains all operations
//!
//! The generated code operates on flat f32 slices — no dynamic shapes.

use std::fmt::Write;

use forgellm_frontend::ir::*;

/// Generate Rust source code from a computation graph.
///
/// Returns a string containing a complete Rust module that implements
/// the model's forward pass. The generated code:
/// - Uses `&[f32]` for weight inputs (pre-loaded)
/// - Uses flat arrays for all intermediate buffers
/// - Has zero allocations during the forward pass
pub fn generate(graph: &Graph) -> Result<String, CodegenError> {
    let config = graph.config.as_ref().ok_or(CodegenError::MissingConfig)?;

    let mut code = String::with_capacity(32 * 1024);

    emit_header(&mut code, config)?;
    emit_kernel_functions(&mut code)?;
    emit_specialized_matmul_functions(&mut code, config)?;
    emit_forward_function(&mut code, graph, config)?;

    Ok(code)
}

/// Errors during code generation.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("graph has no model config")]
    MissingConfig,

    #[error("unsupported operation for CPU codegen: {0}")]
    UnsupportedOp(String),

    #[error("format error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

fn emit_header(code: &mut String, config: &ModelConfig) -> Result<(), CodegenError> {
    writeln!(code, "//! Auto-generated by ForgeLLM CPU codegen.")?;
    writeln!(
        code,
        "//! Model: {} ({} layers, hidden={})",
        config.architecture, config.num_layers, config.hidden_size
    )?;
    writeln!(code, "//!")?;
    writeln!(
        code,
        "//! This code has no dynamic dispatch — all dimensions are baked in."
    )?;
    writeln!(code)?;
    writeln!(code, "#![allow(clippy::excessive_precision)]")?;
    writeln!(code, "#![allow(dead_code, unused_imports, unused_assignments)]")?;
    writeln!(code)?;
    writeln!(code, "use rayon::prelude::*;")?;
    writeln!(code)?;
    writeln!(code, "// Model constants")?;
    writeln!(
        code,
        "pub const HIDDEN_SIZE: usize = {};",
        config.hidden_size
    )?;
    writeln!(
        code,
        "pub const INTERMEDIATE_SIZE: usize = {};",
        config.intermediate_size
    )?;
    writeln!(code, "pub const NUM_LAYERS: usize = {};", config.num_layers)?;
    writeln!(
        code,
        "pub const NUM_HEADS: usize = {};",
        config.num_attention_heads
    )?;
    writeln!(
        code,
        "pub const NUM_KV_HEADS: usize = {};",
        config.num_kv_heads
    )?;
    writeln!(code, "pub const HEAD_DIM: usize = {};", config.head_dim)?;
    writeln!(code, "pub const VOCAB_SIZE: usize = {};", config.vocab_size)?;
    // Cap MAX_SEQ_LEN at 4096 for reasonable KV cache memory.
    // Models like Qwen2.5 have max_seq_len=32768 which would allocate
    // gigabytes of KV cache pre-allocated on construction.
    let effective_seq_len = config.max_seq_len.min(4096);
    writeln!(
        code,
        "pub const MAX_SEQ_LEN: usize = {};  // capped from model's {}",
        effective_seq_len, config.max_seq_len
    )?;
    writeln!(
        code,
        "pub const RMS_NORM_EPS: f32 = {:e};",
        config.rms_norm_eps
    )?;
    writeln!(code, "pub const ROPE_THETA: f32 = {:e};", config.rope_theta)?;
    writeln!(code)?;

    // Aligned buffer type for SIMD-friendly memory access
    writeln!(code, "/// Cache-line aligned buffer for optimal SIMD performance.")?;
    writeln!(code, "#[repr(C, align(64))]")?;
    writeln!(code, "pub struct AlignedBuf<const N: usize>(pub [f32; N]);")?;
    writeln!(code)?;
    writeln!(code, "impl<const N: usize> AlignedBuf<N> {{")?;
    writeln!(code, "    pub fn new() -> Self {{ Self([0.0f32; N]) }}")?;
    writeln!(code, "    pub fn as_slice(&self) -> &[f32] {{ &self.0 }}")?;
    writeln!(code, "    pub fn as_mut_slice(&mut self) -> &mut [f32] {{ &mut self.0 }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    Ok(())
}

fn emit_kernel_functions(code: &mut String) -> Result<(), CodegenError> {
    // Emit all kernels as a template string — includes NEON SIMD with scalar fallback
    code.push_str(
        r#"
// --- NEON SIMD dot product (4 accumulators, 16-element unrolled) ---
#[cfg(target_arch = "aarch64")]
#[inline]
fn dot_f32(a: &[f32], b: &[f32], len: usize) -> f32 {
    use std::arch::aarch64::*;
    unsafe {
        let mut s0 = vdupq_n_f32(0.0);
        let mut s1 = vdupq_n_f32(0.0);
        let mut s2 = vdupq_n_f32(0.0);
        let mut s3 = vdupq_n_f32(0.0);
        let chunks = len / 16;
        for i in 0..chunks {
            let base = i * 16;
            s0 = vfmaq_f32(s0, vld1q_f32(a.as_ptr().add(base)), vld1q_f32(b.as_ptr().add(base)));
            s1 = vfmaq_f32(s1, vld1q_f32(a.as_ptr().add(base+4)), vld1q_f32(b.as_ptr().add(base+4)));
            s2 = vfmaq_f32(s2, vld1q_f32(a.as_ptr().add(base+8)), vld1q_f32(b.as_ptr().add(base+8)));
            s3 = vfmaq_f32(s3, vld1q_f32(a.as_ptr().add(base+12)), vld1q_f32(b.as_ptr().add(base+12)));
        }
        s0 = vaddq_f32(s0, s1);
        s2 = vaddq_f32(s2, s3);
        s0 = vaddq_f32(s0, s2);
        let mut r = vaddvq_f32(s0);
        for i in (chunks*16)..len { r += *a.get_unchecked(i) * *b.get_unchecked(i); }
        r
    }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
fn dot_f32(a: &[f32], b: &[f32], len: usize) -> f32 {
    let mut sum = 0.0f32;
    for i in 0..len { sum += a[i] * b[i]; }
    sum
}

/// RMS normalization with NEON dot product + NEON apply
#[cfg(target_arch = "aarch64")]
#[inline]
pub fn rms_norm(output: &mut [f32], input: &[f32], weight: &[f32], eps: f32) {
    use std::arch::aarch64::*;
    let n = input.len();
    let sum_sq = dot_f32(input, input, n);
    let inv_rms = 1.0 / (sum_sq / n as f32 + eps).sqrt();
    unsafe {
        let vinv = vdupq_n_f32(inv_rms);
        let chunks = n / 4;
        for i in 0..chunks {
            let base = i * 4;
            let vi = vld1q_f32(input.as_ptr().add(base));
            let vw = vld1q_f32(weight.as_ptr().add(base));
            vst1q_f32(output.as_mut_ptr().add(base), vmulq_f32(vmulq_f32(vi, vinv), vw));
        }
    }
    for i in (n / 4 * 4)..n { output[i] = input[i] * inv_rms * weight[i]; }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
pub fn rms_norm(output: &mut [f32], input: &[f32], weight: &[f32], eps: f32) {
    let n = input.len();
    let sum_sq = dot_f32(input, input, n);
    let inv_rms = 1.0 / (sum_sq / n as f32 + eps).sqrt();
    for i in 0..n { output[i] = input[i] * inv_rms * weight[i]; }
}

/// Matrix multiply with NEON dot product per output element
#[inline]
pub fn matmul(output: &mut [f32], input: &[f32], weight: &[f32], m: usize, k: usize, n: usize) {
    for i in 0..m {
        let row = &input[i*k..(i+1)*k];
        for j in 0..n {
            output[i*n+j] = dot_f32(row, &weight[j*k..(j+1)*k], k);
        }
    }
}

"#,
    );

    // Remaining kernels as template string
    code.push_str(
        r#"#[inline]
pub fn silu(output: &mut [f32], input: &[f32]) {
    for (o, &x) in output.iter_mut().zip(input.iter()) { *o = x / (1.0 + (-x).exp()); }
}

/// GeLU activation (approximate): x * 0.5 * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
#[inline]
pub fn gelu(output: &mut [f32], input: &[f32]) {
    const SQRT_2_OVER_PI: f32 = 0.7978845608;
    for (o, &x) in output.iter_mut().zip(input.iter()) {
        let cdf = 0.5 * (1.0 + (SQRT_2_OVER_PI * (x + 0.044715 * x * x * x)).tanh());
        *o = x * cdf;
    }
}

/// Fused GeLU activation + elementwise multiply: output[i] = gelu(gate[i]) * up[i]
#[inline]
pub fn gelu_mul(output: &mut [f32], gate: &[f32], up: &[f32]) {
    const SQRT_2_OVER_PI: f32 = 0.7978845608;
    for i in 0..gate.len() {
        let x = gate[i];
        let cdf = 0.5 * (1.0 + (SQRT_2_OVER_PI * (x + 0.044715 * x * x * x)).tanh());
        output[i] = (x * cdf) * up[i];
    }
}

/// Fused SiLU activation + elementwise multiply: output[i] = silu(gate[i]) * up[i]
/// Eliminates one intermediate buffer and one memory pass compared to separate silu+mul.
#[inline]
pub fn silu_mul(output: &mut [f32], gate: &[f32], up: &[f32]) {
    for i in 0..gate.len() {
        let x = gate[i];
        output[i] = (x / (1.0 + (-x).exp())) * up[i];
    }
}

#[cfg(target_arch = "aarch64")]
#[inline]
pub fn elementwise_mul(output: &mut [f32], a: &[f32], b: &[f32]) {
    use std::arch::aarch64::*;
    let n = a.len();
    let chunks = n / 16;
    unsafe {
        for i in 0..chunks {
            let base = i * 16;
            vst1q_f32(output.as_mut_ptr().add(base), vmulq_f32(vld1q_f32(a.as_ptr().add(base)), vld1q_f32(b.as_ptr().add(base))));
            vst1q_f32(output.as_mut_ptr().add(base+4), vmulq_f32(vld1q_f32(a.as_ptr().add(base+4)), vld1q_f32(b.as_ptr().add(base+4))));
            vst1q_f32(output.as_mut_ptr().add(base+8), vmulq_f32(vld1q_f32(a.as_ptr().add(base+8)), vld1q_f32(b.as_ptr().add(base+8))));
            vst1q_f32(output.as_mut_ptr().add(base+12), vmulq_f32(vld1q_f32(a.as_ptr().add(base+12)), vld1q_f32(b.as_ptr().add(base+12))));
        }
    }
    for i in (chunks*16)..n { output[i] = a[i] * b[i]; }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
pub fn elementwise_mul(output: &mut [f32], a: &[f32], b: &[f32]) {
    for i in 0..a.len() { output[i] = a[i] * b[i]; }
}

#[cfg(target_arch = "aarch64")]
#[inline]
pub fn elementwise_add(output: &mut [f32], a: &[f32], b: &[f32]) {
    use std::arch::aarch64::*;
    let n = a.len();
    let chunks = n / 16;
    unsafe {
        for i in 0..chunks {
            let base = i * 16;
            vst1q_f32(output.as_mut_ptr().add(base), vaddq_f32(vld1q_f32(a.as_ptr().add(base)), vld1q_f32(b.as_ptr().add(base))));
            vst1q_f32(output.as_mut_ptr().add(base+4), vaddq_f32(vld1q_f32(a.as_ptr().add(base+4)), vld1q_f32(b.as_ptr().add(base+4))));
            vst1q_f32(output.as_mut_ptr().add(base+8), vaddq_f32(vld1q_f32(a.as_ptr().add(base+8)), vld1q_f32(b.as_ptr().add(base+8))));
            vst1q_f32(output.as_mut_ptr().add(base+12), vaddq_f32(vld1q_f32(a.as_ptr().add(base+12)), vld1q_f32(b.as_ptr().add(base+12))));
        }
    }
    for i in (chunks*16)..n { output[i] = a[i] + b[i]; }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
pub fn elementwise_add(output: &mut [f32], a: &[f32], b: &[f32]) {
    for i in 0..a.len() { output[i] = a[i] + b[i]; }
}

/// Fused residual add with NEON: a[i] += b[i]
#[cfg(target_arch = "aarch64")]
#[inline]
pub fn residual_add(a: &mut [f32], b: &[f32]) {
    use std::arch::aarch64::*;
    let n = a.len();
    let chunks = n / 16;
    unsafe {
        for i in 0..chunks {
            let base = i * 16;
            vst1q_f32(a.as_mut_ptr().add(base), vaddq_f32(vld1q_f32(a.as_ptr().add(base)), vld1q_f32(b.as_ptr().add(base))));
            vst1q_f32(a.as_mut_ptr().add(base+4), vaddq_f32(vld1q_f32(a.as_ptr().add(base+4)), vld1q_f32(b.as_ptr().add(base+4))));
            vst1q_f32(a.as_mut_ptr().add(base+8), vaddq_f32(vld1q_f32(a.as_ptr().add(base+8)), vld1q_f32(b.as_ptr().add(base+8))));
            vst1q_f32(a.as_mut_ptr().add(base+12), vaddq_f32(vld1q_f32(a.as_ptr().add(base+12)), vld1q_f32(b.as_ptr().add(base+12))));
        }
    }
    for i in (chunks*16)..n { a[i] += b[i]; }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
pub fn residual_add(a: &mut [f32], b: &[f32]) {
    for i in 0..a.len() { a[i] += b[i]; }
}

#[cfg(target_arch = "aarch64")]
#[inline]
pub fn softmax(values: &mut [f32]) {
    use std::arch::aarch64::*;
    // Find max using NEON
    let n = values.len();
    let mut max_val = unsafe {
        let chunks = n / 4;
        let mut vmax = vdupq_n_f32(f32::NEG_INFINITY);
        for i in 0..chunks { vmax = vmaxq_f32(vmax, vld1q_f32(values.as_ptr().add(i * 4))); }
        vmaxvq_f32(vmax)
    };
    for i in (n / 4 * 4)..n { if values[i] > max_val { max_val = values[i]; } }
    // Exp and sum
    let mut sum = 0.0f32;
    for v in values.iter_mut() { *v = (*v - max_val).exp(); sum += *v; }
    // Normalize with NEON
    let inv = 1.0 / sum;
    unsafe {
        let vinv = vdupq_n_f32(inv);
        let chunks = n / 4;
        for i in 0..chunks {
            let base = i * 4;
            vst1q_f32(values.as_mut_ptr().add(base), vmulq_f32(vld1q_f32(values.as_ptr().add(base)), vinv));
        }
    }
    for i in (n / 4 * 4)..n { values[i] *= inv; }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
pub fn softmax(values: &mut [f32]) {
    let max_val = values.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for v in values.iter_mut() { *v = (*v - max_val).exp(); sum += *v; }
    let inv = 1.0 / sum;
    for v in values.iter_mut() { *v *= inv; }
}

/// Precompute RoPE frequency table: freqs[i] = 1/theta^(2i/head_dim) for i in 0..head_dim/2
#[inline]
pub fn rope_freqs(head_dim: usize, theta: f32) -> Vec<f32> {
    (0..head_dim / 2).map(|i| 1.0 / theta.powf(2.0 * i as f32 / head_dim as f32)).collect()
}

/// Apply RoPE using precomputed frequencies — avoids powf per token.
/// Computes sin/cos table once per position, reuses across all heads.
#[inline]
pub fn rope(data: &mut [f32], pos: usize, head_dim: usize, num_heads: usize, freqs: &[f32]) {
    let half = head_dim / 2;
    // Precompute sin/cos for this position once — shared across all heads
    let mut cos_table = vec![0.0f32; half];
    let mut sin_table = vec![0.0f32; half];
    for i in 0..half {
        let angle = pos as f32 * freqs[i];
        let (s, c) = angle.sin_cos();
        cos_table[i] = c;
        sin_table[i] = s;
    }
    for h in 0..num_heads {
        let off = h * head_dim;
        for i in 0..half {
            let (x0, x1) = (data[off + 2*i], data[off + 2*i + 1]);
            data[off + 2*i] = x0 * cos_table[i] - x1 * sin_table[i];
            data[off + 2*i + 1] = x0 * sin_table[i] + x1 * cos_table[i];
        }
    }
}

#[inline]
pub fn attention(output: &mut [f32], q: &[f32], k_cache: &[f32], v_cache: &[f32],
    seq_len: usize, num_heads: usize, num_kv_heads: usize, head_dim: usize) {
    let gsize = num_heads / num_kv_heads;
    let scale = 1.0 / (head_dim as f32).sqrt();
    let kv_stride = num_kv_heads * head_dim;
    // Fixed-size scores buffer — no heap allocation
    let mut scores = [0.0f32; MAX_SEQ_LEN];
    for h in 0..num_heads {
        let kv_h = h / gsize;
        let qo = h * head_dim;
        for t in 0..seq_len {
            let ko = t * kv_stride + kv_h * head_dim;
            scores[t] = dot_f32(&q[qo..qo+head_dim], &k_cache[ko..ko+head_dim], head_dim) * scale;
        }
        softmax(&mut scores[..seq_len]);
        for d in 0..head_dim {
            let mut sum = 0.0f32;
            for t in 0..seq_len {
                sum += scores[t] * v_cache[t * kv_stride + kv_h * head_dim + d];
            }
            output[qo+d] = sum;
        }
    }
}

#[inline]
pub fn embedding(output: &mut [f32], token_id: u32, weight: &[f32], embed_dim: usize) {
    let off = token_id as usize * embed_dim;
    output.copy_from_slice(&weight[off..off + embed_dim]);
}

"#,
    );

    Ok(())
}

/// Collect all unique (k, n) matmul shapes used in the forward pass.
fn matmul_shapes(config: &ModelConfig) -> Vec<(usize, usize)> {
    let hidden = config.hidden_size;
    let intermediate = config.intermediate_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let vocab = config.vocab_size;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    let mut shapes = vec![
        (hidden, qk_size),      // q_proj
        (hidden, kv_size),      // k_proj, v_proj
        (qk_size, hidden),      // o_proj
        (hidden, intermediate), // gate_proj, up_proj
        (intermediate, hidden), // down_proj
        (hidden, vocab),        // lm_head
    ];
    shapes.sort();
    shapes.dedup();
    shapes
}

/// Emit specialized matmul_vec functions with baked-in K and N dimensions.
/// Since all our matmuls are m=1 (single-token inference), we generate
/// `matmul_vec_KxN(output, input, weight)` with no runtime dimension args.
fn emit_specialized_matmul_functions(
    code: &mut String,
    config: &ModelConfig,
) -> Result<(), CodegenError> {
    writeln!(code, "// --- Shape-specialized matmul functions (m=1) ---")?;
    writeln!(code, "// All dimensions baked in at compile time — no runtime size parameters.")?;
    writeln!(code)?;

    // Threshold for parallelization: only parallelize if N >= 4096
    // (otherwise Rayon overhead dominates the compute for small matmuls)
    let par_threshold = 4096;

    for &(k, n) in &matmul_shapes(config) {
        writeln!(code, "/// Specialized matmul: [1, {k}] x [{n}, {k}]^T -> [1, {n}]")?;
        if n >= par_threshold {
            // Parallel path: par_chunks_mut(256) for cache locality + amortized Rayon overhead
            writeln!(code, "/// Parallelized: par_chunks_mut(256) with 4-way row ILP per thread")?;
            writeln!(code, "#[inline]")?;
            writeln!(
                code,
                "fn matmul_vec_{k}x{n}(output: &mut [f32; {n}], input: &[f32; {k}], weight: &[f32]) {{"
            )?;
            writeln!(
                code,
                "    output.par_chunks_mut(256).enumerate().for_each(|(chunk_idx, out)| {{"
            )?;
            writeln!(code, "        let base = chunk_idx * 256;")?;
            writeln!(code, "        let len = out.len();")?;
            writeln!(code, "        let chunks4 = len / 4;")?;
            writeln!(code, "        for c in 0..chunks4 {{")?;
            writeln!(code, "            let r = c * 4;")?;
            writeln!(code, "            let j = base + r;")?;
            writeln!(code, "            out[r]   = dot_f32(&input[..], &weight[j*{k}..(j+1)*{k}], {k});")?;
            writeln!(code, "            out[r+1] = dot_f32(&input[..], &weight[(j+1)*{k}..(j+2)*{k}], {k});")?;
            writeln!(code, "            out[r+2] = dot_f32(&input[..], &weight[(j+2)*{k}..(j+3)*{k}], {k});")?;
            writeln!(code, "            out[r+3] = dot_f32(&input[..], &weight[(j+3)*{k}..(j+4)*{k}], {k});")?;
            writeln!(code, "        }}")?;
            writeln!(code, "        for r in (chunks4*4)..len {{")?;
            writeln!(code, "            let j = base + r;")?;
            writeln!(code, "            out[r] = dot_f32(&input[..], &weight[j*{k}..(j+1)*{k}], {k});")?;
            writeln!(code, "        }}")?;
            writeln!(code, "    }});")?;
            writeln!(code, "}}")?;
        } else {
            // Sequential with 4-way row unrolling for ILP
            writeln!(code, "#[inline]")?;
            writeln!(
                code,
                "fn matmul_vec_{k}x{n}(output: &mut [f32; {n}], input: &[f32; {k}], weight: &[f32]) {{"
            )?;
            let n_chunks = n / 4;
            let n_remainder = n % 4;
            if n_chunks > 0 {
                writeln!(code, "    // Process 4 output rows at a time for instruction-level parallelism")?;
                writeln!(code, "    for chunk in 0..{n_chunks} {{")?;
                writeln!(code, "        let j0 = chunk * 4;")?;
                writeln!(code, "        output[j0]   = dot_f32(&input[..], &weight[j0*{k}..(j0+1)*{k}], {k});")?;
                writeln!(code, "        output[j0+1] = dot_f32(&input[..], &weight[(j0+1)*{k}..(j0+2)*{k}], {k});")?;
                writeln!(code, "        output[j0+2] = dot_f32(&input[..], &weight[(j0+2)*{k}..(j0+3)*{k}], {k});")?;
                writeln!(code, "        output[j0+3] = dot_f32(&input[..], &weight[(j0+3)*{k}..(j0+4)*{k}], {k});")?;
                writeln!(code, "    }}")?;
            }
            if n_remainder > 0 {
                writeln!(code, "    // Handle remaining {n_remainder} output rows")?;
                writeln!(code, "    let base = {} * 4;", n_chunks)?;
                for r in 0..n_remainder {
                    writeln!(code, "    output[base+{r}] = dot_f32(&input[..], &weight[(base+{r})*{k}..(base+{r}+1)*{k}], {k});")?;
                }
            }
            writeln!(code, "}}")?;
        }
        writeln!(code)?;
    }

    Ok(())
}

fn emit_forward_function(
    code: &mut String,
    _graph: &Graph,
    config: &ModelConfig,
) -> Result<(), CodegenError> {
    let hidden = config.hidden_size;
    let intermediate = config.intermediate_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let vocab = config.vocab_size;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    writeln!(
        code,
        "/// Model weights — loaded once, passed to forward()."
    )?;
    writeln!(code, "pub struct Weights {{")?;
    writeln!(
        code,
        "    pub embed_tokens: Vec<f32>,       // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "    pub layers: Vec<LayerWeights>,")?;
    writeln!(code, "    pub final_norm: Vec<f32>,          // [{hidden}]")?;
    writeln!(
        code,
        "    pub lm_head: Vec<f32>,             // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "pub struct LayerWeights {{")?;
    writeln!(code, "    pub attn_norm: Vec<f32>,           // [{hidden}]")?;
    writeln!(
        code,
        "    pub q_proj: Vec<f32>,              // [{} * {hidden}]",
        num_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub k_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub v_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub o_proj: Vec<f32>,              // [{hidden} * {}]",
        num_heads * head_dim
    )?;
    writeln!(code, "    pub ffn_norm: Vec<f32>,            // [{hidden}]")?;
    writeln!(
        code,
        "    pub gate_proj: Vec<f32>,           // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub up_proj: Vec<f32>,             // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub down_proj: Vec<f32>,           // [{hidden} * {intermediate}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "/// KV cache for autoregressive generation.")?;
    writeln!(code, "/// Pre-allocated to MAX_SEQ_LEN — zero allocations during inference.")?;
    writeln!(code, "pub struct KVCache {{")?;
    writeln!(
        code,
        "    pub k: Vec<Vec<f32>>,  // [num_layers][MAX_SEQ_LEN * {}]  (pre-allocated)",
        kv_size
    )?;
    writeln!(
        code,
        "    pub v: Vec<Vec<f32>>,  // [num_layers][MAX_SEQ_LEN * {}]  (pre-allocated)",
        kv_size
    )?;
    writeln!(code, "    pub len: usize,")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "impl KVCache {{")?;
    writeln!(code, "    pub fn new() -> Self {{")?;
    writeln!(code, "        Self {{")?;
    writeln!(
        code,
        "            k: (0..NUM_LAYERS).map(|_| vec![0.0f32; MAX_SEQ_LEN * {kv_size}]).collect(),",
        kv_size = kv_size
    )?;
    writeln!(
        code,
        "            v: (0..NUM_LAYERS).map(|_| vec![0.0f32; MAX_SEQ_LEN * {kv_size}]).collect(),",
        kv_size = kv_size
    )?;
    writeln!(code, "            len: 0,")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Forward function for single token (generation mode)
    writeln!(
        code,
        "/// Run forward pass for a single token. Returns logits [{vocab}]."
    )?;
    writeln!(
        code,
        "pub fn forward(token_id: u32, weights: &Weights, cache: &mut KVCache) -> Vec<f32> {{"
    )?;
    writeln!(code, "    let pos = cache.len;")?;
    writeln!(code)?;

    // Embedding
    writeln!(code, "    // Embedding lookup")?;
    writeln!(
        code,
        "    let mut hidden_state = [0.0f32; HIDDEN_SIZE];"
    )?;
    writeln!(
        code,
        "    embedding(&mut hidden_state, token_id, &weights.embed_tokens, HIDDEN_SIZE);"
    )?;
    writeln!(code)?;

    // Buffers — fixed-size arrays, zero heap allocation
    writeln!(code, "    // Fixed-size buffers — zero heap allocation during forward pass")?;
    writeln!(code, "    let mut normed = [0.0f32; {hidden}];")?;
    writeln!(code, "    let mut q = [0.0f32; {qk_size}];")?;
    writeln!(code, "    let mut k = [0.0f32; {kv_size}];")?;
    writeln!(code, "    let mut v = [0.0f32; {kv_size}];")?;
    writeln!(code, "    let mut attn_out = [0.0f32; {qk_size}];")?;
    writeln!(code, "    let mut attn_proj = [0.0f32; {hidden}];")?;
    writeln!(code, "    let mut gate = [0.0f32; {intermediate}];")?;
    writeln!(code, "    let mut up = [0.0f32; {intermediate}];")?;
    writeln!(code, "    let mut ffn_hidden = [0.0f32; {intermediate}];")?;
    writeln!(code, "    let mut ffn_out = [0.0f32; {hidden}];")?;
    writeln!(code)?;
    writeln!(code, "    // Precomputed RoPE frequencies — avoids powf per token")?;
    writeln!(code, "    let rope_freqs = rope_freqs(HEAD_DIM, ROPE_THETA);")?;
    writeln!(code)?;

    // Transformer layers
    writeln!(code, "    // Transformer layers")?;
    writeln!(code, "    for layer_idx in 0..NUM_LAYERS {{")?;
    writeln!(code, "        let lw = &weights.layers[layer_idx];")?;
    writeln!(code)?;
    writeln!(code, "        // Attention norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &hidden_state, &lw.attn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // QKV projections (shape-specialized)")?;
    writeln!(
        code,
        "        matmul_vec_{hidden}x{qk_size}(&mut q, &normed, &lw.q_proj);",
        hidden = hidden, qk_size = qk_size
    )?;
    writeln!(
        code,
        "        matmul_vec_{hidden}x{kv_size}(&mut k, &normed, &lw.k_proj);",
        hidden = hidden, kv_size = kv_size
    )?;
    writeln!(
        code,
        "        matmul_vec_{hidden}x{kv_size}(&mut v, &normed, &lw.v_proj);",
        hidden = hidden, kv_size = kv_size
    )?;
    writeln!(code)?;
    writeln!(code, "        // RoPE")?;
    writeln!(
        code,
        "        rope(&mut q, pos, HEAD_DIM, NUM_HEADS, &rope_freqs);"
    )?;
    writeln!(
        code,
        "        rope(&mut k, pos, HEAD_DIM, NUM_KV_HEADS, &rope_freqs);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // Update KV cache (direct indexed write, no allocation)")?;
    writeln!(
        code,
        "        cache.k[layer_idx][pos*{kv_size}..(pos+1)*{kv_size}].copy_from_slice(&k);",
        kv_size = kv_size
    )?;
    writeln!(
        code,
        "        cache.v[layer_idx][pos*{kv_size}..(pos+1)*{kv_size}].copy_from_slice(&v);",
        kv_size = kv_size
    )?;
    writeln!(code)?;
    writeln!(code, "        // Attention (cache sliced to valid region)")?;
    writeln!(code, "        attention(")?;
    writeln!(code, "            &mut attn_out, &q,")?;
    writeln!(
        code,
        "            &cache.k[layer_idx][..(pos+1)*{kv_size}], &cache.v[layer_idx][..(pos+1)*{kv_size}],",
        kv_size = kv_size
    )?;
    writeln!(
        code,
        "            pos + 1, NUM_HEADS, NUM_KV_HEADS, HEAD_DIM,"
    )?;
    writeln!(code, "        );")?;
    writeln!(code)?;
    writeln!(code, "        // Output projection + fused residual add")?;
    writeln!(
        code,
        "        matmul_vec_{qk_size}x{hidden}(&mut attn_proj, &attn_out, &lw.o_proj);",
        qk_size = qk_size, hidden = hidden
    )?;
    writeln!(
        code,
        "        residual_add(&mut hidden_state, &attn_proj);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // FFN norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &hidden_state, &lw.ffn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        // FFN: fused silu_mul eliminates gate_act buffer"
    )?;
    writeln!(
        code,
        "        matmul_vec_{hidden}x{intermediate}(&mut gate, &normed, &lw.gate_proj);",
        hidden = hidden, intermediate = intermediate
    )?;
    writeln!(
        code,
        "        matmul_vec_{hidden}x{intermediate}(&mut up, &normed, &lw.up_proj);",
        hidden = hidden, intermediate = intermediate
    )?;
    writeln!(
        code,
        "        silu_mul(&mut ffn_hidden, &gate, &up);"
    )?;
    writeln!(
        code,
        "        matmul_vec_{intermediate}x{hidden}(&mut ffn_out, &ffn_hidden, &lw.down_proj);",
        intermediate = intermediate, hidden = hidden
    )?;
    writeln!(code)?;
    writeln!(code, "        // Fused residual add")?;
    writeln!(
        code,
        "        residual_add(&mut hidden_state, &ffn_out);"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;

    // Final norm + logits
    writeln!(code, "    // Final norm")?;
    writeln!(
        code,
        "    rms_norm(&mut normed, &hidden_state, &weights.final_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "    // Logits projection (parallelized — largest single matmul)")?;
    writeln!(code, "    // Uses larger chunks (256) to amortize Rayon overhead")?;
    writeln!(code, "    let mut logits = vec![0.0f32; VOCAB_SIZE];")?;
    writeln!(
        code,
        "    logits.par_chunks_mut(256).enumerate().for_each(|(chunk_idx, out)| {{"
    )?;
    writeln!(code, "        let base = chunk_idx * 256;")?;
    writeln!(code, "        for r in 0..out.len() {{")?;
    writeln!(
        code,
        "            let j = base + r;"
    )?;
    writeln!(
        code,
        "            out[r] = dot_f32(&normed[..], &weights.lm_head[j*{hidden}..(j+1)*{hidden}], {hidden});"
    )?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }});")?;
    writeln!(code)?;
    writeln!(code, "    cache.len += 1;")?;
    writeln!(code, "    logits")?;
    writeln!(code, "}}")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::graph_builder;

    fn tiny_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 2,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 64,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        }
    }

    #[test]
    fn generate_code_from_tiny_model() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 64;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 2;"));
        assert!(code.contains("pub const VOCAB_SIZE: usize = 256;"));
        assert!(code.contains("fn rms_norm("));
        assert!(code.contains("fn matmul_vec_"));
        assert!(code.contains("fn forward("));
        assert!(code.contains("fn attention("));
    }

    #[test]
    fn generated_code_has_correct_structure() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Should have weight structs
        assert!(code.contains("pub struct Weights"));
        assert!(code.contains("pub struct LayerWeights"));
        assert!(code.contains("pub struct KVCache"));

        // Should have all kernel functions including fused ops
        assert!(code.contains("pub fn silu("));
        assert!(code.contains("pub fn silu_mul("));
        assert!(code.contains("pub fn residual_add("));
        assert!(code.contains("pub fn softmax("));
        assert!(code.contains("pub fn rope("));
        assert!(code.contains("pub fn embedding("));
        assert!(code.contains("pub fn elementwise_mul("));
        assert!(code.contains("pub fn elementwise_add("));
    }

    #[test]
    fn generate_code_for_llama_1b() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 2048,
            intermediate_size: 5632,
            num_layers: 16,
            num_attention_heads: 32,
            num_kv_heads: 8,
            head_dim: 64,
            vocab_size: 32000,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 2048;"));
        assert!(code.contains("pub const NUM_HEADS: usize = 32;"));
        assert!(code.contains("pub const NUM_KV_HEADS: usize = 8;"));
    }

    #[test]
    fn generate_code_for_smollm() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 576,
            intermediate_size: 1536,
            num_layers: 30,
            num_attention_heads: 9,
            num_kv_heads: 3,
            head_dim: 64,
            vocab_size: 49152,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::BF16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 576;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 30;"));

        // Shape-specialized matmul: hidden=576, qk=9*64=576, kv=3*64=192, inter=1536
        assert!(code.contains("fn matmul_vec_576x576("));  // q_proj (hidden→qk)
        assert!(code.contains("fn matmul_vec_576x192("));  // k/v_proj (hidden→kv)
        assert!(code.contains("fn matmul_vec_576x1536(")); // gate/up_proj
        assert!(code.contains("fn matmul_vec_1536x576(")); // down_proj
        // Forward function uses specialized calls
        assert!(code.contains("matmul_vec_576x576(&mut q"));
        assert!(code.contains("matmul_vec_576x192(&mut k"));
        assert!(!code.contains("matmul(&mut q")); // no generic matmul calls
    }

    #[test]
    fn generated_code_compiles_as_rust() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Verify the generated code is valid Rust by checking syntax
        // (actual compilation test would require writing to file and running cargo)
        assert!(code.starts_with("//!"));
        assert!(!code.contains("TODO"));
        assert!(!code.contains("unimplemented"));

        // Check balanced braces
        let opens: usize = code.chars().filter(|&c| c == '{').count();
        let closes: usize = code.chars().filter(|&c| c == '}').count();
        assert_eq!(opens, closes, "unbalanced braces in generated code");
    }

    #[test]
    fn graph_without_config_errors() {
        let graph = Graph::new("no-config");
        let result = generate(&graph);
        assert!(matches!(result, Err(CodegenError::MissingConfig)));
    }

    #[test]
    fn generated_code_has_fused_ops() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Fused silu_mul kernel exists
        assert!(code.contains("pub fn silu_mul("));
        // Fused gelu_mul kernel exists
        assert!(code.contains("pub fn gelu_mul("));
        // Fused residual_add kernel exists
        assert!(code.contains("pub fn residual_add("));
        // Forward uses fused ops
        assert!(code.contains("silu_mul(&mut ffn_hidden"));
        assert!(code.contains("residual_add(&mut hidden_state"));
        // No separate silu+elementwise_mul in forward path
        assert!(!code.contains("silu(&mut gate_act"));
    }

    #[test]
    fn generated_code_has_rayon_parallel() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Should have rayon import
        assert!(code.contains("use rayon::prelude::*;"));
        // Logits should be parallelized (par_chunks_mut for ILP)
        assert!(code.contains("par_chunks_mut"));
    }

    #[test]
    fn generated_code_has_rope_precomputation() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub fn rope_freqs("));
        assert!(code.contains("let rope_freqs = rope_freqs(HEAD_DIM, ROPE_THETA);"));
        assert!(code.contains("&rope_freqs)"));
    }

    #[test]
    fn generated_code_has_neon_simd() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // NEON dot product
        assert!(code.contains("#[cfg(target_arch = \"aarch64\")]"));
        assert!(code.contains("vfmaq_f32"));
        // NEON elementwise ops
        assert!(code.contains("vmulq_f32"));
        assert!(code.contains("vaddq_f32"));
        // Scalar fallbacks
        assert!(code.contains("#[cfg(not(target_arch = \"aarch64\"))]"));
    }

    #[test]
    fn generated_code_has_static_memory() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Fixed-size stack buffers (not vec!)
        assert!(code.contains("let mut normed = [0.0f32;"));
        assert!(code.contains("let mut q = [0.0f32;"));
        assert!(code.contains("let mut hidden_state = [0.0f32;"));
        // Pre-allocated KV cache
        assert!(code.contains("MAX_SEQ_LEN *"));
        // Attention scores on stack
        assert!(code.contains("[0.0f32; MAX_SEQ_LEN]"));
    }

    #[test]
    fn generated_code_has_4_accumulator_dot_f32() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // dot_f32 should use 4 accumulators (s0..s3)
        assert!(code.contains("let mut s0 = vdupq_n_f32(0.0);"));
        assert!(code.contains("let mut s1 = vdupq_n_f32(0.0);"));
        assert!(code.contains("let mut s2 = vdupq_n_f32(0.0);"));
        assert!(code.contains("let mut s3 = vdupq_n_f32(0.0);"));
        // 16-element unrolled loop
        assert!(code.contains("len / 16"));
    }

    #[test]
    fn parallel_path_uses_chunks_with_ilp() {
        // Use a config with N >= 4096 to trigger parallel path
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 896,
            intermediate_size: 4864, // > 4096 threshold
            num_layers: 24,
            num_attention_heads: 14,
            num_kv_heads: 2,
            head_dim: 64,
            vocab_size: 151936,
            max_seq_len: 2048,
            rms_norm_eps: 1e-6,
            rope_theta: 1e6,
            dtype: DType::F16,
        };
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Should use par_chunks_mut(256) for parallel matmul
        assert!(code.contains("par_chunks_mut(256)"));
        // Should have 4-way row ILP within parallel chunks
        assert!(code.contains("let chunks4 = len / 4;"));
        // Specialized matmul for the intermediate size
        assert!(code.contains("matmul_vec_896x4864("));
    }

    #[test]
    fn generated_code_has_4_way_row_unrolling() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Sequential matmul should process 4 rows at a time
        assert!(code.contains("Process 4 output rows at a time"));
        assert!(code.contains("output[j0]"));
        assert!(code.contains("output[j0+1]"));
        assert!(code.contains("output[j0+2]"));
        assert!(code.contains("output[j0+3]"));
    }

    #[test]
    fn generated_code_has_release_profile_optimizations() {
        // Verified at the project.rs level — emit.rs only generates model.rs
        // This test verifies the model file has the dead_code allow
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("#![allow(dead_code, unused_imports, unused_assignments)]"));
    }
}
