//! Rust source code emission from IR graphs.
//!
//! Generates a complete Rust module containing:
//! - Typed buffer declarations for all intermediate tensors
//! - Specialized kernel functions for each operation
//! - A `forward()` function that chains all operations
//!
//! The generated code operates on flat f32 slices — no dynamic shapes.

use std::fmt::Write;

use forgellm_frontend::ir::*;

/// Generate Rust source code from a computation graph.
///
/// Returns a string containing a complete Rust module that implements
/// the model's forward pass. The generated code:
/// - Uses `&[f32]` for weight inputs (pre-loaded)
/// - Uses flat arrays for all intermediate buffers
/// - Has zero allocations during the forward pass
pub fn generate(graph: &Graph) -> Result<String, CodegenError> {
    let config = graph.config.as_ref().ok_or(CodegenError::MissingConfig)?;

    let mut code = String::with_capacity(32 * 1024);

    emit_header(&mut code, config)?;
    emit_kernel_functions(&mut code)?;
    emit_forward_function(&mut code, graph, config)?;

    Ok(code)
}

/// Errors during code generation.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("graph has no model config")]
    MissingConfig,

    #[error("unsupported operation for CPU codegen: {0}")]
    UnsupportedOp(String),

    #[error("format error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

fn emit_header(code: &mut String, config: &ModelConfig) -> Result<(), CodegenError> {
    writeln!(code, "//! Auto-generated by ForgeLLM CPU codegen.")?;
    writeln!(
        code,
        "//! Model: {} ({} layers, hidden={})",
        config.architecture, config.num_layers, config.hidden_size
    )?;
    writeln!(code, "//!")?;
    writeln!(
        code,
        "//! This code has no dynamic dispatch — all dimensions are baked in."
    )?;
    writeln!(code)?;
    writeln!(code, "#![allow(clippy::excessive_precision)]")?;
    writeln!(code)?;
    writeln!(code, "// Model constants")?;
    writeln!(
        code,
        "pub const HIDDEN_SIZE: usize = {};",
        config.hidden_size
    )?;
    writeln!(
        code,
        "pub const INTERMEDIATE_SIZE: usize = {};",
        config.intermediate_size
    )?;
    writeln!(code, "pub const NUM_LAYERS: usize = {};", config.num_layers)?;
    writeln!(
        code,
        "pub const NUM_HEADS: usize = {};",
        config.num_attention_heads
    )?;
    writeln!(
        code,
        "pub const NUM_KV_HEADS: usize = {};",
        config.num_kv_heads
    )?;
    writeln!(code, "pub const HEAD_DIM: usize = {};", config.head_dim)?;
    writeln!(code, "pub const VOCAB_SIZE: usize = {};", config.vocab_size)?;
    writeln!(
        code,
        "pub const MAX_SEQ_LEN: usize = {};",
        config.max_seq_len
    )?;
    writeln!(
        code,
        "pub const RMS_NORM_EPS: f32 = {:e};",
        config.rms_norm_eps
    )?;
    writeln!(code, "pub const ROPE_THETA: f32 = {:e};", config.rope_theta)?;
    writeln!(code)?;
    Ok(())
}

fn emit_kernel_functions(code: &mut String) -> Result<(), CodegenError> {
    // RMSNorm kernel
    writeln!(
        code,
        "/// RMS normalization: output = (x / rms(x)) * weight"
    )?;
    writeln!(code, "#[inline]")?;
    writeln!(
        code,
        "pub fn rms_norm(output: &mut [f32], input: &[f32], weight: &[f32], eps: f32) {{"
    )?;
    writeln!(code, "    let n = input.len();")?;
    writeln!(code, "    let mut sum_sq: f32 = 0.0;")?;
    writeln!(code, "    for i in 0..n {{")?;
    writeln!(code, "        sum_sq += input[i] * input[i];")?;
    writeln!(code, "    }}")?;
    writeln!(code, "    let rms = (sum_sq / n as f32 + eps).sqrt();")?;
    writeln!(code, "    let inv_rms = 1.0 / rms;")?;
    writeln!(code, "    for i in 0..n {{")?;
    writeln!(code, "        output[i] = input[i] * inv_rms * weight[i];")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // MatMul kernel: output[m][n] = input[m][k] * weight[n][k]^T
    writeln!(
        code,
        "/// Matrix multiply: output[m,n] = input[m,k] * weight^T[k,n]"
    )?;
    writeln!(
        code,
        "/// Weight is stored as [n, k] (row-major), so weight[j] is row j."
    )?;
    writeln!(code, "#[inline]")?;
    writeln!(code, "pub fn matmul(output: &mut [f32], input: &[f32], weight: &[f32], m: usize, k: usize, n: usize) {{")?;
    writeln!(code, "    for i in 0..m {{")?;
    writeln!(code, "        for j in 0..n {{")?;
    writeln!(code, "            let mut sum: f32 = 0.0;")?;
    writeln!(code, "            for l in 0..k {{")?;
    writeln!(
        code,
        "                sum += input[i * k + l] * weight[j * k + l];"
    )?;
    writeln!(code, "            }}")?;
    writeln!(code, "            output[i * n + j] = sum;")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // SiLU activation
    writeln!(code, "/// SiLU activation: x * sigmoid(x)")?;
    writeln!(code, "#[inline]")?;
    writeln!(code, "pub fn silu(output: &mut [f32], input: &[f32]) {{")?;
    writeln!(code, "    for i in 0..input.len() {{")?;
    writeln!(code, "        let x = input[i];")?;
    writeln!(code, "        output[i] = x / (1.0 + (-x).exp());")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Elementwise multiply
    writeln!(code, "/// Elementwise multiply: output = a * b")?;
    writeln!(code, "#[inline]")?;
    writeln!(
        code,
        "pub fn elementwise_mul(output: &mut [f32], a: &[f32], b: &[f32]) {{"
    )?;
    writeln!(code, "    for i in 0..a.len() {{")?;
    writeln!(code, "        output[i] = a[i] * b[i];")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Elementwise add (residual)
    writeln!(
        code,
        "/// Elementwise add (residual connection): output = a + b"
    )?;
    writeln!(code, "#[inline]")?;
    writeln!(
        code,
        "pub fn elementwise_add(output: &mut [f32], a: &[f32], b: &[f32]) {{"
    )?;
    writeln!(code, "    for i in 0..a.len() {{")?;
    writeln!(code, "        output[i] = a[i] + b[i];")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Softmax
    writeln!(code, "/// Softmax over a slice")?;
    writeln!(code, "#[inline]")?;
    writeln!(code, "pub fn softmax(values: &mut [f32]) {{")?;
    writeln!(
        code,
        "    let max_val = values.iter().copied().fold(f32::NEG_INFINITY, f32::max);"
    )?;
    writeln!(code, "    let mut sum: f32 = 0.0;")?;
    writeln!(code, "    for v in values.iter_mut() {{")?;
    writeln!(code, "        *v = (*v - max_val).exp();")?;
    writeln!(code, "        sum += *v;")?;
    writeln!(code, "    }}")?;
    writeln!(code, "    for v in values.iter_mut() {{")?;
    writeln!(code, "        *v /= sum;")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // RoPE
    writeln!(code, "/// Apply Rotary Position Embedding to Q or K")?;
    writeln!(code, "#[inline]")?;
    writeln!(code, "pub fn rope(data: &mut [f32], pos: usize, head_dim: usize, num_heads: usize, theta: f32) {{")?;
    writeln!(code, "    for h in 0..num_heads {{")?;
    writeln!(code, "        let head_offset = h * head_dim;")?;
    writeln!(code, "        for i in (0..head_dim).step_by(2) {{")?;
    writeln!(
        code,
        "            let freq = 1.0 / theta.powf(i as f32 / head_dim as f32);"
    )?;
    writeln!(code, "            let angle = pos as f32 * freq;")?;
    writeln!(code, "            let cos_val = angle.cos();")?;
    writeln!(code, "            let sin_val = angle.sin();")?;
    writeln!(code, "            let x0 = data[head_offset + i];")?;
    writeln!(code, "            let x1 = data[head_offset + i + 1];")?;
    writeln!(
        code,
        "            data[head_offset + i] = x0 * cos_val - x1 * sin_val;"
    )?;
    writeln!(
        code,
        "            data[head_offset + i + 1] = x0 * sin_val + x1 * cos_val;"
    )?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Attention
    writeln!(
        code,
        "/// Single-token grouped-query attention (for generation)"
    )?;
    writeln!(code, "#[inline]")?;
    writeln!(code, "pub fn attention(")?;
    writeln!(code, "    output: &mut [f32],")?;
    writeln!(code, "    q: &[f32],        // [num_heads * head_dim]")?;
    writeln!(
        code,
        "    k_cache: &[f32],   // [seq_len, num_kv_heads * head_dim]"
    )?;
    writeln!(
        code,
        "    v_cache: &[f32],   // [seq_len, num_kv_heads * head_dim]"
    )?;
    writeln!(code, "    seq_len: usize,")?;
    writeln!(code, "    num_heads: usize,")?;
    writeln!(code, "    num_kv_heads: usize,")?;
    writeln!(code, "    head_dim: usize,")?;
    writeln!(code, ") {{")?;
    writeln!(code, "    let kv_group_size = num_heads / num_kv_heads;")?;
    writeln!(code, "    let scale = 1.0 / (head_dim as f32).sqrt();")?;
    writeln!(code)?;
    writeln!(code, "    for h in 0..num_heads {{")?;
    writeln!(code, "        let kv_h = h / kv_group_size;")?;
    writeln!(code, "        let q_offset = h * head_dim;")?;
    writeln!(code)?;
    writeln!(code, "        // Compute attention scores")?;
    writeln!(code, "        let mut scores = vec![0.0f32; seq_len];")?;
    writeln!(code, "        for t in 0..seq_len {{")?;
    writeln!(
        code,
        "            let k_offset = t * num_kv_heads * head_dim + kv_h * head_dim;"
    )?;
    writeln!(code, "            let mut dot: f32 = 0.0;")?;
    writeln!(code, "            for d in 0..head_dim {{")?;
    writeln!(
        code,
        "                dot += q[q_offset + d] * k_cache[k_offset + d];"
    )?;
    writeln!(code, "            }}")?;
    writeln!(code, "            scores[t] = dot * scale;")?;
    writeln!(code, "        }}")?;
    writeln!(code)?;
    writeln!(code, "        // Softmax")?;
    writeln!(code, "        softmax(&mut scores);")?;
    writeln!(code)?;
    writeln!(code, "        // Weighted sum of values")?;
    writeln!(code, "        for d in 0..head_dim {{")?;
    writeln!(code, "            let mut sum: f32 = 0.0;")?;
    writeln!(code, "            for t in 0..seq_len {{")?;
    writeln!(
        code,
        "                let v_offset = t * num_kv_heads * head_dim + kv_h * head_dim;"
    )?;
    writeln!(
        code,
        "                sum += scores[t] * v_cache[v_offset + d];"
    )?;
    writeln!(code, "            }}")?;
    writeln!(code, "            output[q_offset + d] = sum;")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Embedding lookup
    writeln!(code, "/// Token embedding lookup")?;
    writeln!(code, "#[inline]")?;
    writeln!(
        code,
        "pub fn embedding(output: &mut [f32], token_id: u32, weight: &[f32], embed_dim: usize) {{"
    )?;
    writeln!(code, "    let offset = token_id as usize * embed_dim;")?;
    writeln!(
        code,
        "    output.copy_from_slice(&weight[offset..offset + embed_dim]);"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    Ok(())
}

fn emit_forward_function(
    code: &mut String,
    _graph: &Graph,
    config: &ModelConfig,
) -> Result<(), CodegenError> {
    let hidden = config.hidden_size;
    let intermediate = config.intermediate_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let vocab = config.vocab_size;

    writeln!(
        code,
        "/// Model weights — loaded once, passed to forward()."
    )?;
    writeln!(code, "pub struct Weights {{")?;
    writeln!(
        code,
        "    pub embed_tokens: Vec<f32>,       // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "    pub layers: Vec<LayerWeights>,")?;
    writeln!(code, "    pub final_norm: Vec<f32>,          // [{hidden}]")?;
    writeln!(
        code,
        "    pub lm_head: Vec<f32>,             // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "pub struct LayerWeights {{")?;
    writeln!(code, "    pub attn_norm: Vec<f32>,           // [{hidden}]")?;
    writeln!(
        code,
        "    pub q_proj: Vec<f32>,              // [{} * {hidden}]",
        num_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub k_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub v_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub o_proj: Vec<f32>,              // [{hidden} * {}]",
        num_heads * head_dim
    )?;
    writeln!(code, "    pub ffn_norm: Vec<f32>,            // [{hidden}]")?;
    writeln!(
        code,
        "    pub gate_proj: Vec<f32>,           // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub up_proj: Vec<f32>,             // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub down_proj: Vec<f32>,           // [{hidden} * {intermediate}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "/// KV cache for autoregressive generation.")?;
    writeln!(code, "pub struct KVCache {{")?;
    writeln!(
        code,
        "    pub k: Vec<Vec<f32>>,  // [num_layers][seq_len * {} * {}]",
        num_kv_heads, head_dim
    )?;
    writeln!(
        code,
        "    pub v: Vec<Vec<f32>>,  // [num_layers][seq_len * {} * {}]",
        num_kv_heads, head_dim
    )?;
    writeln!(code, "    pub len: usize,")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "impl KVCache {{")?;
    writeln!(code, "    pub fn new() -> Self {{")?;
    writeln!(code, "        Self {{")?;
    writeln!(
        code,
        "            k: (0..NUM_LAYERS).map(|_| Vec::new()).collect(),"
    )?;
    writeln!(
        code,
        "            v: (0..NUM_LAYERS).map(|_| Vec::new()).collect(),"
    )?;
    writeln!(code, "            len: 0,")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Forward function for single token (generation mode)
    writeln!(
        code,
        "/// Run forward pass for a single token. Returns logits [{vocab}]."
    )?;
    writeln!(
        code,
        "pub fn forward(token_id: u32, weights: &Weights, cache: &mut KVCache) -> Vec<f32> {{"
    )?;
    writeln!(code, "    let pos = cache.len;")?;
    writeln!(code)?;

    // Embedding
    writeln!(code, "    // Embedding lookup")?;
    writeln!(
        code,
        "    let mut hidden_state = vec![0.0f32; HIDDEN_SIZE];"
    )?;
    writeln!(
        code,
        "    embedding(&mut hidden_state, token_id, &weights.embed_tokens, HIDDEN_SIZE);"
    )?;
    writeln!(code)?;

    // Buffers
    writeln!(code, "    // Pre-allocate buffers")?;
    writeln!(code, "    let mut normed = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut q = vec![0.0f32; NUM_HEADS * HEAD_DIM];")?;
    writeln!(
        code,
        "    let mut k = vec![0.0f32; NUM_KV_HEADS * HEAD_DIM];"
    )?;
    writeln!(
        code,
        "    let mut v = vec![0.0f32; NUM_KV_HEADS * HEAD_DIM];"
    )?;
    writeln!(
        code,
        "    let mut attn_out = vec![0.0f32; NUM_HEADS * HEAD_DIM];"
    )?;
    writeln!(code, "    let mut attn_proj = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut residual = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut gate = vec![0.0f32; INTERMEDIATE_SIZE];")?;
    writeln!(
        code,
        "    let mut gate_act = vec![0.0f32; INTERMEDIATE_SIZE];"
    )?;
    writeln!(code, "    let mut up = vec![0.0f32; INTERMEDIATE_SIZE];")?;
    writeln!(
        code,
        "    let mut ffn_hidden = vec![0.0f32; INTERMEDIATE_SIZE];"
    )?;
    writeln!(code, "    let mut ffn_out = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code)?;

    // Transformer layers
    writeln!(code, "    // Transformer layers")?;
    writeln!(code, "    for layer_idx in 0..NUM_LAYERS {{")?;
    writeln!(code, "        let lw = &weights.layers[layer_idx];")?;
    writeln!(code)?;
    writeln!(code, "        // Attention norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &hidden_state, &lw.attn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // QKV projections")?;
    writeln!(
        code,
        "        matmul(&mut q, &normed, &lw.q_proj, 1, HIDDEN_SIZE, NUM_HEADS * HEAD_DIM);"
    )?;
    writeln!(
        code,
        "        matmul(&mut k, &normed, &lw.k_proj, 1, HIDDEN_SIZE, NUM_KV_HEADS * HEAD_DIM);"
    )?;
    writeln!(
        code,
        "        matmul(&mut v, &normed, &lw.v_proj, 1, HIDDEN_SIZE, NUM_KV_HEADS * HEAD_DIM);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // RoPE")?;
    writeln!(
        code,
        "        rope(&mut q, pos, HEAD_DIM, NUM_HEADS, ROPE_THETA);"
    )?;
    writeln!(
        code,
        "        rope(&mut k, pos, HEAD_DIM, NUM_KV_HEADS, ROPE_THETA);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // Update KV cache")?;
    writeln!(code, "        cache.k[layer_idx].extend_from_slice(&k);")?;
    writeln!(code, "        cache.v[layer_idx].extend_from_slice(&v);")?;
    writeln!(code)?;
    writeln!(code, "        // Attention")?;
    writeln!(code, "        attention(")?;
    writeln!(code, "            &mut attn_out, &q,")?;
    writeln!(
        code,
        "            &cache.k[layer_idx], &cache.v[layer_idx],"
    )?;
    writeln!(
        code,
        "            pos + 1, NUM_HEADS, NUM_KV_HEADS, HEAD_DIM,"
    )?;
    writeln!(code, "        );")?;
    writeln!(code)?;
    writeln!(code, "        // Output projection + residual")?;
    writeln!(code, "        matmul(&mut attn_proj, &attn_out, &lw.o_proj, 1, NUM_HEADS * HEAD_DIM, HIDDEN_SIZE);")?;
    writeln!(
        code,
        "        elementwise_add(&mut residual, &hidden_state, &attn_proj);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // FFN norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &residual, &lw.ffn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        // FFN: gate_proj -> SiLU, up_proj, multiply, down_proj"
    )?;
    writeln!(
        code,
        "        matmul(&mut gate, &normed, &lw.gate_proj, 1, HIDDEN_SIZE, INTERMEDIATE_SIZE);"
    )?;
    writeln!(code, "        silu(&mut gate_act, &gate);")?;
    writeln!(
        code,
        "        matmul(&mut up, &normed, &lw.up_proj, 1, HIDDEN_SIZE, INTERMEDIATE_SIZE);"
    )?;
    writeln!(
        code,
        "        elementwise_mul(&mut ffn_hidden, &gate_act, &up);"
    )?;
    writeln!(code, "        matmul(&mut ffn_out, &ffn_hidden, &lw.down_proj, 1, INTERMEDIATE_SIZE, HIDDEN_SIZE);")?;
    writeln!(code)?;
    writeln!(code, "        // Residual")?;
    writeln!(
        code,
        "        elementwise_add(&mut hidden_state, &residual, &ffn_out);"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;

    // Final norm + logits
    writeln!(code, "    // Final norm")?;
    writeln!(
        code,
        "    rms_norm(&mut normed, &hidden_state, &weights.final_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "    // Logits projection")?;
    writeln!(code, "    let mut logits = vec![0.0f32; VOCAB_SIZE];")?;
    writeln!(
        code,
        "    matmul(&mut logits, &normed, &weights.lm_head, 1, HIDDEN_SIZE, VOCAB_SIZE);"
    )?;
    writeln!(code)?;
    writeln!(code, "    cache.len += 1;")?;
    writeln!(code, "    logits")?;
    writeln!(code, "}}")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::graph_builder;

    fn tiny_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 2,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 64,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        }
    }

    #[test]
    fn generate_code_from_tiny_model() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 64;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 2;"));
        assert!(code.contains("pub const VOCAB_SIZE: usize = 256;"));
        assert!(code.contains("fn rms_norm("));
        assert!(code.contains("fn matmul("));
        assert!(code.contains("fn forward("));
        assert!(code.contains("fn attention("));
    }

    #[test]
    fn generated_code_has_correct_structure() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Should have weight structs
        assert!(code.contains("pub struct Weights"));
        assert!(code.contains("pub struct LayerWeights"));
        assert!(code.contains("pub struct KVCache"));

        // Should have all kernel functions
        assert!(code.contains("pub fn silu("));
        assert!(code.contains("pub fn softmax("));
        assert!(code.contains("pub fn rope("));
        assert!(code.contains("pub fn embedding("));
        assert!(code.contains("pub fn elementwise_mul("));
        assert!(code.contains("pub fn elementwise_add("));
    }

    #[test]
    fn generate_code_for_llama_1b() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 2048,
            intermediate_size: 5632,
            num_layers: 16,
            num_attention_heads: 32,
            num_kv_heads: 8,
            head_dim: 64,
            vocab_size: 32000,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 2048;"));
        assert!(code.contains("pub const NUM_HEADS: usize = 32;"));
        assert!(code.contains("pub const NUM_KV_HEADS: usize = 8;"));
    }

    #[test]
    fn generate_code_for_smollm() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 576,
            intermediate_size: 1536,
            num_layers: 30,
            num_attention_heads: 9,
            num_kv_heads: 3,
            head_dim: 64,
            vocab_size: 49152,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::BF16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 576;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 30;"));
    }

    #[test]
    fn generated_code_compiles_as_rust() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Verify the generated code is valid Rust by checking syntax
        // (actual compilation test would require writing to file and running cargo)
        assert!(code.starts_with("//!"));
        assert!(!code.contains("TODO"));
        assert!(!code.contains("unimplemented"));

        // Check balanced braces
        let opens: usize = code.chars().filter(|&c| c == '{').count();
        let closes: usize = code.chars().filter(|&c| c == '}').count();
        assert_eq!(opens, closes, "unbalanced braces in generated code");
    }

    #[test]
    fn graph_without_config_errors() {
        let graph = Graph::new("no-config");
        let result = generate(&graph);
        assert!(matches!(result, Err(CodegenError::MissingConfig)));
    }
}
