//! Rust source code emission from IR graphs.
//!
//! Generates a complete Rust module containing:
//! - Typed buffer declarations for all intermediate tensors
//! - Specialized kernel functions for each operation
//! - A `forward()` function that chains all operations
//!
//! The generated code operates on flat f32 slices — no dynamic shapes.

use std::fmt::Write;

use forgellm_frontend::ir::*;

/// Generate Rust source code from a computation graph.
///
/// Returns a string containing a complete Rust module that implements
/// the model's forward pass. The generated code:
/// - Uses `&[f32]` for weight inputs (pre-loaded)
/// - Uses flat arrays for all intermediate buffers
/// - Has zero allocations during the forward pass
pub fn generate(graph: &Graph) -> Result<String, CodegenError> {
    let config = graph.config.as_ref().ok_or(CodegenError::MissingConfig)?;

    let mut code = String::with_capacity(32 * 1024);

    emit_header(&mut code, config)?;
    emit_kernel_functions(&mut code)?;
    emit_forward_function(&mut code, graph, config)?;

    Ok(code)
}

/// Errors during code generation.
#[derive(Debug, thiserror::Error)]
pub enum CodegenError {
    #[error("graph has no model config")]
    MissingConfig,

    #[error("unsupported operation for CPU codegen: {0}")]
    UnsupportedOp(String),

    #[error("format error: {0}")]
    Fmt(#[from] std::fmt::Error),
}

fn emit_header(code: &mut String, config: &ModelConfig) -> Result<(), CodegenError> {
    writeln!(code, "//! Auto-generated by ForgeLLM CPU codegen.")?;
    writeln!(
        code,
        "//! Model: {} ({} layers, hidden={})",
        config.architecture, config.num_layers, config.hidden_size
    )?;
    writeln!(code, "//!")?;
    writeln!(
        code,
        "//! This code has no dynamic dispatch — all dimensions are baked in."
    )?;
    writeln!(code)?;
    writeln!(code, "#![allow(clippy::excessive_precision)]")?;
    writeln!(code)?;
    writeln!(code, "// Model constants")?;
    writeln!(
        code,
        "pub const HIDDEN_SIZE: usize = {};",
        config.hidden_size
    )?;
    writeln!(
        code,
        "pub const INTERMEDIATE_SIZE: usize = {};",
        config.intermediate_size
    )?;
    writeln!(code, "pub const NUM_LAYERS: usize = {};", config.num_layers)?;
    writeln!(
        code,
        "pub const NUM_HEADS: usize = {};",
        config.num_attention_heads
    )?;
    writeln!(
        code,
        "pub const NUM_KV_HEADS: usize = {};",
        config.num_kv_heads
    )?;
    writeln!(code, "pub const HEAD_DIM: usize = {};", config.head_dim)?;
    writeln!(code, "pub const VOCAB_SIZE: usize = {};", config.vocab_size)?;
    writeln!(
        code,
        "pub const MAX_SEQ_LEN: usize = {};",
        config.max_seq_len
    )?;
    writeln!(
        code,
        "pub const RMS_NORM_EPS: f32 = {:e};",
        config.rms_norm_eps
    )?;
    writeln!(code, "pub const ROPE_THETA: f32 = {:e};", config.rope_theta)?;
    writeln!(code)?;
    Ok(())
}

fn emit_kernel_functions(code: &mut String) -> Result<(), CodegenError> {
    // Emit all kernels as a template string — includes NEON SIMD with scalar fallback
    code.push_str(
        r#"
// --- NEON SIMD dot product ---
#[cfg(target_arch = "aarch64")]
#[inline]
fn dot_f32(a: &[f32], b: &[f32], len: usize) -> f32 {
    use std::arch::aarch64::*;
    unsafe {
        let mut s0 = vdupq_n_f32(0.0);
        let mut s1 = vdupq_n_f32(0.0);
        let chunks = len / 8;
        for i in 0..chunks {
            let base = i * 8;
            s0 = vfmaq_f32(s0, vld1q_f32(a.as_ptr().add(base)), vld1q_f32(b.as_ptr().add(base)));
            s1 = vfmaq_f32(s1, vld1q_f32(a.as_ptr().add(base+4)), vld1q_f32(b.as_ptr().add(base+4)));
        }
        let mut r = vaddvq_f32(vaddq_f32(s0, s1));
        for i in (chunks*8)..len { r += *a.get_unchecked(i) * *b.get_unchecked(i); }
        r
    }
}

#[cfg(not(target_arch = "aarch64"))]
#[inline]
fn dot_f32(a: &[f32], b: &[f32], len: usize) -> f32 {
    let mut sum = 0.0f32;
    for i in 0..len { sum += a[i] * b[i]; }
    sum
}

/// RMS normalization with NEON dot product
#[inline]
pub fn rms_norm(output: &mut [f32], input: &[f32], weight: &[f32], eps: f32) {
    let n = input.len();
    let sum_sq = dot_f32(input, input, n);
    let inv_rms = 1.0 / (sum_sq / n as f32 + eps).sqrt();
    for i in 0..n { output[i] = input[i] * inv_rms * weight[i]; }
}

/// Matrix multiply with NEON dot product per output element
#[inline]
pub fn matmul(output: &mut [f32], input: &[f32], weight: &[f32], m: usize, k: usize, n: usize) {
    for i in 0..m {
        let row = &input[i*k..(i+1)*k];
        for j in 0..n {
            output[i*n+j] = dot_f32(row, &weight[j*k..(j+1)*k], k);
        }
    }
}

"#,
    );

    // Remaining kernels as template string
    code.push_str(
        r#"#[inline]
pub fn silu(output: &mut [f32], input: &[f32]) {
    for (o, &x) in output.iter_mut().zip(input.iter()) { *o = x / (1.0 + (-x).exp()); }
}

#[inline]
pub fn elementwise_mul(output: &mut [f32], a: &[f32], b: &[f32]) {
    for i in 0..a.len() { output[i] = a[i] * b[i]; }
}

#[inline]
pub fn elementwise_add(output: &mut [f32], a: &[f32], b: &[f32]) {
    for i in 0..a.len() { output[i] = a[i] + b[i]; }
}

#[inline]
pub fn softmax(values: &mut [f32]) {
    let max_val = values.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for v in values.iter_mut() { *v = (*v - max_val).exp(); sum += *v; }
    let inv = 1.0 / sum;
    for v in values.iter_mut() { *v *= inv; }
}

#[inline]
pub fn rope(data: &mut [f32], pos: usize, head_dim: usize, num_heads: usize, theta: f32) {
    for h in 0..num_heads {
        let off = h * head_dim;
        for i in (0..head_dim).step_by(2) {
            let freq = 1.0 / theta.powf(i as f32 / head_dim as f32);
            let angle = pos as f32 * freq;
            let (sin_v, cos_v) = angle.sin_cos();
            let (x0, x1) = (data[off+i], data[off+i+1]);
            data[off+i] = x0 * cos_v - x1 * sin_v;
            data[off+i+1] = x0 * sin_v + x1 * cos_v;
        }
    }
}

#[inline]
pub fn attention(output: &mut [f32], q: &[f32], k_cache: &[f32], v_cache: &[f32],
    seq_len: usize, num_heads: usize, num_kv_heads: usize, head_dim: usize) {
    let gsize = num_heads / num_kv_heads;
    let scale = 1.0 / (head_dim as f32).sqrt();
    let kv_stride = num_kv_heads * head_dim;
    for h in 0..num_heads {
        let kv_h = h / gsize;
        let qo = h * head_dim;
        let mut scores = vec![0.0f32; seq_len];
        for t in 0..seq_len {
            let ko = t * kv_stride + kv_h * head_dim;
            scores[t] = dot_f32(&q[qo..qo+head_dim], &k_cache[ko..ko+head_dim], head_dim) * scale;
        }
        softmax(&mut scores);
        for d in 0..head_dim {
            let mut sum = 0.0f32;
            for t in 0..seq_len {
                sum += scores[t] * v_cache[t * kv_stride + kv_h * head_dim + d];
            }
            output[qo+d] = sum;
        }
    }
}

#[inline]
pub fn embedding(output: &mut [f32], token_id: u32, weight: &[f32], embed_dim: usize) {
    let off = token_id as usize * embed_dim;
    output.copy_from_slice(&weight[off..off + embed_dim]);
}

"#,
    );

    Ok(())
}

fn emit_forward_function(
    code: &mut String,
    _graph: &Graph,
    config: &ModelConfig,
) -> Result<(), CodegenError> {
    let hidden = config.hidden_size;
    let intermediate = config.intermediate_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let vocab = config.vocab_size;

    writeln!(
        code,
        "/// Model weights — loaded once, passed to forward()."
    )?;
    writeln!(code, "pub struct Weights {{")?;
    writeln!(
        code,
        "    pub embed_tokens: Vec<f32>,       // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "    pub layers: Vec<LayerWeights>,")?;
    writeln!(code, "    pub final_norm: Vec<f32>,          // [{hidden}]")?;
    writeln!(
        code,
        "    pub lm_head: Vec<f32>,             // [{vocab} * {hidden}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "pub struct LayerWeights {{")?;
    writeln!(code, "    pub attn_norm: Vec<f32>,           // [{hidden}]")?;
    writeln!(
        code,
        "    pub q_proj: Vec<f32>,              // [{} * {hidden}]",
        num_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub k_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub v_proj: Vec<f32>,              // [{} * {hidden}]",
        num_kv_heads * head_dim
    )?;
    writeln!(
        code,
        "    pub o_proj: Vec<f32>,              // [{hidden} * {}]",
        num_heads * head_dim
    )?;
    writeln!(code, "    pub ffn_norm: Vec<f32>,            // [{hidden}]")?;
    writeln!(
        code,
        "    pub gate_proj: Vec<f32>,           // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub up_proj: Vec<f32>,             // [{intermediate} * {hidden}]"
    )?;
    writeln!(
        code,
        "    pub down_proj: Vec<f32>,           // [{hidden} * {intermediate}]"
    )?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "/// KV cache for autoregressive generation.")?;
    writeln!(code, "pub struct KVCache {{")?;
    writeln!(
        code,
        "    pub k: Vec<Vec<f32>>,  // [num_layers][seq_len * {} * {}]",
        num_kv_heads, head_dim
    )?;
    writeln!(
        code,
        "    pub v: Vec<Vec<f32>>,  // [num_layers][seq_len * {} * {}]",
        num_kv_heads, head_dim
    )?;
    writeln!(code, "    pub len: usize,")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    writeln!(code, "impl KVCache {{")?;
    writeln!(code, "    pub fn new() -> Self {{")?;
    writeln!(code, "        Self {{")?;
    writeln!(
        code,
        "            k: (0..NUM_LAYERS).map(|_| Vec::new()).collect(),"
    )?;
    writeln!(
        code,
        "            v: (0..NUM_LAYERS).map(|_| Vec::new()).collect(),"
    )?;
    writeln!(code, "            len: 0,")?;
    writeln!(code, "        }}")?;
    writeln!(code, "    }}")?;
    writeln!(code, "}}")?;
    writeln!(code)?;

    // Forward function for single token (generation mode)
    writeln!(
        code,
        "/// Run forward pass for a single token. Returns logits [{vocab}]."
    )?;
    writeln!(
        code,
        "pub fn forward(token_id: u32, weights: &Weights, cache: &mut KVCache) -> Vec<f32> {{"
    )?;
    writeln!(code, "    let pos = cache.len;")?;
    writeln!(code)?;

    // Embedding
    writeln!(code, "    // Embedding lookup")?;
    writeln!(
        code,
        "    let mut hidden_state = vec![0.0f32; HIDDEN_SIZE];"
    )?;
    writeln!(
        code,
        "    embedding(&mut hidden_state, token_id, &weights.embed_tokens, HIDDEN_SIZE);"
    )?;
    writeln!(code)?;

    // Buffers
    writeln!(code, "    // Pre-allocate buffers")?;
    writeln!(code, "    let mut normed = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut q = vec![0.0f32; NUM_HEADS * HEAD_DIM];")?;
    writeln!(
        code,
        "    let mut k = vec![0.0f32; NUM_KV_HEADS * HEAD_DIM];"
    )?;
    writeln!(
        code,
        "    let mut v = vec![0.0f32; NUM_KV_HEADS * HEAD_DIM];"
    )?;
    writeln!(
        code,
        "    let mut attn_out = vec![0.0f32; NUM_HEADS * HEAD_DIM];"
    )?;
    writeln!(code, "    let mut attn_proj = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut residual = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code, "    let mut gate = vec![0.0f32; INTERMEDIATE_SIZE];")?;
    writeln!(
        code,
        "    let mut gate_act = vec![0.0f32; INTERMEDIATE_SIZE];"
    )?;
    writeln!(code, "    let mut up = vec![0.0f32; INTERMEDIATE_SIZE];")?;
    writeln!(
        code,
        "    let mut ffn_hidden = vec![0.0f32; INTERMEDIATE_SIZE];"
    )?;
    writeln!(code, "    let mut ffn_out = vec![0.0f32; HIDDEN_SIZE];")?;
    writeln!(code)?;

    // Transformer layers
    writeln!(code, "    // Transformer layers")?;
    writeln!(code, "    for layer_idx in 0..NUM_LAYERS {{")?;
    writeln!(code, "        let lw = &weights.layers[layer_idx];")?;
    writeln!(code)?;
    writeln!(code, "        // Attention norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &hidden_state, &lw.attn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // QKV projections")?;
    writeln!(
        code,
        "        matmul(&mut q, &normed, &lw.q_proj, 1, HIDDEN_SIZE, NUM_HEADS * HEAD_DIM);"
    )?;
    writeln!(
        code,
        "        matmul(&mut k, &normed, &lw.k_proj, 1, HIDDEN_SIZE, NUM_KV_HEADS * HEAD_DIM);"
    )?;
    writeln!(
        code,
        "        matmul(&mut v, &normed, &lw.v_proj, 1, HIDDEN_SIZE, NUM_KV_HEADS * HEAD_DIM);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // RoPE")?;
    writeln!(
        code,
        "        rope(&mut q, pos, HEAD_DIM, NUM_HEADS, ROPE_THETA);"
    )?;
    writeln!(
        code,
        "        rope(&mut k, pos, HEAD_DIM, NUM_KV_HEADS, ROPE_THETA);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // Update KV cache")?;
    writeln!(code, "        cache.k[layer_idx].extend_from_slice(&k);")?;
    writeln!(code, "        cache.v[layer_idx].extend_from_slice(&v);")?;
    writeln!(code)?;
    writeln!(code, "        // Attention")?;
    writeln!(code, "        attention(")?;
    writeln!(code, "            &mut attn_out, &q,")?;
    writeln!(
        code,
        "            &cache.k[layer_idx], &cache.v[layer_idx],"
    )?;
    writeln!(
        code,
        "            pos + 1, NUM_HEADS, NUM_KV_HEADS, HEAD_DIM,"
    )?;
    writeln!(code, "        );")?;
    writeln!(code)?;
    writeln!(code, "        // Output projection + residual")?;
    writeln!(code, "        matmul(&mut attn_proj, &attn_out, &lw.o_proj, 1, NUM_HEADS * HEAD_DIM, HIDDEN_SIZE);")?;
    writeln!(
        code,
        "        elementwise_add(&mut residual, &hidden_state, &attn_proj);"
    )?;
    writeln!(code)?;
    writeln!(code, "        // FFN norm")?;
    writeln!(
        code,
        "        rms_norm(&mut normed, &residual, &lw.ffn_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(
        code,
        "        // FFN: gate_proj -> SiLU, up_proj, multiply, down_proj"
    )?;
    writeln!(
        code,
        "        matmul(&mut gate, &normed, &lw.gate_proj, 1, HIDDEN_SIZE, INTERMEDIATE_SIZE);"
    )?;
    writeln!(code, "        silu(&mut gate_act, &gate);")?;
    writeln!(
        code,
        "        matmul(&mut up, &normed, &lw.up_proj, 1, HIDDEN_SIZE, INTERMEDIATE_SIZE);"
    )?;
    writeln!(
        code,
        "        elementwise_mul(&mut ffn_hidden, &gate_act, &up);"
    )?;
    writeln!(code, "        matmul(&mut ffn_out, &ffn_hidden, &lw.down_proj, 1, INTERMEDIATE_SIZE, HIDDEN_SIZE);")?;
    writeln!(code)?;
    writeln!(code, "        // Residual")?;
    writeln!(
        code,
        "        elementwise_add(&mut hidden_state, &residual, &ffn_out);"
    )?;
    writeln!(code, "    }}")?;
    writeln!(code)?;

    // Final norm + logits
    writeln!(code, "    // Final norm")?;
    writeln!(
        code,
        "    rms_norm(&mut normed, &hidden_state, &weights.final_norm, RMS_NORM_EPS);"
    )?;
    writeln!(code)?;
    writeln!(code, "    // Logits projection")?;
    writeln!(code, "    let mut logits = vec![0.0f32; VOCAB_SIZE];")?;
    writeln!(
        code,
        "    matmul(&mut logits, &normed, &weights.lm_head, 1, HIDDEN_SIZE, VOCAB_SIZE);"
    )?;
    writeln!(code)?;
    writeln!(code, "    cache.len += 1;")?;
    writeln!(code, "    logits")?;
    writeln!(code, "}}")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::graph_builder;

    fn tiny_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 2,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 64,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        }
    }

    #[test]
    fn generate_code_from_tiny_model() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 64;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 2;"));
        assert!(code.contains("pub const VOCAB_SIZE: usize = 256;"));
        assert!(code.contains("fn rms_norm("));
        assert!(code.contains("fn matmul("));
        assert!(code.contains("fn forward("));
        assert!(code.contains("fn attention("));
    }

    #[test]
    fn generated_code_has_correct_structure() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Should have weight structs
        assert!(code.contains("pub struct Weights"));
        assert!(code.contains("pub struct LayerWeights"));
        assert!(code.contains("pub struct KVCache"));

        // Should have all kernel functions
        assert!(code.contains("pub fn silu("));
        assert!(code.contains("pub fn softmax("));
        assert!(code.contains("pub fn rope("));
        assert!(code.contains("pub fn embedding("));
        assert!(code.contains("pub fn elementwise_mul("));
        assert!(code.contains("pub fn elementwise_add("));
    }

    #[test]
    fn generate_code_for_llama_1b() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 2048,
            intermediate_size: 5632,
            num_layers: 16,
            num_attention_heads: 32,
            num_kv_heads: 8,
            head_dim: 64,
            vocab_size: 32000,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 2048;"));
        assert!(code.contains("pub const NUM_HEADS: usize = 32;"));
        assert!(code.contains("pub const NUM_KV_HEADS: usize = 8;"));
    }

    #[test]
    fn generate_code_for_smollm() {
        let config = ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 576,
            intermediate_size: 1536,
            num_layers: 30,
            num_attention_heads: 9,
            num_kv_heads: 3,
            head_dim: 64,
            vocab_size: 49152,
            max_seq_len: 2048,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::BF16,
        };

        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        assert!(code.contains("pub const HIDDEN_SIZE: usize = 576;"));
        assert!(code.contains("pub const NUM_LAYERS: usize = 30;"));
    }

    #[test]
    fn generated_code_compiles_as_rust() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let code = generate(&graph).unwrap();

        // Verify the generated code is valid Rust by checking syntax
        // (actual compilation test would require writing to file and running cargo)
        assert!(code.starts_with("//!"));
        assert!(!code.contains("TODO"));
        assert!(!code.contains("unimplemented"));

        // Check balanced braces
        let opens: usize = code.chars().filter(|&c| c == '{').count();
        let closes: usize = code.chars().filter(|&c| c == '}').count();
        assert_eq!(opens, closes, "unbalanced braces in generated code");
    }

    #[test]
    fn graph_without_config_errors() {
        let graph = Graph::new("no-config");
        let result = generate(&graph);
        assert!(matches!(result, Err(CodegenError::MissingConfig)));
    }
}
