//! Generate a complete Cargo project from a computation graph.
//!
//! Creates a directory structure with:
//! - Cargo.toml (with tokenizers dependency)
//! - src/model.rs (kernels + forward function)
//! - src/main.rs (weight loader + tokenizer + generation loop)

use std::fs;
use std::path::Path;

use forgellm_frontend::ir::*;

use crate::emit;

/// Generate a complete Cargo project from a computation graph.
pub fn generate_project(
    graph: &Graph,
    output_dir: &Path,
    model_name: &str,
    embed_weights: bool,
) -> Result<(), ProjectError> {
    let config = graph
        .config
        .as_ref()
        .ok_or(ProjectError::Codegen(emit::CodegenError::MissingConfig))?;

    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(ProjectError::Io)?;

    // Generate model.rs
    let model_code = emit::generate(graph).map_err(ProjectError::Codegen)?;
    fs::write(src_dir.join("model.rs"), &model_code).map_err(ProjectError::Io)?;

    // Generate Cargo.toml
    fs::write(
        output_dir.join("Cargo.toml"),
        generate_cargo_toml(model_name),
    )
    .map_err(ProjectError::Io)?;

    // Generate .cargo/config.toml (enables native CPU features like dotprod on M1)
    let cargo_config_dir = output_dir.join(".cargo");
    fs::create_dir_all(&cargo_config_dir).map_err(ProjectError::Io)?;
    fs::write(cargo_config_dir.join("config.toml"), CARGO_CONFIG).map_err(ProjectError::Io)?;

    // Generate main.rs
    let main_code = if embed_weights {
        generate_main_embedded(config)
    } else {
        generate_main(config)
    };
    fs::write(src_dir.join("main.rs"), main_code).map_err(ProjectError::Io)?;

    Ok(())
}

/// Generate a Cargo library crate from a computation graph (for speculative decoding).
///
/// Same as `generate_project` but produces a `[lib]` crate with `src/lib.rs` that
/// re-exports `pub mod model;`.  No binary entry point is generated.
pub fn generate_project_as_lib(
    graph: &Graph,
    output_dir: &Path,
    lib_name: &str,
) -> Result<(), ProjectError> {
    // Validate config exists (reuses same check)
    let _ = graph
        .config
        .as_ref()
        .ok_or(ProjectError::Codegen(emit::CodegenError::MissingConfig))?;

    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(ProjectError::Io)?;

    // Generate model.rs
    let model_code = emit::generate(graph).map_err(ProjectError::Codegen)?;
    fs::write(src_dir.join("model.rs"), &model_code).map_err(ProjectError::Io)?;

    // Generate Cargo.toml with [lib] section
    fs::write(
        output_dir.join("Cargo.toml"),
        generate_lib_cargo_toml(lib_name),
    )
    .map_err(ProjectError::Io)?;

    // Generate lib.rs that re-exports model
    let lib_code = "//! AOT-compiled model library generated by ForgeLLM.\n//! Re-exports the model module for use in speculative decoding runners.\n\npub mod model;\n";
    fs::write(src_dir.join("lib.rs"), lib_code).map_err(ProjectError::Io)?;

    Ok(())
}

/// Generated .cargo/config.toml that enables native CPU features (e.g., dotprod on M1).
/// `target-cpu=native` lets the compiler emit vdotq_s32 / AVX-512 / AMX instructions
/// that are available on the build machine, maximizing inference throughput.
const CARGO_CONFIG: &str = r#"# Generated by ForgeLLM — enables native CPU features for maximum inference throughput.
[build]
rustflags = ["-C", "target-cpu=native"]
"#;

fn generate_lib_cargo_toml(lib_name: &str) -> String {
    let sanitized = lib_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string();

    format!(
        r#"[package]
name = "{sanitized}"
version = "0.1.0"
edition = "2021"
description = "AOT-compiled LLM library generated by ForgeLLM"

[lib]
name = "{sanitized}"

[dependencies]
rayon = "1.10"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn generate_cargo_toml(model_name: &str) -> String {
    let sanitized = model_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string();

    format!(
        r#"[package]
name = "{sanitized}"
version = "0.1.0"
edition = "2021"
description = "AOT-compiled LLM inference binary generated by ForgeLLM"

[dependencies]
tokenizers = {{ version = "0.21", default-features = false, features = ["onig"] }}
rayon = "1.10"
memmap2 = "0.9"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn generate_main(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let _arch_lower = arch.to_lowercase();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;
    let is_q8 = config.dtype == DType::Q8_0;
    let is_q4 = config.dtype == DType::Q4_0;
    let is_q4k = config.dtype == DType::Q4_K;
    // lm_head may use a different dtype than projections — compute its byte
    // size separately (Q4_K_M → Q4_K proj + Q8_0 lm_head is the common case).
    let lm_dtype = config.lm_head_dtype.unwrap_or(config.dtype);
    let lm_is_q8 = lm_dtype == DType::Q8_0;
    let lm_is_q4k = lm_dtype == DType::Q4_K;

    // Pre-compute row byte sizes per dtype.
    let q8_row_bytes = |numel: usize| -> usize { numel.div_ceil(32) * 34 };
    let q4_row_bytes = |numel: usize| -> usize { numel.div_ceil(32) * 18 };
    // Q4_K: 144 bytes per 256-element super-block.
    let q4k_row_bytes = |numel: usize| -> usize { numel.div_ceil(256) * 144 };

    // Byte sizes for projection weight tensors (Q8_0 / Q4_0 / Q4_K).
    let proj_row_bytes: fn(usize) -> usize = if is_q4k {
        |n| n.div_ceil(256) * 144
    } else if is_q8 {
        |n| n.div_ceil(32) * 34
    } else {
        |n| n.div_ceil(32) * 18
    };
    let (qp_bytes, kp_bytes, vp_bytes, op_bytes, gp_bytes, up_bytes, dp_bytes) = (
        qk_size * proj_row_bytes(hidden),
        kv_size * proj_row_bytes(hidden),
        kv_size * proj_row_bytes(hidden),
        hidden * proj_row_bytes(qk_size),
        inter * proj_row_bytes(hidden),
        inter * proj_row_bytes(hidden),
        hidden * proj_row_bytes(inter),
    );
    // lm_head byte size depends on lm_head_dtype, not projection dtype.
    let lmh_bytes = if lm_is_q8 {
        vocab * q8_row_bytes(hidden)
    } else if lm_is_q4k {
        vocab * q4k_row_bytes(hidden)
    } else {
        vocab * q4_row_bytes(hidden)
    };

    let weight_loading_code = if is_q8 || is_q4 || is_q4k {
        // Quantized: load raw bytes; norm/embed are still f32
        r##"fn load_weights_raw(path: &str) -> Vec<u8> {
    let file = std::fs::File::open(path).expect("failed to open weights");
    let mmap = unsafe { memmap2::Mmap::map(&file) }.expect("failed to mmap weights");
    mmap.to_vec()
}
"##
        .to_string()
    } else {
        r##"fn load_weights(path: &str) -> Vec<f32> {
    let file = std::fs::File::open(path).expect("failed to open weights");
    let mmap = unsafe { memmap2::Mmap::map(&file) }.expect("failed to mmap weights");
    // Fast path: direct memcpy from mmap to f32 Vec (assumes little-endian, aligned)
    let n = mmap.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {
        std::ptr::copy_nonoverlapping(
            mmap.as_ptr() as *const f32,
            out.as_mut_ptr(),
            n,
        );
        out.set_len(n);
    }
    out
}
"##
        .to_string()
    };

    let weight_slice_code = if is_q8 || is_q4 || is_q4k {
        // Quantized: byte offsets for projection weights, f32 element offsets for norm/embed
        let quant_label = if is_q8 {
            "Q8_0"
        } else if is_q4k {
            "Q4_K"
        } else {
            "Q4_0"
        };

        // Qwen2 QKV bias (F32) — read from weights.bin when enabled. Each bias
        // tensor has `num_heads * head_dim` (Q) or `num_kv_heads * head_dim` (K/V)
        // F32 elements, written by cmd_export_weights_impl immediately after the
        // corresponding projection weight.
        let (q_bias_read, k_bias_read, v_bias_read, layer_fields) = if config.qkv_bias {
            let q_bias_bytes = qk_size * 4;
            let kv_bias_bytes = kv_size * 4;
            (
                format!(
                    r##"        // Qwen2 Q projection bias: f32, interpreted from raw bytes
        let qb_bytes = {q_bias_bytes};
        let qb: Vec<f32> = {{
            let n = qb_bytes / 4;
            let mut v = Vec::<f32>::with_capacity(n);
            unsafe {{
                std::ptr::copy_nonoverlapping(w[boff..boff+qb_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
                v.set_len(n);
            }}
            v
        }};
        boff += qb_bytes;
"##
                ),
                format!(
                    r##"        // Qwen2 K projection bias: f32
        let kb_bytes = {kv_bias_bytes};
        let kb: Vec<f32> = {{
            let n = kb_bytes / 4;
            let mut v = Vec::<f32>::with_capacity(n);
            unsafe {{
                std::ptr::copy_nonoverlapping(w[boff..boff+kb_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
                v.set_len(n);
            }}
            v
        }};
        boff += kb_bytes;
"##
                ),
                format!(
                    r##"        // Qwen2 V projection bias: f32
        let vb_bytes = {kv_bias_bytes};
        let vb: Vec<f32> = {{
            let n = vb_bytes / 4;
            let mut v = Vec::<f32>::with_capacity(n);
            unsafe {{
                std::ptr::copy_nonoverlapping(w[boff..boff+vb_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
                v.set_len(n);
            }}
            v
        }};
        boff += vb_bytes;
"##
                ),
                ", q_bias: qb, k_bias: kb, v_bias: vb".to_string(),
            )
        } else {
            (String::new(), String::new(), String::new(), String::new())
        };

        format!(
            r##"    let w = load_weights_raw(weights_path);
    let mut boff = 0usize;  // byte offset into raw buffer

    // embed_tokens: f32, interpreted from raw bytes
    let embed_bytes = {vocab} * {hidden} * 4;
    let embed: Vec<f32> = {{
        let n = embed_bytes / 4;
        let mut v = Vec::<f32>::with_capacity(n);
        unsafe {{
            std::ptr::copy_nonoverlapping(w[boff..boff+embed_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
            v.set_len(n);
        }}
        v
    }};
    boff += embed_bytes;
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        // attn_norm: f32
        let an_bytes = {hidden} * 4;
        let an: Vec<f32> = {{
            let n = an_bytes / 4;
            let mut v = Vec::<f32>::with_capacity(n);
            unsafe {{
                std::ptr::copy_nonoverlapping(w[boff..boff+an_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
                v.set_len(n);
            }}
            v
        }};
        boff += an_bytes;
        // Projection weights: {quant_label} raw bytes (Q, K, V as a contiguous triplet)
        let qp = w[boff..boff+{qp_bytes}].to_vec(); boff += {qp_bytes};
        let kp = w[boff..boff+{kp_bytes}].to_vec(); boff += {kp_bytes};
        let vp = w[boff..boff+{vp_bytes}].to_vec(); boff += {vp_bytes};
{q_bias_read}{k_bias_read}{v_bias_read}        let op = w[boff..boff+{op_bytes}].to_vec(); boff += {op_bytes};
        // ffn_norm: f32
        let fn_bytes = {hidden} * 4;
        let fn_: Vec<f32> = {{
            let n = fn_bytes / 4;
            let mut v = Vec::<f32>::with_capacity(n);
            unsafe {{
                std::ptr::copy_nonoverlapping(w[boff..boff+fn_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
                v.set_len(n);
            }}
            v
        }};
        boff += fn_bytes;
        let gp = w[boff..boff+{gp_bytes}].to_vec(); boff += {gp_bytes};
        let up = w[boff..boff+{up_bytes}].to_vec(); boff += {up_bytes};
        let dp = w[boff..boff+{dp_bytes}].to_vec(); boff += {dp_bytes};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp{layer_fields} }});
    }}
    // final_norm: f32
    let fnorm_bytes = {hidden} * 4;
    let fnorm: Vec<f32> = {{
        let n = fnorm_bytes / 4;
        let mut v = Vec::<f32>::with_capacity(n);
        unsafe {{
            std::ptr::copy_nonoverlapping(w[boff..boff+fnorm_bytes].as_ptr() as *const f32, v.as_mut_ptr(), n);
            v.set_len(n);
        }}
        v
    }};
    boff += fnorm_bytes;
    // lm_head: {quant_label} raw bytes
    let lmh = w[boff..boff+{lmh_bytes}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};"##
        )
    } else {
        // Qwen2 QKV bias (F32) — f32 path. Each bias is qk_size or kv_size floats.
        let (q_bias_read, k_bias_read, v_bias_read, layer_fields) = if config.qkv_bias {
            (
                format!("        let qb = w[off..off+{qk_size}].to_vec(); off += {qk_size};\n"),
                format!("        let kb = w[off..off+{kv_size}].to_vec(); off += {kv_size};\n"),
                format!("        let vb = w[off..off+{kv_size}].to_vec(); off += {kv_size};\n"),
                ", q_bias: qb, k_bias: kb, v_bias: vb".to_string(),
            )
        } else {
            (String::new(), String::new(), String::new(), String::new())
        };
        format!(
            r##"    let w = load_weights(weights_path);
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
{q_bias_read}{k_bias_read}{v_bias_read}        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp{layer_fields} }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};"##
        )
    };

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})

mod model;

use std::env;
use std::io::Write;

{weight_loading_code}

fn save_kv_cache(path: &str, cache: &model::KVCache) {{
    let kv = {kv_size};
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(&(cache.len as u64).to_le_bytes());
    // Save int8 K/V data
    for layer in &cache.k {{
        for &val in &layer[..cache.len * kv] {{ data.push(val as u8); }}
    }}
    for layer in &cache.v {{
        for &val in &layer[..cache.len * kv] {{ data.push(val as u8); }}
    }}
    // Save per-token scales
    for layer in &cache.k_scales {{
        for &val in &layer[..cache.len] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    for layer in &cache.v_scales {{
        for &val in &layer[..cache.len] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    std::fs::write(path, &data).expect("failed to save cache");
    eprintln!("KV cache saved ({{}} positions, int8)", cache.len);
}}

fn load_kv_cache(path: &str, cache: &mut model::KVCache) {{
    let kv = {kv_size};
    let data = std::fs::read(path).expect("failed to read cache");
    let len = u64::from_le_bytes(data[0..8].try_into().unwrap()) as usize;
    let mut off = 8;
    // Load int8 K/V data
    for layer in &mut cache.k {{
        for i in 0..len * kv {{ layer[i] = data[off] as i8; off += 1; }}
    }}
    for layer in &mut cache.v {{
        for i in 0..len * kv {{ layer[i] = data[off] as i8; off += 1; }}
    }}
    // Load per-token scales
    for layer in &mut cache.k_scales {{
        for i in 0..len {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    for layer in &mut cache.v_scales {{
        for i in 0..len {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    cache.len = len;
    eprintln!("KV cache loaded ({{}} positions, int8)", len);
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn apply_repeat_penalty(logits: &mut [f32], recent_tokens: &[u32], penalty: f32) {{
    if penalty <= 1.0 {{ return; }}
    for &tok in recent_tokens {{
        let idx = tok as usize;
        if idx < logits.len() {{
            if logits[idx] > 0.0 {{ logits[idx] /= penalty; }} else {{ logits[idx] *= penalty; }}
        }}
    }}
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, top_p: f32, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    // Apply temperature
    for l in logits.iter_mut() {{ *l /= temperature; }}
    // Softmax
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    // Sort indices by probability (descending)
    let mut indices: Vec<usize> = (0..logits.len()).collect();
    indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
    // Apply top-k
    if top_k > 0 && top_k < logits.len() {{
        for &idx in &indices[top_k..] {{ logits[idx] = 0.0; }}
    }}
    // Apply top-p (nucleus sampling)
    if top_p > 0.0 && top_p < 1.0 {{
        let mut cumsum = 0.0f32;
        for &idx in &indices {{
            cumsum += logits[idx];
            if cumsum > top_p {{
                logits[idx] = 0.0;
            }}
        }}
    }}
    // Renormalize
    sum = logits.iter().copied().sum();
    if sum > 0.0 {{ for l in logits.iter_mut() {{ *l /= sum; }} }}
    // Sample from distribution
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        // Compute weight count (per layer + embeddings + final norm + lm_head)
        let per_layer = model::HIDDEN_SIZE
            + model::HIDDEN_SIZE * model::NUM_HEADS * model::HEAD_DIM
            + 2 * model::HIDDEN_SIZE * model::NUM_KV_HEADS * model::HEAD_DIM
            + model::HIDDEN_SIZE * model::NUM_HEADS * model::HEAD_DIM
            + model::HIDDEN_SIZE
            + 3 * model::HIDDEN_SIZE * model::INTERMEDIATE_SIZE;
        let total_params = 2 * model::VOCAB_SIZE * model::HIDDEN_SIZE
            + model::NUM_LAYERS * per_layer
            + model::HIDDEN_SIZE;
        println!("  Parameters:   {{:.1}}M", (total_params as f64) / 1e6);
        println!("  Weights:      {{:.1}} MB (f32)", (total_params as f64 * 4.0) / 1e6);
        // Each forward pass does ~2*params multiply-add operations
        let flops_per_token = 2 * total_params;
        println!("  FLOPs/token:  {{:.2}} GFLOP", (flops_per_token as f64) / 1e9);
        // Compute KV cache size: int8 K+V data + f32 per-token scales
        let kv_data_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * model::NUM_KV_HEADS * model::HEAD_DIM * 1 * 2;
        let kv_scale_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * 4 * 2;
        let kv_bytes = kv_data_bytes + kv_scale_bytes;
        println!("  KV cache:     {{:.1}} MB (int8, max_seq_len={{}})", (kv_bytes as f64) / 1e6, model::MAX_SEQ_LEN);
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    if args.len() < 3 {{
        eprintln!("Usage: {{}} <weights.bin> <tokenizer.json> [prompt] [--temp T] [--top-k K] [--max-tokens N]", args[0]);
        eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden}");
        eprintln!("       {{}} --version", args[0]);
        std::process::exit(1);
    }}

    let weights_path = &args[1];
    let tokenizer_path = &args[2];
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let top_p = parse_f32_arg(&args, "--top-p", 0.9);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let repeat_penalty = parse_f32_arg(&args, "--repeat-penalty", 1.1);
    let seed = args.windows(2).find(|w| w[0] == "--seed").and_then(|w| w[1].parse::<u64>().ok()).unwrap_or(0xdeadbeef12345678);
    let quiet = args.iter().any(|a| a == "--quiet" || a == "-q");
    let save_cache_path = args.windows(2).find(|w| w[0] == "--save-cache").map(|w| w[1].clone());
    let load_cache_path = args.windows(2).find(|w| w[0] == "--load-cache").map(|w| w[1].clone());
    let prompt = args.iter().skip(3).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    let t_load = std::time::Instant::now();
    eprintln!("Loading tokenizer...");
    let tokenizer = tokenizers::Tokenizer::from_file(tokenizer_path).expect("failed to load tokenizer");

    eprintln!("Loading weights...");
{weight_slice_code}
    eprintln!("Load time: {{:.2}}s", t_load.elapsed().as_secs_f64());
    let mut cache = model::KVCache::new();
    if let Some(ref cp) = load_cache_path {{ load_kv_cache(cp, &mut cache); }}

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let prompt_tokens: Vec<u32> = enc.get_ids().to_vec();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", prompt_tokens.len(), temperature, top_k, max_tokens);

    // Prefill: process entire prompt in one batched pass, filling the KV cache
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = seed;
    let mut logits = model::forward_prefill(&prompt_tokens, &weights, &mut cache);
    let mut next = sample(&mut logits, temperature, top_k, top_p, &mut rng_state);
    eprintln!("Prefill: {{:.1}} tok/s", prompt_tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    if !quiet {{ print!("{{}}", prompt); }}
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut recent_tokens: Vec<u32> = prompt_tokens.clone();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        if !quiet {{
            let text = tokenizer.decode(&[next], true).unwrap_or_default();
            print!("{{}}", text);
            std::io::stdout().flush().ok();
        }}
        recent_tokens.push(next);
        let mut l = model::forward(next, &weights, &mut cache);
        apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
        next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
        gen_count += 1;
    }}
    if !quiet {{ println!(); }}
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
    if let Some(ref cp) = save_cache_path {{ save_kv_cache(cp, &cache); }}

    // Interactive chat mode
    if args.iter().any(|a| a == "--interactive" || a == "--chat") {{
        eprintln!("\n--- Interactive mode (type /quit to exit) ---");
        loop {{
            eprint!("> ");
            std::io::stderr().flush().ok();
            let mut input = String::new();
            if std::io::stdin().read_line(&mut input).is_err() || input.trim().is_empty() {{ continue; }}
            let input = input.trim();
            if input == "/quit" || input == "/exit" {{ break; }}
            if input == "/clear" {{
                cache.reset();
                recent_tokens.clear();
                eprintln!("Cache cleared.");
                continue;
            }}

            let enc2 = tokenizer.encode(input, false).expect("encode failed");
            let toks2: Vec<u32> = enc2.get_ids().to_vec();
            let mut l2 = model::forward_prefill(&toks2, &weights, &mut cache);
            next = sample(&mut l2, temperature, top_k, top_p, &mut rng_state);
            let t2 = std::time::Instant::now();
            let mut gen2 = 0usize;
            for _ in 0..max_tokens {{
                if eos_tokens.contains(&next) {{ break; }}
                let text = tokenizer.decode(&[next], true).unwrap_or_default();
                print!("{{}}", text);
                std::io::stdout().flush().ok();
                let mut l = model::forward(next, &weights, &mut cache);
                apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
                next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
                recent_tokens.push(next);
                gen2 += 1;
            }}
            println!();
            eprintln!("[{{}} tokens, {{:.1}} tok/s]", gen2, gen2 as f64 / t2.elapsed().as_secs_f64());
        }}
    }}
}}
"##
    )
}

fn generate_main_embedded(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;
    let is_q8 = config.dtype == DType::Q8_0;
    let is_q4 = config.dtype == DType::Q4_0;
    let is_q4k = config.dtype == DType::Q4_K;
    let lm_dtype = config.lm_head_dtype.unwrap_or(config.dtype);
    let lm_is_q8 = lm_dtype == DType::Q8_0;
    let lm_is_q4k = lm_dtype == DType::Q4_K;

    let q8_row_bytes = |numel: usize| -> usize { numel.div_ceil(32) * 34 };
    let q4_row_bytes = |numel: usize| -> usize { numel.div_ceil(32) * 18 };
    let q4k_row_bytes = |numel: usize| -> usize { numel.div_ceil(256) * 144 };
    let proj_row_bytes: fn(usize) -> usize = if is_q4k {
        |n| n.div_ceil(256) * 144
    } else if is_q8 {
        |n| n.div_ceil(32) * 34
    } else {
        |n| n.div_ceil(32) * 18
    };
    let (qp_bytes, kp_bytes, vp_bytes, op_bytes, gp_bytes, up_bytes, dp_bytes) = (
        qk_size * proj_row_bytes(hidden),
        kv_size * proj_row_bytes(hidden),
        kv_size * proj_row_bytes(hidden),
        hidden * proj_row_bytes(qk_size),
        inter * proj_row_bytes(hidden),
        inter * proj_row_bytes(hidden),
        hidden * proj_row_bytes(inter),
    );
    let lmh_bytes = if lm_is_q8 {
        vocab * q8_row_bytes(hidden)
    } else if lm_is_q4k {
        vocab * q4k_row_bytes(hidden)
    } else {
        vocab * q4_row_bytes(hidden)
    };

    let bytes_helper = if is_q8 || is_q4 || is_q4k {
        // For quantized models, we only need the bytes_to_f32 helper for norm/embed extraction
        r##"fn bytes_to_f32_slice(bytes: &[u8]) -> Vec<f32> {
    let n = bytes.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr() as *const f32, out.as_mut_ptr(), n);
        out.set_len(n);
    }
    out
}
"##
        .to_string()
    } else {
        r##"fn bytes_to_f32(bytes: &[u8]) -> Vec<f32> {
    let n = bytes.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr() as *const f32, out.as_mut_ptr(), n);
        out.set_len(n);
    }
    out
}
"##
        .to_string()
    };

    let quant_label = if is_q8 {
        "Q8_0"
    } else if is_q4k {
        "Q4_K"
    } else {
        "Q4_0"
    };

    let weight_slice_code_embedded = if is_q8 || is_q4 || is_q4k {
        format!(
            r##"    let w: &[u8] = WEIGHTS_BYTES;
    let mut boff = 0usize;

    let embed_bytes = {vocab} * {hidden} * 4;
    let embed = bytes_to_f32_slice(&w[boff..boff+embed_bytes]);
    boff += embed_bytes;
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an_bytes = {hidden} * 4;
        let an = bytes_to_f32_slice(&w[boff..boff+an_bytes]); boff += an_bytes;
        // Projection weights: {quant_label} raw bytes
        let qp = w[boff..boff+{qp_bytes}].to_vec(); boff += {qp_bytes};
        let kp = w[boff..boff+{kp_bytes}].to_vec(); boff += {kp_bytes};
        let vp = w[boff..boff+{vp_bytes}].to_vec(); boff += {vp_bytes};
        let op = w[boff..boff+{op_bytes}].to_vec(); boff += {op_bytes};
        let fn_bytes = {hidden} * 4;
        let fn_ = bytes_to_f32_slice(&w[boff..boff+fn_bytes]); boff += fn_bytes;
        let gp = w[boff..boff+{gp_bytes}].to_vec(); boff += {gp_bytes};
        let up = w[boff..boff+{up_bytes}].to_vec(); boff += {up_bytes};
        let dp = w[boff..boff+{dp_bytes}].to_vec(); boff += {dp_bytes};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm_bytes = {hidden} * 4;
    let fnorm = bytes_to_f32_slice(&w[boff..boff+fnorm_bytes]); boff += fnorm_bytes;
    // lm_head: {quant_label} raw bytes
    let lmh = w[boff..boff+{lmh_bytes}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};"##
        )
    } else {
        format!(
            r##"    let w = bytes_to_f32(WEIGHTS_BYTES);
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};"##
        )
    };

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})
//! Weights and tokenizer embedded via include_bytes! — single-file deployment.

mod model;

use std::env;
use std::io::Write;

static WEIGHTS_BYTES: &[u8] = include_bytes!("../weights.bin");
static TOKENIZER_BYTES: &[u8] = include_bytes!("../tokenizer.json");

{bytes_helper}

fn save_kv_cache(path: &str, cache: &model::KVCache) {{
    let kv = {kv_size};
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(&(cache.len as u64).to_le_bytes());
    // Save int8 K/V data
    for layer in &cache.k {{
        for &val in &layer[..cache.len * kv] {{ data.push(val as u8); }}
    }}
    for layer in &cache.v {{
        for &val in &layer[..cache.len * kv] {{ data.push(val as u8); }}
    }}
    // Save per-token scales
    for layer in &cache.k_scales {{
        for &val in &layer[..cache.len] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    for layer in &cache.v_scales {{
        for &val in &layer[..cache.len] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    std::fs::write(path, &data).expect("failed to save cache");
    eprintln!("KV cache saved ({{}} positions, int8)", cache.len);
}}

fn load_kv_cache(path: &str, cache: &mut model::KVCache) {{
    let kv = {kv_size};
    let data = std::fs::read(path).expect("failed to read cache");
    let len = u64::from_le_bytes(data[0..8].try_into().unwrap()) as usize;
    let mut off = 8;
    // Load int8 K/V data
    for layer in &mut cache.k {{
        for i in 0..len * kv {{ layer[i] = data[off] as i8; off += 1; }}
    }}
    for layer in &mut cache.v {{
        for i in 0..len * kv {{ layer[i] = data[off] as i8; off += 1; }}
    }}
    // Load per-token scales
    for layer in &mut cache.k_scales {{
        for i in 0..len {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    for layer in &mut cache.v_scales {{
        for i in 0..len {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    cache.len = len;
    eprintln!("KV cache loaded ({{}} positions, int8)", len);
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn apply_repeat_penalty(logits: &mut [f32], recent_tokens: &[u32], penalty: f32) {{
    if penalty <= 1.0 {{ return; }}
    for &tok in recent_tokens {{
        let idx = tok as usize;
        if idx < logits.len() {{
            if logits[idx] > 0.0 {{ logits[idx] /= penalty; }} else {{ logits[idx] *= penalty; }}
        }}
    }}
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    for l in logits.iter_mut() {{ *l /= temperature; }}
    if top_k > 0 && top_k < logits.len() {{
        let mut indices: Vec<usize> = (0..logits.len()).collect();
        indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
        let threshold = logits[indices[top_k - 1]];
        for l in logits.iter_mut() {{ if *l < threshold {{ *l = f32::NEG_INFINITY; }} }}
    }}
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary (embedded weights)");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        println!("  Weights:      {{:.1}} MB (embedded)", WEIGHTS_BYTES.len() as f64 / 1e6);
        // Compute KV cache size: int8 K+V data + f32 per-token scales
        let kv_data_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * model::NUM_KV_HEADS * model::HEAD_DIM * 1 * 2;
        let kv_scale_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * 4 * 2;
        let kv_bytes = kv_data_bytes + kv_scale_bytes;
        println!("  KV cache:     {{:.1}} MB (int8, max_seq_len={{}})", (kv_bytes as f64) / 1e6, model::MAX_SEQ_LEN);
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let top_p = parse_f32_arg(&args, "--top-p", 0.9);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let repeat_penalty = parse_f32_arg(&args, "--repeat-penalty", 1.1);
    let seed = args.windows(2).find(|w| w[0] == "--seed").and_then(|w| w[1].parse::<u64>().ok()).unwrap_or(0xdeadbeef12345678);
    let quiet = args.iter().any(|a| a == "--quiet" || a == "-q");
    let save_cache_path = args.windows(2).find(|w| w[0] == "--save-cache").map(|w| w[1].clone());
    let load_cache_path = args.windows(2).find(|w| w[0] == "--load-cache").map(|w| w[1].clone());
    let prompt = args.iter().skip(1).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden} | weights embedded");

    let t_load = std::time::Instant::now();
    eprintln!("Loading tokenizer (embedded)...");
    let tokenizer = tokenizers::Tokenizer::from_bytes(TOKENIZER_BYTES).expect("failed to load tokenizer");

    eprintln!("Parsing weights (embedded, {{:.1}} MB)...", WEIGHTS_BYTES.len() as f64 / 1e6);
{weight_slice_code_embedded}
    eprintln!("Load time: {{:.2}}s", t_load.elapsed().as_secs_f64());
    let mut cache = model::KVCache::new();
    if let Some(ref cp) = load_cache_path {{ load_kv_cache(cp, &mut cache); }}

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let prompt_tokens: Vec<u32> = enc.get_ids().to_vec();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", prompt_tokens.len(), temperature, top_k, max_tokens);

    // Prefill: process entire prompt in one batched pass, filling the KV cache
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = seed;
    let mut logits = model::forward_prefill(&prompt_tokens, &weights, &mut cache);
    let mut next = sample(&mut logits, temperature, top_k, top_p, &mut rng_state);
    eprintln!("Prefill: {{:.1}} tok/s", prompt_tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    if !quiet {{ print!("{{}}", prompt); }}
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut recent_tokens: Vec<u32> = prompt_tokens.clone();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        if !quiet {{
            let text = tokenizer.decode(&[next], true).unwrap_or_default();
            print!("{{}}", text);
            std::io::stdout().flush().ok();
        }}
        recent_tokens.push(next);
        let mut l = model::forward(next, &weights, &mut cache);
        apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
        next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
        gen_count += 1;
    }}
    if !quiet {{ println!(); }}
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
    if let Some(ref cp) = save_cache_path {{ save_kv_cache(cp, &cache); }}
}}
"##
    )
}

/// Errors during project generation.
#[derive(Debug, thiserror::Error)]
pub enum ProjectError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("codegen error: {0}")]
    Codegen(#[from] emit::CodegenError),
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::graph_builder;

    fn tiny_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 2,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 64,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
            lm_head_dtype: None,
            sliding_window_size: None,
            qkv_bias: false,
            hidden_activation: HiddenActivation::SiLU,
        }
    }

    #[test]
    fn generate_project_creates_files() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_project");
        let _ = fs::remove_dir_all(&dir);

        generate_project(&graph, &dir, "test-model", false).unwrap();

        assert!(dir.join("Cargo.toml").exists());
        assert!(dir.join("src/model.rs").exists());
        assert!(dir.join("src/main.rs").exists());

        let cargo = fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("test-model"));
        assert!(cargo.contains("rayon"));
        assert!(cargo.contains("memmap2"));
        assert!(cargo.contains("tokenizers"));

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("load_weights"));
        assert!(main.contains("fn sample("));
        assert!(main.contains("--temp"));
        assert!(main.contains("--top-k"));
        assert!(main.contains("--top-p"));
        assert!(main.contains("--repeat-penalty"));
        assert!(main.contains("--max-tokens"));
        assert!(main.contains("--interactive"));
        assert!(main.contains("--version"));
        assert!(main.contains("--quiet"));
        assert!(main.contains("--save-cache"));
        assert!(main.contains("Load time:"));

        // Verify Cargo.toml has all profile settings
        assert!(cargo.contains("lto = \"fat\""));
        assert!(cargo.contains("strip = true"));
        assert!(cargo.contains("panic = \"abort\""));
        assert!(cargo.contains("codegen-units = 1"));

        // Model.rs should have key constants and functions
        let model_rs = fs::read_to_string(dir.join("src/model.rs")).unwrap();
        assert!(model_rs.contains("pub const HIDDEN_SIZE"));
        assert!(model_rs.contains("pub const NUM_LAYERS"));
        assert!(model_rs.contains("pub const MAX_SEQ_LEN"));
        assert!(model_rs.contains("pub fn forward("));
        assert!(model_rs.contains("pub struct Weights"));
        assert!(model_rs.contains("pub struct KVCache"));
        assert!(model_rs.contains("pub fn reset"));
        assert!(model_rs.contains("pub fn memory_bytes"));
        assert!(model_rs.contains("impl Default for KVCache"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_project_embedded_mode() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_embedded");
        let _ = fs::remove_dir_all(&dir);

        generate_project(&graph, &dir, "test-embedded", true).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("include_bytes!"));
        assert!(main.contains("WEIGHTS_BYTES"));
        assert!(main.contains("TOKENIZER_BYTES"));
        assert!(main.contains("from_bytes"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn cargo_toml_sanitizes_name() {
        let toml = generate_cargo_toml("My Model/v2.0");
        assert!(toml.contains("name = \"my-model-v2-0\""));
    }

    #[test]
    fn generate_main_has_rayon_in_cargo() {
        let toml = generate_cargo_toml("my-model");
        assert!(
            toml.contains("rayon"),
            "generated Cargo.toml should contain rayon dependency"
        );
    }

    #[test]
    fn chat_clear_uses_reset_not_new() {
        // The /clear command should use cache.reset() not KVCache::new()
        // (which would re-allocate the entire cache).
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_chat_reset");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-chat", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        // Find /clear handler and verify it uses cache.reset()
        let clear_idx = main
            .find("if input == \"/clear\"")
            .expect("clear handler missing");
        let after_clear = &main[clear_idx..clear_idx + 200];
        assert!(
            after_clear.contains("cache.reset()"),
            "expected cache.reset() in /clear handler"
        );
        assert!(
            after_clear.contains("recent_tokens.clear()"),
            "expected recent_tokens.clear() in /clear handler"
        );
        assert!(
            !after_clear.contains("KVCache::new()"),
            "should not re-allocate cache on /clear"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn seed_flag_supported() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_seed");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-seed", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("--seed"), "should support --seed flag");
        assert!(main.contains("let seed = "), "should parse seed");
        assert!(
            main.contains("let mut rng_state: u64 = seed;"),
            "should use parsed seed"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn version_output_has_kv_cache_info() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_version_kv");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-ver", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(
            main.contains("KV cache:"),
            "version output should show KV cache size"
        );
        assert!(
            main.contains("kv_bytes"),
            "should compute KV bytes from constants"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_project_as_lib_creates_lib_rs_not_main_rs() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_lib_crate");
        let _ = fs::remove_dir_all(&dir);

        generate_project_as_lib(&graph, &dir, "draft").unwrap();

        assert!(dir.join("Cargo.toml").exists(), "Cargo.toml should exist");
        assert!(dir.join("src/lib.rs").exists(), "src/lib.rs should exist");
        assert!(
            dir.join("src/model.rs").exists(),
            "src/model.rs should exist"
        );
        assert!(
            !dir.join("src/main.rs").exists(),
            "src/main.rs should NOT exist for lib crate"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_project_as_lib_cargo_toml_has_lib_section() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_lib_cargo");
        let _ = fs::remove_dir_all(&dir);

        generate_project_as_lib(&graph, &dir, "draft").unwrap();

        let cargo = fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(
            cargo.contains("[lib]"),
            "Cargo.toml should have [lib] section"
        );
        assert!(
            cargo.contains("name = \"draft\""),
            "lib name should be 'draft'"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_project_as_lib_lib_rs_reexports_model() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_lib_reexport");
        let _ = fs::remove_dir_all(&dir);

        generate_project_as_lib(&graph, &dir, "target-model").unwrap();

        let lib_rs = fs::read_to_string(dir.join("src/lib.rs")).unwrap();
        assert!(
            lib_rs.contains("pub mod model;"),
            "lib.rs should re-export model module"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn main_uses_forward_prefill_for_prompt() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_prefill_main");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-prefill", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(
            main.contains("model::forward_prefill("),
            "main.rs should call forward_prefill for prompt processing"
        );
        // Prefill call should appear before the generation loop
        let prefill_pos = main
            .find("model::forward_prefill(")
            .expect("forward_prefill call missing");
        let gen_loop_pos = main
            .find("for _ in 0..max_tokens")
            .expect("generation loop missing");
        assert!(
            prefill_pos < gen_loop_pos,
            "forward_prefill should be called before the generation loop"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn main_uses_prompt_tokens_vec_for_prefill() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_prefill_vec");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-prefill-vec", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        // The tokens should be collected into a Vec<u32> and passed to forward_prefill
        assert!(
            main.contains("let prompt_tokens: Vec<u32>"),
            "main.rs should collect prompt tokens into Vec<u32>"
        );
        assert!(
            main.contains("model::forward_prefill(&prompt_tokens,"),
            "main.rs should pass &prompt_tokens to forward_prefill"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn embedded_main_uses_forward_prefill_for_prompt() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_embedded_prefill");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-embedded-prefill", true).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(
            main.contains("model::forward_prefill("),
            "embedded main.rs should call forward_prefill for prompt processing"
        );
        // forward_prefill should be called before the generation loop
        let prefill_pos = main
            .find("model::forward_prefill(")
            .expect("forward_prefill call missing in embedded main");
        let gen_loop_pos = main
            .find("for _ in 0..max_tokens")
            .expect("generation loop missing");
        assert!(
            prefill_pos < gen_loop_pos,
            "forward_prefill should be called before the generation loop in embedded mode"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn interactive_mode_uses_forward_prefill() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_interactive_prefill");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-interactive-prefill", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        // Interactive mode should also use forward_prefill for each user turn
        let interactive_start = main
            .find("Interactive mode")
            .expect("interactive mode section missing");
        let interactive_section = &main[interactive_start..];
        assert!(
            interactive_section.contains("forward_prefill("),
            "interactive mode should use forward_prefill for user input"
        );

        let _ = fs::remove_dir_all(&dir);
    }
}
