//! Generate a complete Cargo project from a computation graph.
//!
//! Creates a directory structure with:
//! - Cargo.toml (with tokenizers dependency)
//! - src/model.rs (kernels + forward function)
//! - src/main.rs (weight loader + tokenizer + generation loop)

use std::fs;
use std::path::Path;

use forgellm_frontend::ir::*;

use crate::emit;

/// Generate a complete Cargo project from a computation graph.
pub fn generate_project(
    graph: &Graph,
    output_dir: &Path,
    model_name: &str,
    embed_weights: bool,
) -> Result<(), ProjectError> {
    let config = graph
        .config
        .as_ref()
        .ok_or(ProjectError::Codegen(emit::CodegenError::MissingConfig))?;

    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(ProjectError::Io)?;

    // Generate model.rs
    let model_code = emit::generate(graph).map_err(ProjectError::Codegen)?;
    fs::write(src_dir.join("model.rs"), &model_code).map_err(ProjectError::Io)?;

    // Generate Cargo.toml
    fs::write(
        output_dir.join("Cargo.toml"),
        generate_cargo_toml(model_name),
    )
    .map_err(ProjectError::Io)?;

    // Generate main.rs
    let main_code = if embed_weights {
        generate_main_embedded(config)
    } else {
        generate_main(config)
    };
    fs::write(src_dir.join("main.rs"), main_code).map_err(ProjectError::Io)?;

    Ok(())
}

fn generate_cargo_toml(model_name: &str) -> String {
    let sanitized = model_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string();

    format!(
        r#"[package]
name = "{sanitized}"
version = "0.1.0"
edition = "2021"
description = "AOT-compiled LLM inference binary generated by ForgeLLM"

[dependencies]
tokenizers = {{ version = "0.21", default-features = false, features = ["onig"] }}
rayon = "1.10"
memmap2 = "0.9"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn generate_main(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let _arch_lower = arch.to_lowercase();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})

mod model;

use std::env;
use std::io::Write;

fn load_weights(path: &str) -> Vec<f32> {{
    let file = std::fs::File::open(path).expect("failed to open weights");
    let mmap = unsafe {{ memmap2::Mmap::map(&file) }}.expect("failed to mmap weights");
    // Fast path: direct memcpy from mmap to f32 Vec (assumes little-endian, aligned)
    let n = mmap.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {{
        std::ptr::copy_nonoverlapping(
            mmap.as_ptr() as *const f32,
            out.as_mut_ptr(),
            n,
        );
        out.set_len(n);
    }}
    out
}}

fn save_kv_cache(path: &str, cache: &model::KVCache) {{
    let kv = {kv_size};
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(&(cache.len as u64).to_le_bytes());
    for layer in &cache.k {{
        for &val in &layer[..cache.len * kv] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    for layer in &cache.v {{
        for &val in &layer[..cache.len * kv] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    std::fs::write(path, &data).expect("failed to save cache");
    eprintln!("KV cache saved ({{}} positions)", cache.len);
}}

fn load_kv_cache(path: &str, cache: &mut model::KVCache) {{
    let kv = {kv_size};
    let data = std::fs::read(path).expect("failed to read cache");
    let len = u64::from_le_bytes(data[0..8].try_into().unwrap()) as usize;
    let mut off = 8;
    for layer in &mut cache.k {{
        for i in 0..len * kv {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    for layer in &mut cache.v {{
        for i in 0..len * kv {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    cache.len = len;
    eprintln!("KV cache loaded ({{}} positions)", len);
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn apply_repeat_penalty(logits: &mut [f32], recent_tokens: &[u32], penalty: f32) {{
    if penalty <= 1.0 {{ return; }}
    for &tok in recent_tokens {{
        let idx = tok as usize;
        if idx < logits.len() {{
            if logits[idx] > 0.0 {{ logits[idx] /= penalty; }} else {{ logits[idx] *= penalty; }}
        }}
    }}
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, top_p: f32, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    // Apply temperature
    for l in logits.iter_mut() {{ *l /= temperature; }}
    // Softmax
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    // Sort indices by probability (descending)
    let mut indices: Vec<usize> = (0..logits.len()).collect();
    indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
    // Apply top-k
    if top_k > 0 && top_k < logits.len() {{
        for &idx in &indices[top_k..] {{ logits[idx] = 0.0; }}
    }}
    // Apply top-p (nucleus sampling)
    if top_p > 0.0 && top_p < 1.0 {{
        let mut cumsum = 0.0f32;
        for &idx in &indices {{
            cumsum += logits[idx];
            if cumsum > top_p {{
                logits[idx] = 0.0;
            }}
        }}
    }}
    // Renormalize
    sum = logits.iter().copied().sum();
    if sum > 0.0 {{ for l in logits.iter_mut() {{ *l /= sum; }} }}
    // Sample from distribution
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        // Compute weight count (per layer + embeddings + final norm + lm_head)
        let per_layer = model::HIDDEN_SIZE
            + model::HIDDEN_SIZE * model::NUM_HEADS * model::HEAD_DIM
            + 2 * model::HIDDEN_SIZE * model::NUM_KV_HEADS * model::HEAD_DIM
            + model::HIDDEN_SIZE * model::NUM_HEADS * model::HEAD_DIM
            + model::HIDDEN_SIZE
            + 3 * model::HIDDEN_SIZE * model::INTERMEDIATE_SIZE;
        let total_params = 2 * model::VOCAB_SIZE * model::HIDDEN_SIZE
            + model::NUM_LAYERS * per_layer
            + model::HIDDEN_SIZE;
        println!("  Parameters:   {{:.1}}M", (total_params as f64) / 1e6);
        println!("  Weights:      {{:.1}} MB (f32)", (total_params as f64 * 4.0) / 1e6);
        // Each forward pass does ~2*params multiply-add operations
        let flops_per_token = 2 * total_params;
        println!("  FLOPs/token:  {{:.2}} GFLOP", (flops_per_token as f64) / 1e9);
        // Compute KV cache size without allocating
        let kv_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * model::NUM_KV_HEADS * model::HEAD_DIM * 4 * 2;
        println!("  KV cache:     {{:.1}} MB (max_seq_len={{}})", (kv_bytes as f64) / 1e6, model::MAX_SEQ_LEN);
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    if args.len() < 3 {{
        eprintln!("Usage: {{}} <weights.bin> <tokenizer.json> [prompt] [--temp T] [--top-k K] [--max-tokens N]", args[0]);
        eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden}");
        eprintln!("       {{}} --version", args[0]);
        std::process::exit(1);
    }}

    let weights_path = &args[1];
    let tokenizer_path = &args[2];
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let top_p = parse_f32_arg(&args, "--top-p", 0.9);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let repeat_penalty = parse_f32_arg(&args, "--repeat-penalty", 1.1);
    let seed = args.windows(2).find(|w| w[0] == "--seed").and_then(|w| w[1].parse::<u64>().ok()).unwrap_or(0xdeadbeef12345678);
    let quiet = args.iter().any(|a| a == "--quiet" || a == "-q");
    let save_cache_path = args.windows(2).find(|w| w[0] == "--save-cache").map(|w| w[1].clone());
    let load_cache_path = args.windows(2).find(|w| w[0] == "--load-cache").map(|w| w[1].clone());
    let prompt = args.iter().skip(3).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    let t_load = std::time::Instant::now();
    eprintln!("Loading tokenizer...");
    let tokenizer = tokenizers::Tokenizer::from_file(tokenizer_path).expect("failed to load tokenizer");

    eprintln!("Loading weights...");
    let w = load_weights(weights_path);
    eprintln!("Load time: {{:.2}}s", t_load.elapsed().as_secs_f64());
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};
    let mut cache = model::KVCache::new();
    if let Some(ref cp) = load_cache_path {{ load_kv_cache(cp, &mut cache); }}

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let tokens = enc.get_ids();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", tokens.len(), temperature, top_k, max_tokens);

    // Prefill
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = seed;
    let mut next = 0u32;
    for &tok in tokens {{ let mut l = model::forward(tok, &weights, &mut cache); next = sample(&mut l, temperature, top_k, top_p, &mut rng_state); }}
    eprintln!("Prefill: {{:.1}} tok/s", tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    if !quiet {{ print!("{{}}", prompt); }}
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut recent_tokens: Vec<u32> = tokens.to_vec();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        if !quiet {{
            let text = tokenizer.decode(&[next], true).unwrap_or_default();
            print!("{{}}", text);
            std::io::stdout().flush().ok();
        }}
        recent_tokens.push(next);
        let mut l = model::forward(next, &weights, &mut cache);
        apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
        next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
        gen_count += 1;
    }}
    if !quiet {{ println!(); }}
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
    if let Some(ref cp) = save_cache_path {{ save_kv_cache(cp, &cache); }}

    // Interactive chat mode
    if args.iter().any(|a| a == "--interactive" || a == "--chat") {{
        eprintln!("\n--- Interactive mode (type /quit to exit) ---");
        loop {{
            eprint!("> ");
            std::io::stderr().flush().ok();
            let mut input = String::new();
            if std::io::stdin().read_line(&mut input).is_err() || input.trim().is_empty() {{ continue; }}
            let input = input.trim();
            if input == "/quit" || input == "/exit" {{ break; }}
            if input == "/clear" {{
                cache.reset();
                recent_tokens.clear();
                eprintln!("Cache cleared.");
                continue;
            }}

            let enc2 = tokenizer.encode(input, false).expect("encode failed");
            let toks2 = enc2.get_ids();
            for &tok in toks2 {{
                let mut l = model::forward(tok, &weights, &mut cache);
                next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
            }}
            let t2 = std::time::Instant::now();
            let mut gen2 = 0usize;
            for _ in 0..max_tokens {{
                if eos_tokens.contains(&next) {{ break; }}
                let text = tokenizer.decode(&[next], true).unwrap_or_default();
                print!("{{}}", text);
                std::io::stdout().flush().ok();
                let mut l = model::forward(next, &weights, &mut cache);
                apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
                next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
                recent_tokens.push(next);
                gen2 += 1;
            }}
            println!();
            eprintln!("[{{}} tokens, {{:.1}} tok/s]", gen2, gen2 as f64 / t2.elapsed().as_secs_f64());
        }}
    }}
}}
"##
    )
}

fn generate_main_embedded(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})
//! Weights and tokenizer embedded via include_bytes! — single-file deployment.

mod model;

use std::env;
use std::io::Write;

static WEIGHTS_BYTES: &[u8] = include_bytes!("../weights.bin");
static TOKENIZER_BYTES: &[u8] = include_bytes!("../tokenizer.json");

fn bytes_to_f32(bytes: &[u8]) -> Vec<f32> {{
    let n = bytes.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {{
        std::ptr::copy_nonoverlapping(bytes.as_ptr() as *const f32, out.as_mut_ptr(), n);
        out.set_len(n);
    }}
    out
}}

fn save_kv_cache(path: &str, cache: &model::KVCache) {{
    let kv = {kv_size};
    let mut data: Vec<u8> = Vec::new();
    data.extend_from_slice(&(cache.len as u64).to_le_bytes());
    for layer in &cache.k {{
        for &val in &layer[..cache.len * kv] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    for layer in &cache.v {{
        for &val in &layer[..cache.len * kv] {{ data.extend_from_slice(&val.to_le_bytes()); }}
    }}
    std::fs::write(path, &data).expect("failed to save cache");
    eprintln!("KV cache saved ({{}} positions)", cache.len);
}}

fn load_kv_cache(path: &str, cache: &mut model::KVCache) {{
    let kv = {kv_size};
    let data = std::fs::read(path).expect("failed to read cache");
    let len = u64::from_le_bytes(data[0..8].try_into().unwrap()) as usize;
    let mut off = 8;
    for layer in &mut cache.k {{
        for i in 0..len * kv {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    for layer in &mut cache.v {{
        for i in 0..len * kv {{ layer[i] = f32::from_le_bytes(data[off..off+4].try_into().unwrap()); off += 4; }}
    }}
    cache.len = len;
    eprintln!("KV cache loaded ({{}} positions)", len);
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn apply_repeat_penalty(logits: &mut [f32], recent_tokens: &[u32], penalty: f32) {{
    if penalty <= 1.0 {{ return; }}
    for &tok in recent_tokens {{
        let idx = tok as usize;
        if idx < logits.len() {{
            if logits[idx] > 0.0 {{ logits[idx] /= penalty; }} else {{ logits[idx] *= penalty; }}
        }}
    }}
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    for l in logits.iter_mut() {{ *l /= temperature; }}
    if top_k > 0 && top_k < logits.len() {{
        let mut indices: Vec<usize> = (0..logits.len()).collect();
        indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
        let threshold = logits[indices[top_k - 1]];
        for l in logits.iter_mut() {{ if *l < threshold {{ *l = f32::NEG_INFINITY; }} }}
    }}
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary (embedded weights)");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        println!("  Weights:      {{:.1}} MB (embedded)", WEIGHTS_BYTES.len() as f64 / 1e6);
        let kv_bytes = model::NUM_LAYERS * model::MAX_SEQ_LEN * model::NUM_KV_HEADS * model::HEAD_DIM * 4 * 2;
        println!("  KV cache:     {{:.1}} MB (max_seq_len={{}})", (kv_bytes as f64) / 1e6, model::MAX_SEQ_LEN);
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let top_p = parse_f32_arg(&args, "--top-p", 0.9);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let repeat_penalty = parse_f32_arg(&args, "--repeat-penalty", 1.1);
    let seed = args.windows(2).find(|w| w[0] == "--seed").and_then(|w| w[1].parse::<u64>().ok()).unwrap_or(0xdeadbeef12345678);
    let quiet = args.iter().any(|a| a == "--quiet" || a == "-q");
    let save_cache_path = args.windows(2).find(|w| w[0] == "--save-cache").map(|w| w[1].clone());
    let load_cache_path = args.windows(2).find(|w| w[0] == "--load-cache").map(|w| w[1].clone());
    let prompt = args.iter().skip(1).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden} | weights embedded");

    let t_load = std::time::Instant::now();
    eprintln!("Loading tokenizer (embedded)...");
    let tokenizer = tokenizers::Tokenizer::from_bytes(TOKENIZER_BYTES).expect("failed to load tokenizer");

    eprintln!("Parsing weights (embedded, {{:.1}} MB)...", WEIGHTS_BYTES.len() as f64 / 1e6);
    let w = bytes_to_f32(WEIGHTS_BYTES);
    eprintln!("Load time: {{:.2}}s", t_load.elapsed().as_secs_f64());
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};
    let mut cache = model::KVCache::new();
    if let Some(ref cp) = load_cache_path {{ load_kv_cache(cp, &mut cache); }}

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let tokens = enc.get_ids();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", tokens.len(), temperature, top_k, max_tokens);

    // Prefill
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = seed;
    let mut next = 0u32;
    for &tok in tokens {{ let mut l = model::forward(tok, &weights, &mut cache); next = sample(&mut l, temperature, top_k, top_p, &mut rng_state); }}
    eprintln!("Prefill: {{:.1}} tok/s", tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    if !quiet {{ print!("{{}}", prompt); }}
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut recent_tokens: Vec<u32> = tokens.to_vec();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        if !quiet {{
            let text = tokenizer.decode(&[next], true).unwrap_or_default();
            print!("{{}}", text);
            std::io::stdout().flush().ok();
        }}
        recent_tokens.push(next);
        let mut l = model::forward(next, &weights, &mut cache);
        apply_repeat_penalty(&mut l, &recent_tokens, repeat_penalty);
        next = sample(&mut l, temperature, top_k, top_p, &mut rng_state);
        gen_count += 1;
    }}
    if !quiet {{ println!(); }}
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
    if let Some(ref cp) = save_cache_path {{ save_kv_cache(cp, &cache); }}
}}
"##
    )
}

/// Errors during project generation.
#[derive(Debug, thiserror::Error)]
pub enum ProjectError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("codegen error: {0}")]
    Codegen(#[from] emit::CodegenError),
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgellm_frontend::graph_builder;

    fn tiny_config() -> ModelConfig {
        ModelConfig {
            architecture: Architecture::Llama,
            hidden_size: 64,
            intermediate_size: 128,
            num_layers: 2,
            num_attention_heads: 4,
            num_kv_heads: 2,
            head_dim: 16,
            vocab_size: 256,
            max_seq_len: 64,
            rms_norm_eps: 1e-5,
            rope_theta: 10000.0,
            dtype: DType::F16,
        }
    }

    #[test]
    fn generate_project_creates_files() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_project");
        let _ = fs::remove_dir_all(&dir);

        generate_project(&graph, &dir, "test-model", false).unwrap();

        assert!(dir.join("Cargo.toml").exists());
        assert!(dir.join("src/model.rs").exists());
        assert!(dir.join("src/main.rs").exists());

        let cargo = fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("test-model"));
        assert!(cargo.contains("rayon"));
        assert!(cargo.contains("memmap2"));
        assert!(cargo.contains("tokenizers"));

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("load_weights"));
        assert!(main.contains("fn sample("));
        assert!(main.contains("--temp"));
        assert!(main.contains("--top-k"));
        assert!(main.contains("--top-p"));
        assert!(main.contains("--repeat-penalty"));
        assert!(main.contains("--max-tokens"));
        assert!(main.contains("--interactive"));
        assert!(main.contains("--version"));
        assert!(main.contains("--quiet"));
        assert!(main.contains("--save-cache"));
        assert!(main.contains("Load time:"));

        // Verify Cargo.toml has all profile settings
        assert!(cargo.contains("lto = \"fat\""));
        assert!(cargo.contains("strip = true"));
        assert!(cargo.contains("panic = \"abort\""));
        assert!(cargo.contains("codegen-units = 1"));

        // Model.rs should have key constants and functions
        let model_rs = fs::read_to_string(dir.join("src/model.rs")).unwrap();
        assert!(model_rs.contains("pub const HIDDEN_SIZE"));
        assert!(model_rs.contains("pub const NUM_LAYERS"));
        assert!(model_rs.contains("pub const MAX_SEQ_LEN"));
        assert!(model_rs.contains("pub fn forward("));
        assert!(model_rs.contains("pub struct Weights"));
        assert!(model_rs.contains("pub struct KVCache"));
        assert!(model_rs.contains("pub fn reset"));
        assert!(model_rs.contains("pub fn memory_bytes"));
        assert!(model_rs.contains("impl Default for KVCache"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_project_embedded_mode() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_embedded");
        let _ = fs::remove_dir_all(&dir);

        generate_project(&graph, &dir, "test-embedded", true).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("include_bytes!"));
        assert!(main.contains("WEIGHTS_BYTES"));
        assert!(main.contains("TOKENIZER_BYTES"));
        assert!(main.contains("from_bytes"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn cargo_toml_sanitizes_name() {
        let toml = generate_cargo_toml("My Model/v2.0");
        assert!(toml.contains("name = \"my-model-v2-0\""));
    }

    #[test]
    fn chat_clear_uses_reset_not_new() {
        // The /clear command should use cache.reset() not KVCache::new()
        // (which would re-allocate the entire cache).
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_chat_reset");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-chat", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        // Find /clear handler and verify it uses cache.reset()
        let clear_idx = main.find("if input == \"/clear\"").expect("clear handler missing");
        let after_clear = &main[clear_idx..clear_idx+200];
        assert!(after_clear.contains("cache.reset()"), "expected cache.reset() in /clear handler");
        assert!(after_clear.contains("recent_tokens.clear()"), "expected recent_tokens.clear() in /clear handler");
        assert!(!after_clear.contains("KVCache::new()"), "should not re-allocate cache on /clear");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn seed_flag_supported() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_seed");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-seed", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("--seed"), "should support --seed flag");
        assert!(main.contains("let seed = "), "should parse seed");
        assert!(main.contains("let mut rng_state: u64 = seed;"), "should use parsed seed");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn version_output_has_kv_cache_info() {
        let config = tiny_config();
        let graph = graph_builder::build_graph(&config).unwrap();
        let dir = std::env::temp_dir().join("forgellm_test_version_kv");
        let _ = fs::remove_dir_all(&dir);
        generate_project(&graph, &dir, "test-ver", false).unwrap();

        let main = fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main.contains("KV cache:"), "version output should show KV cache size");
        assert!(main.contains("kv_bytes"), "should compute KV bytes from constants");

        let _ = fs::remove_dir_all(&dir);
    }
}
