//! Generate a complete Cargo project from a computation graph.
//!
//! Creates a directory structure with:
//! - Cargo.toml (with tokenizers dependency)
//! - src/model.rs (kernels + forward function)
//! - src/main.rs (weight loader + tokenizer + generation loop)

use std::fs;
use std::path::Path;

use forgellm_frontend::ir::*;

use crate::emit;

/// Generate a complete Cargo project from a computation graph.
pub fn generate_project(
    graph: &Graph,
    output_dir: &Path,
    model_name: &str,
    embed_weights: bool,
) -> Result<(), ProjectError> {
    let config = graph
        .config
        .as_ref()
        .ok_or(ProjectError::Codegen(emit::CodegenError::MissingConfig))?;

    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(ProjectError::Io)?;

    // Generate model.rs
    let model_code = emit::generate(graph).map_err(ProjectError::Codegen)?;
    fs::write(src_dir.join("model.rs"), &model_code).map_err(ProjectError::Io)?;

    // Generate Cargo.toml
    fs::write(
        output_dir.join("Cargo.toml"),
        generate_cargo_toml(model_name),
    )
    .map_err(ProjectError::Io)?;

    // Generate main.rs
    let main_code = if embed_weights {
        generate_main_embedded(config)
    } else {
        generate_main(config)
    };
    fs::write(src_dir.join("main.rs"), main_code).map_err(ProjectError::Io)?;

    Ok(())
}

fn generate_cargo_toml(model_name: &str) -> String {
    let sanitized = model_name
        .to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string();

    format!(
        r#"[package]
name = "{sanitized}"
version = "0.1.0"
edition = "2021"
description = "AOT-compiled LLM inference binary generated by ForgeLLM"

[dependencies]
tokenizers = {{ version = "0.21", default-features = false, features = ["onig"] }}
rayon = "1.10"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
"#
    )
}

fn generate_main(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let _arch_lower = arch.to_lowercase();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})

mod model;

use std::env;
use std::io::{{Read, Write}};

fn load_weights(path: &str) -> Vec<f32> {{
    let mut file = std::fs::File::open(path).expect("failed to open weights");
    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes).expect("failed to read weights");
    bytes.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    // Apply temperature
    for l in logits.iter_mut() {{ *l /= temperature; }}
    // Top-k: zero out everything below the k-th largest
    if top_k > 0 && top_k < logits.len() {{
        let mut indices: Vec<usize> = (0..logits.len()).collect();
        indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
        let threshold = logits[indices[top_k - 1]];
        for l in logits.iter_mut() {{ if *l < threshold {{ *l = f32::NEG_INFINITY; }} }}
    }}
    // Softmax
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    // Sample from distribution
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    if args.len() < 3 {{
        eprintln!("Usage: {{}} <weights.bin> <tokenizer.json> [prompt] [--temp T] [--top-k K] [--max-tokens N]", args[0]);
        eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden}");
        eprintln!("       {{}} --version", args[0]);
        std::process::exit(1);
    }}

    let weights_path = &args[1];
    let tokenizer_path = &args[2];
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let prompt = args.iter().skip(3).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    eprintln!("Loading tokenizer...");
    let tokenizer = tokenizers::Tokenizer::from_file(tokenizer_path).expect("failed to load tokenizer");

    eprintln!("Loading weights...");
    let w = load_weights(weights_path);
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};
    let mut cache = model::KVCache::new();

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let tokens = enc.get_ids();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", tokens.len(), temperature, top_k, max_tokens);

    // Prefill
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = 0xdeadbeef12345678;
    let mut next = 0u32;
    for &tok in tokens {{ let mut l = model::forward(tok, &weights, &mut cache); next = sample(&mut l, temperature, top_k, &mut rng_state); }}
    eprintln!("Prefill: {{:.1}} tok/s", tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    print!("{{}}", prompt);
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        let text = tokenizer.decode(&[next], true).unwrap_or_default();
        print!("{{}}", text);
        std::io::stdout().flush().ok();
        let mut l = model::forward(next, &weights, &mut cache);
        next = sample(&mut l, temperature, top_k, &mut rng_state);
        gen_count += 1;
    }}
    println!();
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
}}
"##
    )
}

fn generate_main_embedded(config: &ModelConfig) -> String {
    let hidden = config.hidden_size;
    let inter = config.intermediate_size;
    let vocab = config.vocab_size;
    let num_heads = config.num_attention_heads;
    let num_kv_heads = config.num_kv_heads;
    let head_dim = config.head_dim;
    let arch = config.architecture.to_string();
    let num_layers = config.num_layers;
    let qk_size = num_heads * head_dim;
    let kv_size = num_kv_heads * head_dim;

    format!(
        r##"//! AOT-compiled inference binary generated by ForgeLLM.
//! Model: {arch} ({num_layers} layers, hidden={hidden})
//! Weights and tokenizer embedded via include_bytes! — single-file deployment.

mod model;

use std::env;
use std::io::Write;

static WEIGHTS_BYTES: &[u8] = include_bytes!("../weights.bin");
static TOKENIZER_BYTES: &[u8] = include_bytes!("../tokenizer.json");

fn bytes_to_f32(bytes: &[u8]) -> Vec<f32> {{
    bytes.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits.iter().enumerate().max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap()).map(|(i, _)| i as u32).unwrap_or(0)
}}

fn sample(logits: &mut [f32], temperature: f32, top_k: usize, rng_state: &mut u64) -> u32 {{
    if temperature <= 0.0 {{ return argmax(logits); }}
    for l in logits.iter_mut() {{ *l /= temperature; }}
    if top_k > 0 && top_k < logits.len() {{
        let mut indices: Vec<usize> = (0..logits.len()).collect();
        indices.sort_unstable_by(|&a, &b| logits[b].partial_cmp(&logits[a]).unwrap());
        let threshold = logits[indices[top_k - 1]];
        for l in logits.iter_mut() {{ if *l < threshold {{ *l = f32::NEG_INFINITY; }} }}
    }}
    let max_val = logits.iter().copied().fold(f32::NEG_INFINITY, f32::max);
    let mut sum = 0.0f32;
    for l in logits.iter_mut() {{ *l = (*l - max_val).exp(); sum += *l; }}
    for l in logits.iter_mut() {{ *l /= sum; }}
    *rng_state ^= *rng_state << 13;
    *rng_state ^= *rng_state >> 7;
    *rng_state ^= *rng_state << 17;
    let r = (*rng_state as f32) / (u64::MAX as f32);
    let mut cumsum = 0.0f32;
    for (i, &p) in logits.iter().enumerate() {{
        cumsum += p;
        if cumsum >= r {{ return i as u32; }}
    }}
    logits.len() as u32 - 1
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2).find(|w| w[0] == flag).and_then(|w| w[1].parse().ok()).unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.iter().any(|a| a == "--version" || a == "-V") {{
        println!("AOT-compiled {arch} inference binary (embedded weights)");
        println!("  Layers:       {num_layers}");
        println!("  Hidden size:  {hidden}");
        println!("  Vocab size:   {vocab}");
        println!("  Heads:        {num_heads} (KV: {num_kv_heads})");
        println!("  Head dim:     {head_dim}");
        println!("  Intermediate: {inter}");
        println!("  Weights:      {{:.1}} MB (embedded)", WEIGHTS_BYTES.len() as f64 / 1e6);
        println!("  Compiled by:  ForgeLLM (https://forgellm.dev)");
        return;
    }}
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let top_k = parse_usize_arg(&args, "--top-k", 0);
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let prompt = args.iter().skip(1).filter(|a| !a.starts_with("--")).take_while(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    eprintln!("AOT-compiled {arch} | {num_layers} layers | hidden={hidden} | weights embedded");

    eprintln!("Loading tokenizer (embedded)...");
    let tokenizer = tokenizers::Tokenizer::from_bytes(TOKENIZER_BYTES).expect("failed to load tokenizer");

    eprintln!("Parsing weights (embedded, {{:.1}} MB)...", WEIGHTS_BYTES.len() as f64 / 1e6);
    let w = bytes_to_f32(WEIGHTS_BYTES);
    let mut off = 0usize;

    let embed = w[off..off + {vocab} * {hidden}].to_vec(); off += {vocab} * {hidden};
    let mut layers = Vec::new();
    for _ in 0..{num_layers} {{
        let an = w[off..off+{hidden}].to_vec(); off += {hidden};
        let qp = w[off..off+{qk_size}*{hidden}].to_vec(); off += {qk_size}*{hidden};
        let kp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let vp = w[off..off+{kv_size}*{hidden}].to_vec(); off += {kv_size}*{hidden};
        let op = w[off..off+{hidden}*{qk_size}].to_vec(); off += {hidden}*{qk_size};
        let fn_ = w[off..off+{hidden}].to_vec(); off += {hidden};
        let gp = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let up = w[off..off+{inter}*{hidden}].to_vec(); off += {inter}*{hidden};
        let dp = w[off..off+{hidden}*{inter}].to_vec(); off += {hidden}*{inter};
        layers.push(model::LayerWeights {{ attn_norm: an, q_proj: qp, k_proj: kp, v_proj: vp, o_proj: op, ffn_norm: fn_, gate_proj: gp, up_proj: up, down_proj: dp }});
    }}
    let fnorm = w[off..off+{hidden}].to_vec(); off += {hidden};
    let lmh = w[off..off+{vocab}*{hidden}].to_vec();
    let weights = model::Weights {{ embed_tokens: embed, layers, final_norm: fnorm, lm_head: lmh }};
    let mut cache = model::KVCache::new();

    let enc = tokenizer.encode(prompt.as_str(), false).expect("encode failed");
    let tokens = enc.get_ids();
    eprintln!("Prompt: {{}} tokens | temp={{}} top_k={{}} max_tokens={{}}", tokens.len(), temperature, top_k, max_tokens);

    // Prefill
    let t0 = std::time::Instant::now();
    let mut rng_state: u64 = 0xdeadbeef12345678;
    let mut next = 0u32;
    for &tok in tokens {{ let mut l = model::forward(tok, &weights, &mut cache); next = sample(&mut l, temperature, top_k, &mut rng_state); }}
    eprintln!("Prefill: {{:.1}} tok/s", tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Generate
    print!("{{}}", prompt);
    let t1 = std::time::Instant::now();
    // Detect EOS tokens from tokenizer
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ].iter().filter_map(|t| *t).collect();
    let mut gen_count = 0usize;
    for _ in 0..max_tokens {{
        if eos_tokens.contains(&next) {{ break; }}
        let text = tokenizer.decode(&[next], true).unwrap_or_default();
        print!("{{}}", text);
        std::io::stdout().flush().ok();
        let mut l = model::forward(next, &weights, &mut cache);
        next = sample(&mut l, temperature, top_k, &mut rng_state);
        gen_count += 1;
    }}
    println!();
    eprintln!("Generate: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)", gen_count, t1.elapsed().as_secs_f64(), gen_count as f64 / t1.elapsed().as_secs_f64());
}}
"##
    )
}

/// Errors during project generation.
#[derive(Debug, thiserror::Error)]
pub enum ProjectError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("codegen error: {0}")]
    Codegen(#[from] emit::CodegenError),
}
