//! Speculative decoding runner code generation.
//!
//! Generates a `runner/` Cargo project that depends on both a draft model library
//! and a target model library, and implements the speculative decoding loop:
//! the draft model runs N tokens ahead and the target model verifies each token.

use std::fs;
use std::path::Path;

/// Configuration for the speculative runner project.
pub struct SpeculativeRunnerConfig<'a> {
    /// Human-readable name used to derive the runner crate name.
    pub model_name: &'a str,
    /// Default number of speculative steps the draft model takes per call.
    pub draft_steps: usize,
}

/// Generate the speculative decoding runner project in `output_dir/runner/`.
///
/// Creates:
/// - `runner/Cargo.toml` — depends on `draft` and `target` local crates
/// - `runner/src/main.rs` — speculative decoding loop with CLI args
pub fn generate_speculative_runner(
    config: &SpeculativeRunnerConfig<'_>,
    output_dir: &Path,
) -> Result<(), SpeculativeError> {
    let runner_dir = output_dir.join("runner");
    let src_dir = runner_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(SpeculativeError::Io)?;

    // Cargo.toml
    let cargo_toml = generate_runner_cargo_toml(config.model_name);
    fs::write(runner_dir.join("Cargo.toml"), cargo_toml).map_err(SpeculativeError::Io)?;

    // main.rs
    let main_rs = generate_runner_main(config.draft_steps);
    fs::write(src_dir.join("main.rs"), main_rs).map_err(SpeculativeError::Io)?;

    Ok(())
}

fn sanitize_name(name: &str) -> String {
    name.to_lowercase()
        .replace(|c: char| !c.is_alphanumeric() && c != '-', "-")
        .trim_matches('-')
        .to_string()
}

fn generate_runner_cargo_toml(model_name: &str) -> String {
    let sanitized = sanitize_name(model_name);
    format!(
        r#"[package]
name = "{sanitized}-speculative"
version = "0.1.0"
edition = "2021"
description = "Speculative decoding runner generated by ForgeLLM"

[dependencies]
draft = {{ path = "../draft" }}
target = {{ path = "../target" }}
tokenizers = {{ version = "0.21", default-features = false, features = ["onig"] }}
memmap2 = "0.9"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
"#
    )
}

fn generate_runner_main(draft_steps: usize) -> String {
    format!(
        r##"//! Speculative decoding runner generated by ForgeLLM.
//!
//! The draft model runs N tokens ahead; the target model verifies each token.
//! Accept all tokens where draft == target (argmax), fall back to target on mismatch.

use std::env;
use std::io::Write;

fn load_weights(path: &str) -> Vec<f32> {{
    let file = std::fs::File::open(path).expect("failed to open weights");
    let mmap = unsafe {{ memmap2::Mmap::map(&file) }}.expect("failed to mmap weights");
    let n = mmap.len() / 4;
    let mut out = Vec::<f32>::with_capacity(n);
    unsafe {{
        std::ptr::copy_nonoverlapping(
            mmap.as_ptr() as *const f32,
            out.as_mut_ptr(),
            n,
        );
        out.set_len(n);
    }}
    out
}}

fn argmax(logits: &[f32]) -> u32 {{
    logits
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
        .map(|(i, _)| i as u32)
        .unwrap_or(0)
}}

/// Run draft model `draft_steps` times starting from `input_token`, then verify
/// each draft token with the target model.  Returns the sequence of accepted
/// tokens (at least 1 — the target token on the first mismatch, or all draft
/// tokens when every one matches).
fn speculative_step(
    input_token: u32,
    draft_steps: usize,
    draft_weights: &draft::model::Weights,
    draft_cache: &mut draft::model::KVCache,
    target_weights: &target::model::Weights,
    target_cache: &mut target::model::KVCache,
) -> Vec<u32> {{
    // 1. Run draft model `draft_steps` times.
    let mut draft_tokens: Vec<u32> = Vec::with_capacity(draft_steps);
    let mut current_token = input_token;
    for _ in 0..draft_steps {{
        let logits = draft::model::forward(current_token, draft_weights, draft_cache);
        let next_tok = argmax(&logits);
        draft_tokens.push(next_tok);
        current_token = next_tok;
    }}

    // 2. Verify with target model — run target once per draft token.
    let mut accepted: Vec<u32> = Vec::new();
    let mut verify_token = input_token;
    for (i, &draft_tok) in draft_tokens.iter().enumerate() {{
        let target_logits = target::model::forward(verify_token, target_weights, target_cache);
        let target_tok = argmax(&target_logits);
        if target_tok == draft_tok {{
            accepted.push(draft_tok);
            verify_token = draft_tok;
        }} else {{
            // Mismatch: accept target's token and roll back draft cache.
            accepted.push(target_tok);
            let rollback = draft_steps - i - 1;
            draft_cache.len -= rollback.min(draft_cache.len);
            return accepted;
        }}
    }}

    // All draft tokens accepted — target cache is now 1 token behind draft.
    // Run target one more time so both caches stay in sync.
    let _ = target::model::forward(verify_token, target_weights, target_cache);

    accepted
}}

fn parse_f32_arg(args: &[String], flag: &str, default: f32) -> f32 {{
    args.windows(2)
        .find(|w| w[0] == flag)
        .and_then(|w| w[1].parse().ok())
        .unwrap_or(default)
}}

fn parse_usize_arg(args: &[String], flag: &str, default: usize) -> usize {{
    args.windows(2)
        .find(|w| w[0] == flag)
        .and_then(|w| w[1].parse().ok())
        .unwrap_or(default)
}}

fn main() {{
    let args: Vec<String> = env::args().collect();
    if args.len() < 5 {{
        eprintln!(
            "Usage: {{}} <draft_weights.bin> <target_weights.bin> <tokenizer.json> <prompt> \
             [--draft-steps N] [--max-tokens N] [--temp F] [--seed N]",
            args[0]
        );
        std::process::exit(1);
    }}

    let draft_weights_path = &args[1];
    let target_weights_path = &args[2];
    let tokenizer_path = &args[3];
    let prompt = args[4..].iter().filter(|a| !a.starts_with("--")).cloned().collect::<Vec<_>>().join(" ");
    let prompt = if prompt.is_empty() {{ "Hello".to_string() }} else {{ prompt }};

    let draft_steps = parse_usize_arg(&args, "--draft-steps", {draft_steps});
    let max_tokens = parse_usize_arg(&args, "--max-tokens", 128);
    let temperature = parse_f32_arg(&args, "--temp", 0.0);
    let seed = args.windows(2)
        .find(|w| w[0] == "--seed")
        .and_then(|w| w[1].parse::<u64>().ok())
        .unwrap_or(0xdeadbeef12345678);

    let _ = temperature; // reserved for future stochastic speculative decoding
    let _ = seed;        // reserved for future stochastic sampling

    let t_load = std::time::Instant::now();
    eprintln!("Loading tokenizer...");
    let tokenizer = tokenizers::Tokenizer::from_file(tokenizer_path)
        .expect("failed to load tokenizer");

    eprintln!("Loading draft weights from {{draft_weights_path}}...");
    let draft_w_flat = load_weights(draft_weights_path);

    eprintln!("Loading target weights from {{target_weights_path}}...");
    let target_w_flat = load_weights(target_weights_path);

    // Build weight structs from flat buffers.
    let draft_weights = draft::model::Weights::from_flat(&draft_w_flat);
    let target_weights = target::model::Weights::from_flat(&target_w_flat);

    eprintln!("Load time: {{:.2}}s", t_load.elapsed().as_secs_f64());

    let mut draft_cache = draft::model::KVCache::new();
    let mut target_cache = target::model::KVCache::new();

    eprintln!("Encoding prompt...");
    let enc = tokenizer
        .encode(prompt.as_str(), false)
        .expect("encode failed");
    let tokens = enc.get_ids();
    eprintln!(
        "Prompt: {{}} tokens | draft_steps={{}} max_tokens={{}}",
        tokens.len(),
        draft_steps,
        max_tokens
    );

    // Prefill both caches with the prompt tokens.
    let t0 = std::time::Instant::now();
    let mut next = 0u32;
    for &tok in tokens {{
        let dl = draft::model::forward(tok, &draft_weights, &mut draft_cache);
        let tl = target::model::forward(tok, &target_weights, &mut target_cache);
        next = argmax(&tl);
        let _ = argmax(&dl); // keep draft cache warm
    }}
    eprintln!("Prefill: {{:.1}} tok/s", tokens.len() as f64 / t0.elapsed().as_secs_f64());

    // Detect EOS tokens from tokenizer.
    let eos_tokens: Vec<u32> = [
        tokenizer.token_to_id("</s>"),
        tokenizer.token_to_id("<|endoftext|>"),
        tokenizer.token_to_id("<|im_end|>"),
        tokenizer.token_to_id("<|eot_id|>"),
    ]
    .iter()
    .filter_map(|t| *t)
    .collect();

    print!("{{prompt}}");
    std::io::stdout().flush().ok();

    let t1 = std::time::Instant::now();
    let mut gen_count = 0usize;

    'gen: loop {{
        if gen_count >= max_tokens {{ break; }}
        if eos_tokens.contains(&next) {{ break; }}

        let accepted = speculative_step(
            next,
            draft_steps,
            &draft_weights,
            &mut draft_cache,
            &target_weights,
            &mut target_cache,
        );

        for tok in accepted {{
            if eos_tokens.contains(&tok) {{ break 'gen; }}
            let text = tokenizer.decode(&[tok], true).unwrap_or_default();
            print!("{{text}}");
            std::io::stdout().flush().ok();
            next = tok;
            gen_count += 1;
            if gen_count >= max_tokens {{ break 'gen; }}
        }}
    }}

    println!();
    eprintln!(
        "Generated: {{}} tokens in {{:.2}}s ({{:.1}} tok/s)",
        gen_count,
        t1.elapsed().as_secs_f64(),
        gen_count as f64 / t1.elapsed().as_secs_f64()
    );
}}
"##,
        draft_steps = draft_steps,
    )
}

/// Errors during speculative runner generation.
#[derive(Debug, thiserror::Error)]
pub enum SpeculativeError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn runner_config() -> SpeculativeRunnerConfig<'static> {
        SpeculativeRunnerConfig {
            model_name: "my-model",
            draft_steps: 4,
        }
    }

    #[test]
    fn generate_speculative_runner_creates_cargo_toml() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_cargo");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        assert!(
            dir.join("runner/Cargo.toml").exists(),
            "runner/Cargo.toml should exist"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn generate_speculative_runner_creates_main_rs() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_main");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        assert!(
            dir.join("runner/src/main.rs").exists(),
            "runner/src/main.rs should exist"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn runner_cargo_toml_has_draft_and_target_dependencies() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_deps");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        let cargo = fs::read_to_string(dir.join("runner/Cargo.toml")).unwrap();
        assert!(
            cargo.contains("draft = { path = \"../draft\" }"),
            "Cargo.toml should depend on draft crate"
        );
        assert!(
            cargo.contains("target = { path = \"../target\" }"),
            "Cargo.toml should depend on target crate"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn runner_main_rs_contains_speculative_step_function() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_fn");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        let main_rs = fs::read_to_string(dir.join("runner/src/main.rs")).unwrap();
        assert!(
            main_rs.contains("fn speculative_step("),
            "main.rs should contain speculative_step function"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn runner_main_rs_contains_draft_steps_usage() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_steps");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        let main_rs = fs::read_to_string(dir.join("runner/src/main.rs")).unwrap();
        assert!(
            main_rs.contains("draft_steps"),
            "main.rs should use draft_steps"
        );
        assert!(
            main_rs.contains("--draft-steps"),
            "main.rs should support --draft-steps CLI flag"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn runner_main_rs_contains_max_tokens_and_seed() {
        let dir = std::env::temp_dir().join("forgellm_spec_test_args");
        let _ = fs::remove_dir_all(&dir);

        generate_speculative_runner(&runner_config(), &dir).unwrap();

        let main_rs = fs::read_to_string(dir.join("runner/src/main.rs")).unwrap();
        assert!(
            main_rs.contains("--max-tokens"),
            "should support --max-tokens"
        );
        assert!(main_rs.contains("--temp"), "should support --temp");
        assert!(main_rs.contains("--seed"), "should support --seed");

        let _ = fs::remove_dir_all(&dir);
    }
}
